"use strict";

const DATA = {
	baseElements: [
		"air",
		"earth",
		"fire",
		"water"
	],
	elements: [
		"acid rain",
		"air",
		"airplane",
		"alarm clock",
		"Alchemist",
		"alcohol",
		"algae",
		"alien",
		"allergy",
		"alligator",
		"alpaca",
		"ambulance",
		"angel",
		"angler",
		"Animal",
		"ant",
		"Ant farm",
		"antarctica",
		"Anthill",
		"Apron",
		"aquarium",
		"Archeologist",
		"archipelago",
		"Arctic",
		"armadillo",
		"armor",
		"Arrow",
		"ash",
		"astronaut",
		"Astronaut Ice Cream",
		"Astronomer",
		"atmosphere",
		"atomic bomb",
		"aurora",
		"avalanche",
		"Aviary",
		"axe",
		"bacon",
		"bacteria",
		"baker",
		"bakery",
		"banana",
		"banana bread",
		"bandage",
		"bank",
		"barn",
		"Barrel",
		"bat",
		"batman",
		"batter",
		"Battery",
		"bayonet",
		"bbq",
		"beach",
		"beaver",
		"bee",
		"beehive",
		"Beekeeper",
		"beer",
		"Bell",
		"bicycle",
		"Big",
		"Binoculars",
		"bird",
		"Birdcage",
		"birdhouse",
		"black hole",
		"blade",
		"blender",
		"blizzard",
		"blood",
		"Blood bag",
		"blueprint",
		"boat",
		"boiler",
		"bone",
		"bonsai tree",
		"book",
		"Bottle",
		"Boulder",
		"Bow",
		"Box",
		"bread",
		"brick",
		"bridge",
		"broom",
		"Bucket",
		"bullet",
		"bulletproof vest",
		"bus",
		"butcher",
		"butter",
		"butterfly",
		"Butterfly net",
		"Cable car",
		"cactus",
		"Cadbury Eggs",
		"Cage",
		"cake",
		"camel",
		"campfire",
		"candle",
		"candy cane",
		"cannon",
		"Canvas",
		"cape",
		"car",
		"caramel",
		"Caramel Apple",
		"Caramelo",
		"carbon dioxide",
		"carrot",
		"cart",
		"cashmere",
		"castle",
		"cat",
		"catnip",
		"cauldron",
		"Cave",
		"caviar",
		"centaur",
		"cereal",
		"chain",
		"chainsaw",
		"chameleon",
		"charcoal",
		"cheese",
		"cheeseburger",
		"chicken",
		"Chicken coop",
		"chicken soup",
		"chicken wing",
		"Chill",
		"chimney",
		"chocolate",
		"chocolate milk",
		"christmas stocking",
		"christmas tree",
		"cigarette",
		"Circus",
		"city",
		"clay",
		"clock",
		"Closet",
		"cloud",
		"coal",
		"coconut",
		"coconut milk",
		"coffin",
		"cold",
		"Combustion engine",
		"computer",
		"computer mouse",
		"confetti",
		"constellation",
		"Container",
		"Continent",
		"Cook",
		"cookbook",
		"cookie",
		"Cookie cutter",
		"cookie dough",
		"Coral",
		"corpse",
		"cotton",
		"cotton candy",
		"cow",
		"crayon",
		"crow",
		"crown",
		"crystal ball",
		"cuckoo",
		"Cup",
		"Current",
		"Cutting board",
		"cyborg",
		"cyclist",
		"dam",
		"Darkness",
		"darth vader",
		"Dawn",
		"day",
		"Death",
		"desert",
		"dew",
		"diamond",
		"dinosaur",
		"Diver",
		"doctor",
		"dog",
		"Doge",
		"doghouse",
		"Domestication",
		"Don Quixote",
		"donut",
		"double rainbow!",
		"dough",
		"dragon",
		"drone",
		"drum",
		"drunk",
		"dry ice",
		"duck",
		"duckling",
		"dune",
		"dust",
		"dynamite",
		"eagle",
		"earth",
		"earthquake",
		"eclipse",
		"egg",
		"egg timer",
		"electric car",
		"electric eel",
		"electrician",
		"electricity",
		"email",
		"energy",
		"engineer",
		"eruption",
		"excalibur",
		"Excavator",
		"explosion",
		"fabric",
		"Factory",
		"fairy tale",
		"family",
		"family tree",
		"farm",
		"farmer",
		"faun",
		"fence",
		"field",
		"fire",
		"fire extinguisher",
		"Firefighter",
		"fireman",
		"fireplace",
		"Firestation",
		"firetruck",
		"Firewall",
		"fireworks",
		"fish",
		"fish and chips",
		"fishing rod",
		"flamethrower",
		"flashlight",
		"flood",
		"flour",
		"flower",
		"flute",
		"flying fish",
		"flying squirrel",
		"fog",
		"Force knight",
		"forest",
		"Fork",
		"fortune cookie",
		"fossil",
		"fountain",
		"fox",
		"frankenstein",
		"Frankenstein's monster",
		"french fries",
		"fridge",
		"frog",
		"frozen yogurt",
		"fruit",
		"fruit tree",
		"Fun Dip",
		"galaxy",
		"Galaxy cluster",
		"Garage",
		"garden",
		"gardener",
		"Gas",
		"geyser",
		"ghost",
		"gift",
		"gingerbread house",
		"gingerbread man",
		"glacier",
		"glass",
		"glasses",
		"gnome",
		"goat",
		"godzilla",
		"gold",
		"Goldfish",
		"golem",
		"granite",
		"grass",
		"grave",
		"gravestone",
		"graveyard",
		"greenhouse",
		"grenade",
		"grilled cheese",
		"grim reaper",
		"Guinness Float",
		"gun",
		"gunpowder",
		"Gust",
		"Hacker",
		"hail",
		"ham",
		"hamburger",
		"hammer",
		"hamster",
		"Hangar",
		"hard roe",
		"harp",
		"hay",
		"hay bale",
		"Heat",
		"hedge",
		"Hedgehog",
		"helicopter",
		"herb",
		"hero",
		"Hill",
		"hippo",
		"honey",
		"horizon",
		"horse",
		"horseshoe",
		"hospital",
		"Hot chocolate",
		"hourglass",
		"house",
		"human",
		"hummingbird",
		"hurricane",
		"husky",
		"ice",
		"ice cream",
		"ice cream truck",
		"Ice sculpture",
		"iceberg",
		"iced tea",
		"idea",
		"igloo",
		"internet",
		"Island",
		"isle",
		"ivy",
		"jack-o'-lantern",
		"jam",
		"Jar",
		"jedi",
		"jerky",
		"juice",
		"Juicy Fruit",
		"Jupiter",
		"Kaiju",
		"Katana",
		"Keyboard Cat",
		"kite",
		"Knife",
		"knight",
		"lake",
		"lamp",
		"Land",
		"Laptop",
		"lasso",
		"lava",
		"lava lamp",
		"Lawn",
		"lawn mower",
		"leaf",
		"leather",
		"Legend",
		"lemonade",
		"Lens",
		"letter",
		"Librarian",
		"library",
		"life",
		"light",
		"light bulb",
		"Light sword",
		"lighthouse",
		"Lightning",
		"lightsaber",
		"lion",
		"Liquid",
		"Little alchemy (element)",
		"livestock",
		"lizard",
		"log cabin",
		"love",
		"lumberjack",
		"mac and cheese",
		"Machine",
		"Magic",
		"Magma",
		"Mail truck",
		"Mailbox",
		"mailman",
		"manatee",
		"map",
		"Maple syrup",
		"mars",
		"marshmallows",
		"mayonnaise",
		"meat",
		"medusa",
		"Mercury",
		"mermaid",
		"metal",
		"meteor",
		"meteoroid",
		"microscope",
		"milk",
		"milk shake",
		"Milky Way",
		"Mineral",
		"minotaur",
		"mirror",
		"Mist",
		"mold",
		"monarch",
		"money",
		"monkey",
		"moon",
		"Moon rover",
		"moss",
		"moth",
		"Motion",
		"motorcycle",
		"Mounds",
		"mountain",
		"mountain goat",
		"mountain range",
		"mouse",
		"mousetrap",
		"mud",
		"mummy",
		"music",
		"Musician",
		"narwhal",
		"needle",
		"nerd",
		"Nerds",
		"Nessie",
		"nest",
		"Net",
		"newspaper",
		"night",
		"ninja",
		"Ninja Turtle",
		"nut",
		"Nuts",
		"oasis",
		"obsidian",
		"ocean",
		"oil",
		"oil lamp",
		"omelette",
		"optical fiber",
		"orchard",
		"Ore",
		"Organic matter",
		"origami",
		"ostrich",
		"owl",
		"oxygen",
		"ozone",
		"paint",
		"Painter",
		"Painting",
		"Paleontologist",
		"palm",
		"Pan flute",
		"paper",
		"paper airplane",
		"Paper cup",
		"parachute",
		"Paraglider",
		"Park",
		"parrot",
		"pasta",
		"peacock",
		"Peanut butter",
		"Peat",
		"Pebble",
		"Peeps",
		"pegasus",
		"pencil",
		"pencil sharpener",
		"penguin",
		"penicillin",
		"perfume",
		"petroleum",
		"Philosophy",
		"phoenix",
		"picnic",
		"pie",
		"pig",
		"pigeon",
		"piggy bank",
		"pillow",
		"pilot",
		"pinocchio",
		"pipe",
		"piranha",
		"pirate",
		"pirate ship",
		"pitchfork",
		"pizza",
		"planet",
		"plankton",
		"plant",
		"Plasma",
		"platypus",
		"Plow",
		"Pokki",
		"Polar bear",
		"Pollen",
		"pond",
		"Pop Rocks",
		"popsicle",
		"Post office",
		"Potato",
		"Potter",
		"pottery",
		"pressure",
		"Primordial soup",
		"printer",
		"prism",
		"pterodactyl",
		"puddle",
		"pumpkin",
		"pyramid",
		"quicksand",
		"Quicksilver",
		"rabbit",
		"rain",
		"rainbow",
		"Rainforest",
		"rat",
		"recipe",
		"Red Vines",
		"Reed",
		"reindeer",
		"Restaurant",
		"ring",
		"Ring Pop",
		"river",
		"Rivulet",
		"robot",
		"Robot vacuum",
		"Rock",
		"rocket",
		"Roe",
		"roller coaster",
		"roomba",
		"rope",
		"rose",
		"ruins",
		"ruler",
		"rust",
		"rv",
		"Sack",
		"saddle",
		"safe",
		"safety glasses",
		"sailboat",
		"sailor",
		"salt",
		"Samurai",
		"sand",
		"sand castle",
		"sandpaper",
		"sandstone",
		"sandstorm",
		"sandwich",
		"santa",
		"Sap",
		"saturn",
		"scalpel",
		"scarecrow",
		"Science",
		"scissors",
		"scorpion",
		"Scuba tank",
		"scythe",
		"sea",
		"seagull",
		"seahorse",
		"seal",
		"seaplane",
		"seasickness",
		"seaweed",
		"Seed",
		"sewing machine",
		"shark",
		"sheep",
		"sheet music",
		"Shovel",
		"shuriken",
		"sickness",
		"Silo",
		"skateboard",
		"skeleton",
		"ski goggles",
		"Skier",
		"Skittles",
		"sky",
		"skyscraper",
		"sledge",
		"Sleigh",
		"sloth",
		"Small",
		"Smartphone",
		"smog",
		"smoke",
		"smoke signal",
		"smoothie",
		"snake",
		"snow",
		"snow globe",
		"snowball",
		"snowboard",
		"Snowboarder",
		"snowman",
		"snowmobile",
		"soap",
		"soap bubble",
		"soda",
		"Soil",
		"solar cell",
		"solar system",
		"Solid",
		"sound",
		"space",
		"space station",
		"spaceship",
		"spaghetti",
		"sphinx",
		"spider",
		"Spoon",
		"Spotlight",
		"sprinkles",
		"squirrel",
		"star",
		"Starburst",
		"starfish",
		"statue",
		"steak",
		"steam",
		"steam engine",
		"steamboat",
		"steel",
		"steel wool",
		"stethoscope",
		"stone",
		"storm",
		"story",
		"Stream",
		"String phone",
		"Stun gun",
		"sugar",
		"sun",
		"sundial",
		"sunflower",
		"sunglasses",
		"super nova",
		"Supernova",
		"surfer",
		"sushi",
		"swamp",
		"sweater",
		"Swedish Fish",
		"Sweethearts",
		"swim goggles",
		"swimmer",
		"Swimming pool",
		"sword",
		"swordfish",
		"Syringe",
		"Tablet",
		"Tailor",
		"tank",
		"Tardis",
		"taser",
		"tea",
		"telescope",
		"tent",
		"The Doctor",
		"The One Ring",
		"Thermometer",
		"thread",
		"tide",
		"time",
		"titanic",
		"toast",
		"tobacco",
		"tool",
		"Toolbox",
		"Tornado",
		"toucan",
		"tractor",
		"train",
		"Trainyard",
		"treasure",
		"treasure map",
		"tree",
		"treehouse",
		"trojan horse",
		"tsunami",
		"tunnel",
		"turtle",
		"twilight",
		"Twix",
		"tyrannosaurus rex",
		"ufo",
		"umbrella",
		"unicorn",
		"Universe",
		"vacuum cleaner",
		"vampire",
		"vase",
		"Vault",
		"vegetable",
		"Venus",
		"village",
		"Vine",
		"vinegar",
		"volcano",
		"vulture",
		"wagon",
		"wall",
		"wallet",
		"wand",
		"Warmth",
		"warrior",
		"watch",
		"water",
		"water gun",
		"water lily",
		"water pipe",
		"waterfall",
		"waterwheel",
		"wave",
		"wax",
		"web",
		"werewolf",
		"wheat",
		"wheel",
		"wild animal",
		"wild boar",
		"Willy Wonka",
		"wind",
		"wind turbine",
		"windmill",
		"window",
		"Windsurfer",
		"wine",
		"wire",
		"witch",
		"wizard",
		"wolf",
		"wood",
		"woodpecker",
		"wool",
		"wrapping paper",
		"Writer",
		"x-ray",
		"yak",
		"Yeti",
		"yoda",
		"yogurt",
		"zombie",
		"Zoo"
	],
	recipes: [
		["planet", "acid rain", "Venus"],
		["air", "air", "pressure"],
		["air", "cloud", "sky"],
		["air", "cold", "Chill"],
		["Container", "air", "Scuba tank"],
		["air", "dinosaur", "pterodactyl"],
		["earth", "air", "dust"],
		["egg", "air", "bird"],
		["air", "energy", "Heat"],
		["air", "energy", "wind"],
		["air", "fire", "energy"],
		["Heat", "air", "Warmth"],
		["air", "idea", "Gas"],
		["air", "lava", "stone"],
		["air", "life", "bird"],
		["air", "metal", "rust"],
		["air", "pressure", "atmosphere"],
		["pressure", "air", "wind"],
		["air", "rain", "Mist"],
		["air", "Science", "Gas"],
		["air", "Small", "Gust"],
		["air", "soap", "soap bubble"],
		["air", "steam", "cloud"],
		["air", "steam", "Mist"],
		["air", "steel", "rust"],
		["air", "stone", "sand"],
		["air", "water", "Mist"],
		["water", "air", "rain"],
		["air", "wave", "sound"],
		["air", "wine", "vinegar"],
		["airplane", "alien", "ufo"],
		["airplane", "astronaut", "spaceship"],
		["airplane", "barn", "Hangar"],
		["blade", "airplane", "helicopter"],
		["airplane", "Container", "Hangar"],
		["airplane", "house", "Hangar"],
		["airplane", "human", "pilot"],
		["airplane", "ocean", "seaplane"],
		["airplane", "paper", "paper airplane"],
		["airplane", "robot", "drone"],
		["airplane", "sea", "seaplane"],
		["airplane", "space", "rocket"],
		["squirrel", "airplane", "flying squirrel"],
		["airplane", "wall", "Hangar"],
		["airplane", "water", "seaplane"],
		["windmill", "airplane", "helicopter"],
		["Small", "Alchemist", "Little alchemy (element)"],
		["Container", "alcohol", "Bottle"],
		["alcohol", "flower", "perfume"],
		["fruit", "alcohol", "wine"],
		["human", "alcohol", "drunk"],
		["alcohol", "rose", "perfume"],
		["alcohol", "wheat", "beer"],
		["algae", "stone", "moss"],
		["rocket", "alien", "ufo"],
		["ambulance", "barn", "Garage"],
		["ambulance", "Container", "Garage"],
		["ambulance", "house", "Garage"],
		["house", "ambulance", "hospital"],
		["ambulance", "wall", "Garage"],
		["angel", "music", "harp"],
		["angler", "rope", "Net"],
		["Animal", "Arctic", "Polar bear"],
		["Animal", "Cage", "Zoo"],
		["Animal", "Container", "Zoo"],
		["Animal", "farmer", "Domestication"],
		["Animal", "human", "Domestication"],
		["Animal", "ice", "Polar bear"],
		["Animal", "needle", "Hedgehog"],
		["Animal", "Science", "Domestication"],
		["tent", "Animal", "Circus"],
		["ant", "Container", "Anthill"],
		["ant", "earth", "Anthill"],
		["farm", "ant", "Ant farm"],
		["ant", "glass", "Ant farm"],
		["ant", "Hill", "Anthill"],
		["ant", "house", "Anthill"],
		["ant", "Jar", "Ant farm"],
		["ant", "Land", "Anthill"],
		["Philosophy", "ant", "Small"],
		["ant", "Soil", "Anthill"],
		["antarctica", "atmosphere", "aurora"],
		["cart", "antarctica", "Sleigh"],
		["ocean", "antarctica", "iceberg"],
		["sea", "antarctica", "iceberg"],
		["sky", "antarctica", "aurora"],
		["sun", "antarctica", "aurora"],
		["wagon", "antarctica", "Sleigh"],
		["Anthill", "farm", "Ant farm"],
		["Anthill", "Jar", "Ant farm"],
		["aquarium", "Big", "Swimming pool"],
		["cart", "Arctic", "Sleigh"],
		["wagon", "Arctic", "Sleigh"],
		["bullet", "armor", "bulletproof vest"],
		["car", "armor", "tank"],
		["human", "armor", "knight"],
		["life", "armor", "robot"],
		["wild animal", "armor", "armadillo"],
		["oil", "ash", "soap"],
		["astronaut", "ice cream", "Astronaut Ice Cream"],
		["Container", "atmosphere", "Scuba tank"],
		["meteoroid", "atmosphere", "meteor"],
		["axe", "electricity", "chainsaw"],
		["axe", "human", "lumberjack"],
		["bread", "bacon", "sandwich"],
		["bacteria", "Death", "Organic matter"],
		["glass", "bacteria", "microscope"],
		["bacteria", "glasses", "microscope"],
		["human", "bacteria", "sickness"],
		["milk", "bacteria", "yogurt"],
		["Philosophy", "bacteria", "Small"],
		["fabric", "baker", "Apron"],
		["house", "baker", "bakery"],
		["paper", "baker", "recipe"],
		["bread", "banana", "banana bread"],
		["wheat", "bank", "Silo"],
		["bus", "barn", "Garage"],
		["car", "barn", "Garage"],
		["chicken", "barn", "Chicken coop"],
		["electric car", "barn", "Garage"],
		["farmer", "barn", "farm"],
		["helicopter", "barn", "Hangar"],
		["ice cream truck", "barn", "Garage"],
		["motorcycle", "barn", "Garage"],
		["rocket", "barn", "Hangar"],
		["rv", "barn", "Garage"],
		["seaplane", "barn", "Hangar"],
		["Sleigh", "barn", "Garage"],
		["snowmobile", "barn", "Garage"],
		["spaceship", "barn", "Hangar"],
		["tractor", "barn", "Garage"],
		["wheat", "barn", "Silo"],
		["Container", "bat", "Cave"],
		["house", "bat", "Cave"],
		["bat", "human", "batman"],
		["meat", "bbq", "steak"],
		["bird", "beach", "seagull"],
		["beach", "glasses", "sunglasses"],
		["life", "beach", "Animal"],
		["light", "beach", "lighthouse"],
		["beach", "sandwich", "picnic"],
		["tree", "beach", "palm"],
		["beach", "wind", "dune"],
		["beaver", "duck", "platypus"],
		["beaver", "river", "dam"],
		["beaver", "tree", "dam"],
		["beaver", "wood", "dam"],
		["bee", "beehive", "honey"],
		["bee", "beehive", "wax"],
		["farmer", "bee", "Beekeeper"],
		["bee", "flower", "honey"],
		["bee", "house", "beehive"],
		["human", "bee", "Beekeeper"],
		["bee", "Net", "Butterfly net"],
		["Philosophy", "bee", "Small"],
		["Pollen", "bee", "Seed"],
		["bee", "tree", "beehive"],
		["farmer", "beehive", "Beekeeper"],
		["human", "beehive", "Beekeeper"],
		["Container", "beer", "Bottle"],
		["beer", "human", "drunk"],
		["beer", "ice cream", "Guinness Float"],
		["bicycle", "energy", "motorcycle"],
		["bicycle", "human", "cyclist"],
		["bicycle", "steel", "motorcycle"],
		["Big", "Birdcage", "Aviary"],
		["Big", "Boulder", "Hill"],
		["fairy tale", "Big", "Legend"],
		["kite", "Big", "Paraglider"],
		["Land", "Big", "Continent"],
		["Pebble", "Big", "Rock"],
		["planet", "Big", "Jupiter"],
		["Rivulet", "Big", "Stream"],
		["Big", "Rock", "Boulder"],
		["safe", "Big", "Vault"],
		["saturn", "Big", "Jupiter"],
		["Shovel", "Big", "Excavator"],
		["Soil", "Big", "Land"],
		["Big", "stone", "Boulder"],
		["story", "Big", "Legend"],
		["tent", "Big", "Circus"],
		["wind", "Big", "Tornado"],
		["bird", "bird", "egg"],
		["bird", "Cage", "Birdcage"],
		["bird", "city", "pigeon"],
		["clock", "bird", "cuckoo"],
		["bird", "Container", "Birdcage"],
		["bird", "corpse", "vulture"],
		["bird", "dinosaur", "pterodactyl"],
		["bird", "earth", "ostrich"],
		["bird", "farmer", "chicken"],
		["bird", "field", "crow"],
		["fire", "bird", "phoenix"],
		["fish", "bird", "flying fish"],
		["bird", "flower", "hummingbird"],
		["bird", "hay", "nest"],
		["bird", "horse", "pegasus"],
		["bird", "house", "birdhouse"],
		["human", "bird", "angel"],
		["ice", "bird", "penguin"],
		["bird", "lake", "duck"],
		["bird", "letter", "pigeon"],
		["livestock", "bird", "chicken"],
		["bird", "metal", "airplane"],
		["mountain", "bird", "eagle"],
		["mouse", "bird", "bat"],
		["night", "bird", "owl"],
		["bird", "ocean", "seagull"],
		["bird", "paper", "origami"],
		["bird", "pirate", "parrot"],
		["bird", "pond", "duck"],
		["bird", "rainbow", "peacock"],
		["bird", "rainbow", "toucan"],
		["bird", "safe", "Birdcage"],
		["bird", "sand", "ostrich"],
		["bird", "scarecrow", "crow"],
		["bird", "sea", "seagull"],
		["bird", "snow", "penguin"],
		["squirrel", "bird", "flying squirrel"],
		["bird", "statue", "pigeon"],
		["bird", "steel", "airplane"],
		["bird", "tree", "nest"],
		["bird", "unicorn", "pegasus"],
		["bird", "wall", "Birdcage"],
		["water", "bird", "duck"],
		["bird", "wizard", "owl"],
		["bird", "wood", "woodpecker"],
		["blade", "blade", "scissors"],
		["blade", "Cook", "Knife"],
		["blade", "cookie dough", "Cookie cutter"],
		["cow", "blade", "leather"],
		["blade", "doctor", "scalpel"],
		["blade", "dough", "Cookie cutter"],
		["blade", "electricity", "blender"],
		["glass", "blade", "blender"],
		["blade", "grass", "scythe"],
		["gun", "blade", "bayonet"],
		["blade", "Heat", "Katana"],
		["blade", "hospital", "scalpel"],
		["human", "blade", "blood"],
		["blade", "livestock", "meat"],
		["blade", "metal", "sword"],
		["blade", "ninja", "Katana"],
		["paper", "blade", "confetti"],
		["blade", "pencil", "pencil sharpener"],
		["pig", "blade", "leather"],
		["blade", "pumpkin", "jack-o'-lantern"],
		["blade", "shuriken", "Katana"],
		["star", "blade", "shuriken"],
		["blade", "steel", "sword"],
		["tree", "blade", "Sap"],
		["blade", "wheat", "scythe"],
		["blade", "wood", "axe"],
		["fruit", "blender", "smoothie"],
		["blood", "Bottle", "Blood bag"],
		["blood", "Container", "Blood bag"],
		["blood", "fabric", "bandage"],
		["fish", "blood", "piranha"],
		["human", "blood", "vampire"],
		["blood", "ocean", "shark"],
		["blood", "Sack", "Blood bag"],
		["sea", "blood", "shark"],
		["boat", "fabric", "sailboat"],
		["human", "boat", "sailor"],
		["boat", "pirate", "pirate ship"],
		["boat", "sickness", "seasickness"],
		["steam engine", "boat", "steamboat"],
		["boat", "wind", "sailboat"],
		["boiler", "chain", "Machine"],
		["boiler", "tool", "Machine"],
		["boiler", "tool", "steam engine"],
		["boiler", "wheel", "Machine"],
		["boiler", "wheel", "steam engine"],
		["bone", "bone", "skeleton"],
		["chicken", "bone", "chicken wing"],
		["bone", "light", "x-ray"],
		["bone", "ocean", "Coral"],
		["bone", "sea", "Coral"],
		["wolf", "bone", "dog"],
		["book", "house", "library"],
		["human", "book", "Writer"],
		["book", "recipe", "cookbook"],
		["jam", "Bottle", "Jar"],
		["Bottle", "milk shake", "Cup"],
		["Bottle", "paint", "Bucket"],
		["Philosophy", "Bottle", "Container"],
		["Bottle", "river", "Bucket"],
		["Bottle", "smoothie", "Cup"],
		["Bottle", "tea", "Cup"],
		["Boulder", "Boulder", "Hill"],
		["earth", "Boulder", "Hill"],
		["hammer", "Boulder", "Ore"],
		["Organic matter", "Boulder", "Mineral"],
		["Boulder", "Small", "Rock"],
		["stone", "Boulder", "Hill"],
		["Bow", "electricity", "Stun gun"],
		["Bow", "energy", "Stun gun"],
		["wood", "Bow", "Arrow"],
		["chain", "Box", "Toolbox"],
		["chicken wing", "Box", "Bucket"],
		["hammer", "Box", "Toolbox"],
		["letter", "Box", "Mailbox"],
		["mailman", "Box", "Mailbox"],
		["Philosophy", "Box", "Container"],
		["ruler", "Box", "Toolbox"],
		["steel wool", "Box", "Toolbox"],
		["tool", "Box", "Toolbox"],
		["cheese", "bread", "sandwich"],
		["bread", "fire", "toast"],
		["bread", "ham", "sandwich"],
		["house", "bread", "bakery"],
		["human", "bread", "baker"],
		["meat", "bread", "hamburger"],
		["time", "bread", "mold"],
		["brick", "brick", "wall"],
		["campfire", "brick", "fireplace"],
		["fireplace", "brick", "chimney"],
		["human", "brick", "house"],
		["smoke", "brick", "chimney"],
		["tool", "brick", "house"],
		["computer", "broom", "Robot vacuum"],
		["Container", "broom", "Closet"],
		["electricity", "broom", "vacuum cleaner"],
		["human", "broom", "witch"],
		["robot", "broom", "Robot vacuum"],
		["wizard", "broom", "witch"],
		["jam", "Bucket", "Jar"],
		["Philosophy", "Bucket", "Container"],
		["metal", "bullet", "gun"],
		["wood", "bullet", "Arrow"],
		["bus", "Container", "Garage"],
		["bus", "house", "Garage"],
		["bus", "wall", "Garage"],
		["cow", "butcher", "meat"],
		["livestock", "butcher", "meat"],
		["pig", "butcher", "meat"],
		["Nuts", "butter", "Peanut butter"],
		["butterfly", "moon", "moth"],
		["butterfly", "Net", "Butterfly net"],
		["butterfly", "night", "moth"],
		["sand", "cactus", "desert"],
		["Container", "cake", "Box"],
		["campfire", "fabric", "smoke signal"],
		["campfire", "garden", "bbq"],
		["house", "campfire", "fireplace"],
		["human", "campfire", "Cook"],
		["human", "campfire", "story"],
		["campfire", "meat", "bbq"],
		["sugar", "campfire", "marshmallows"],
		["campfire", "wall", "fireplace"],
		["campfire", "witch", "cauldron"],
		["dough", "candle", "cake"],
		["pumpkin", "candle", "jack-o'-lantern"],
		["human", "Canvas", "Painter"],
		["Canvas", "paint", "Painting"],
		["Canvas", "Painter", "Painting"],
		["car", "car", "bus"],
		["car", "Container", "Garage"],
		["doctor", "car", "ambulance"],
		["car", "electricity", "electric car"],
		["farmer", "car", "tractor"],
		["field", "car", "tractor"],
		["fireman", "car", "firetruck"],
		["car", "gun", "tank"],
		["hospital", "car", "ambulance"],
		["car", "house", "Garage"],
		["house", "car", "rv"],
		["car", "ice cream", "ice cream truck"],
		["car", "letter", "Mail truck"],
		["car", "mailman", "Mail truck"],
		["moon", "car", "Moon rover"],
		["mountain range", "car", "Cable car"],
		["mountain", "car", "Cable car"],
		["car", "Post office", "Mail truck"],
		["Shovel", "car", "Excavator"],
		["snow", "car", "snowmobile"],
		["car", "wall", "Garage"],
		["caramel", "chocolate", "Caramelo"],
		["caramel", "orchard", "Caramel Apple"],
		["Caramelo", "cookie", "Twix"],
		["carbon dioxide", "cold", "dry ice"],
		["fire", "carbon dioxide", "fire extinguisher"],
		["ice", "carbon dioxide", "dry ice"],
		["juice", "carbon dioxide", "soda"],
		["metal", "carbon dioxide", "fire extinguisher"],
		["Philosophy", "carbon dioxide", "Small"],
		["plant", "carbon dioxide", "oxygen"],
		["pressure", "carbon dioxide", "fire extinguisher"],
		["water", "carbon dioxide", "soda"],
		["snow", "carrot", "snowman"],
		["snowball", "carrot", "snowman"],
		["carrot", "wild animal", "rabbit"],
		["cart", "horse", "wagon"],
		["cart", "ice", "Sleigh"],
		["cart", "mountain", "roller coaster"],
		["snow", "cart", "sledge"],
		["cart", "snow", "Sleigh"],
		["gunpowder", "castle", "cannon"],
		["human", "castle", "monarch"],
		["castle", "night", "ghost"],
		["sand", "castle", "sand castle"],
		["story", "castle", "fairy tale"],
		["time", "castle", "ruins"],
		["cat", "music", "Keyboard Cat"],
		["cat", "plant", "catnip"],
		["wild animal", "cat", "lion"],
		["caviar", "seaweed", "sushi"],
		["Container", "cereal", "Box"],
		["chain", "Container", "Toolbox"],
		["tool", "chain", "Machine"],
		["human", "chainsaw", "lumberjack"],
		["wood", "charcoal", "pencil"],
		["cheese", "dough", "pizza"],
		["cheese", "fish", "Goldfish"],
		["cheese", "hamburger", "cheeseburger"],
		["metal", "cheese", "mousetrap"],
		["cheese", "pasta", "mac and cheese"],
		["sky", "cheese", "moon"],
		["cheese", "toast", "grilled cheese"],
		["cheese", "wild animal", "mouse"],
		["wood", "cheese", "mousetrap"],
		["chicken wing", "Container", "Bucket"],
		["chicken", "Container", "Chicken coop"],
		["egg", "chicken", "Philosophy"],
		["chicken", "house", "Chicken coop"],
		["chicken", "sugar", "Peeps"],
		["chicken", "wall", "Chicken coop"],
		["water", "chicken", "chicken soup"],
		["chicken", "wild animal", "fox"],
		["house", "chimney", "Factory"],
		["santa", "chimney", "gift"],
		["Container", "chocolate milk", "Bottle"],
		["chocolate milk", "Heat", "Hot chocolate"],
		["chocolate", "coconut", "Mounds"],
		["chocolate", "egg", "Cadbury Eggs"],
		["chocolate", "Heat", "Hot chocolate"],
		["chocolate", "milk", "chocolate milk"],
		["santa", "christmas stocking", "gift"],
		["christmas tree", "glass", "snow globe"],
		["human", "christmas tree", "santa"],
		["santa", "christmas tree", "gift"],
		["sugar", "christmas tree", "candy cane"],
		["dinosaur", "city", "godzilla"],
		["dinosaur", "city", "Kaiju"],
		["city", "field", "Park"],
		["Firefighter", "city", "Firestation"],
		["fog", "city", "smog"],
		["city", "forest", "Park"],
		["city", "garden", "Park"],
		["city", "grass", "Park"],
		["clay", "fire", "brick"],
		["fire", "clay", "pottery"],
		["human", "clay", "Potter"],
		["clay", "life", "golem"],
		["clay", "oil", "oil lamp"],
		["clay", "sun", "brick"],
		["clay", "tool", "pottery"],
		["clay", "wheel", "pottery"],
		["egg", "clock", "egg timer"],
		["human", "clock", "watch"],
		["clock", "sound", "alarm clock"],
		["clock", "sun", "sundial"],
		["earth", "cloud", "fog"],
		["electricity", "cloud", "Lightning"],
		["cloud", "electricity", "storm"],
		["energy", "cloud", "Lightning"],
		["energy", "cloud", "storm"],
		["ice", "cloud", "hail"],
		["cloud", "livestock", "sheep"],
		["planet", "cloud", "Jupiter"],
		["plant", "cloud", "cotton"],
		["cloud", "sugar", "cotton candy"],
		["cloud", "water", "rain"],
		["metal", "coal", "steel"],
		["pressure", "coal", "diamond"],
		["coal", "time", "diamond"],
		["wood", "coal", "pencil"],
		["Container", "coconut milk", "Bottle"],
		["milk", "coconut", "coconut milk"],
		["coconut", "tool", "coconut milk"],
		["coffin", "earth", "grave"],
		["electricity", "cold", "fridge"],
		["human", "cold", "Chill"],
		["juice", "cold", "popsicle"],
		["metal", "cold", "fridge"],
		["milk", "cold", "ice cream"],
		["cold", "ocean", "Arctic"],
		["ocean", "cold", "Current"],
		["rain", "cold", "snow"],
		["cold", "sea", "Arctic"],
		["sea", "cold", "Current"],
		["steam", "cold", "snow"],
		["cold", "tea", "iced tea"],
		["water", "cold", "ice"],
		["cold", "yogurt", "frozen yogurt"],
		["human", "computer mouse", "Hacker"],
		["computer", "computer", "internet"],
		["computer", "dog", "Doge"],
		["human", "computer", "Hacker"],
		["letter", "computer", "email"],
		["mouse", "computer", "computer mouse"],
		["paper", "computer", "printer"],
		["computer", "Small", "Laptop"],
		["computer", "squirrel", "Pokki"],
		["computer", "vacuum cleaner", "Robot vacuum"],
		["computer", "web", "internet"],
		["computer", "wire", "internet"],
		["Philosophy", "confetti", "Small"],
		["confetti", "sugar", "sprinkles"],
		["Container", "cookie", "Box"],
		["Container", "crayon", "Box"],
		["Container", "donut", "Box"],
		["electric car", "Container", "Garage"],
		["Container", "electricity", "Battery"],
		["Container", "energy", "Battery"],
		["Container", "flour", "Sack"],
		["Container", "fox", "Cave"],
		["Galaxy cluster", "Container", "Universe"],
		["galaxy", "Container", "Galaxy cluster"],
		["grass", "Container", "Lawn"],
		["hammer", "Container", "Toolbox"],
		["hamster", "Container", "Cage"],
		["helicopter", "Container", "Hangar"],
		["ice cream truck", "Container", "Garage"],
		["jam", "Container", "Jar"],
		["Container", "juice", "Bottle"],
		["Container", "letter", "Sack"],
		["Container", "lion", "Cave"],
		["Container", "Liquid", "Bottle"],
		["mailman", "Container", "Post office"],
		["Container", "milk shake", "Cup"],
		["Container", "milk", "Bottle"],
		["motorcycle", "Container", "Garage"],
		["Container", "oil", "Bottle"],
		["Container", "oxygen", "Scuba tank"],
		["Container", "paint", "Bucket"],
		["Container", "pencil", "Box"],
		["Container", "perfume", "Bottle"],
		["Container", "pizza", "Box"],
		["Container", "Robot vacuum", "Closet"],
		["rocket", "Container", "Hangar"],
		["ruler", "Container", "Toolbox"],
		["rv", "Container", "Garage"],
		["Container", "salt", "Sack"],
		["seaplane", "Container", "Hangar"],
		["Sleigh", "Container", "Garage"],
		["Container", "smoothie", "Cup"],
		["snowmobile", "Container", "Garage"],
		["Container", "soda", "Bottle"],
		["space", "Container", "Universe"],
		["spaceship", "Container", "Hangar"],
		["steel wool", "Container", "Toolbox"],
		["Container", "tea", "Cup"],
		["tool", "Container", "Toolbox"],
		["Container", "Toolbox", "Closet"],
		["tractor", "Container", "Garage"],
		["train", "Container", "Trainyard"],
		["Container", "umbrella", "Closet"],
		["Container", "vacuum cleaner", "Closet"],
		["Container", "water", "Bottle"],
		["wheat", "Container", "Silo"],
		["wine", "Container", "Barrel"],
		["Container", "wine", "Bottle"],
		["Container", "wolf", "Cave"],
		["Container", "wood", "Bucket"],
		["Container", "yogurt", "Bucket"],
		["Continent", "Small", "Land"],
		["fabric", "Cook", "Apron"],
		["house", "Cook", "Restaurant"],
		["sword", "Cook", "Knife"],
		["wood", "Cook", "Cutting board"],
		["cookie", "dough", "cookie dough"],
		["paper", "cookie", "fortune cookie"],
		["santa", "cookie", "gift"],
		["corpse", "earth", "grave"],
		["electricity", "corpse", "frankenstein"],
		["corpse", "electricity", "Frankenstein's monster"],
		["corpse", "Legend", "Frankenstein's monster"],
		["corpse", "life", "zombie"],
		["corpse", "Lightning", "Frankenstein's monster"],
		["corpse", "Philosophy", "Death"],
		["corpse", "pyramid", "mummy"],
		["corpse", "Science", "Organic matter"],
		["corpse", "scythe", "grim reaper"],
		["corpse", "story", "Frankenstein's monster"],
		["corpse", "time", "bone"],
		["corpse", "time", "skeleton"],
		["wood", "corpse", "coffin"],
		["cotton", "fabric", "pillow"],
		["cotton", "tool", "thread"],
		["farmer", "cow", "milk"],
		["fire", "cow", "steak"],
		["cow", "house", "barn"],
		["cow", "human", "milk"],
		["human", "cow", "minotaur"],
		["cow", "mountain", "yak"],
		["cow", "rope", "lasso"],
		["cow", "sea", "manatee"],
		["cow", "tool", "meat"],
		["crown", "human", "monarch"],
		["snow", "crystal ball", "snow globe"],
		["Cup", "paper", "Paper cup"],
		["Cup", "thread", "String phone"],
		["Cup", "wire", "String phone"],
		["river", "dam", "lake"],
		["wild animal", "dam", "beaver"],
		["day", "night", "Dawn"],
		["day", "night", "twilight"],
		["time", "day", "night"],
		["day", "vampire", "dust"],
		["life", "Death", "Organic matter"],
		["desert", "grave", "pyramid"],
		["desert", "horse", "camel"],
		["ice", "desert", "antarctica"],
		["life", "desert", "Animal"],
		["livestock", "desert", "camel"],
		["desert", "palm", "oasis"],
		["desert", "plant", "cactus"],
		["snow", "desert", "antarctica"],
		["desert", "stone", "pyramid"],
		["tree", "desert", "oasis"],
		["desert", "water", "oasis"],
		["desert", "wild animal", "camel"],
		["desert", "wind", "dune"],
		["diamond", "gold", "ring"],
		["diamond", "metal", "ring"],
		["diamond", "sugar", "Ring Pop"],
		["dinosaur", "earth", "fossil"],
		["human", "dinosaur", "Paleontologist"],
		["dinosaur", "Legend", "Kaiju"],
		["meat", "dinosaur", "tyrannosaurus rex"],
		["Science", "dinosaur", "Paleontologist"],
		["dinosaur", "skyscraper", "Kaiju"],
		["stone", "dinosaur", "fossil"],
		["dinosaur", "story", "Kaiju"],
		["dinosaur", "time", "fossil"],
		["house", "doctor", "hospital"],
		["doctor", "mold", "penicillin"],
		["doctor", "needle", "Syringe"],
		["doctor", "Tardis", "The Doctor"],
		["tool", "doctor", "stethoscope"],
		["dog", "forest", "wolf"],
		["dog", "house", "doghouse"],
		["dog", "ice", "husky"],
		["dog", "internet", "Doge"],
		["dog", "sea", "seal"],
		["dog", "snow", "husky"],
		["wild animal", "dog", "wolf"],
		["tree", "Domestication", "Nuts"],
		["double rainbow!", "horse", "unicorn"],
		["life", "double rainbow!", "Magic"],
		["double rainbow!", "life", "unicorn"],
		["dough", "fire", "bread"],
		["dough", "fruit", "pie"],
		["house", "dough", "gingerbread house"],
		["human", "dough", "baker"],
		["life", "dough", "gingerbread man"],
		["dough", "oil", "donut"],
		["dough", "sugar", "cookie"],
		["knight", "dragon", "hero"],
		["dragon", "story", "fairy tale"],
		["human", "drum", "Musician"],
		["egg", "duck", "duckling"],
		["time", "duckling", "duck"],
		["wild animal", "dune", "scorpion"],
		["fire", "dust", "gunpowder"],
		["flower", "dust", "Pollen"],
		["human", "dust", "allergy"],
		["plant", "dust", "Pollen"],
		["earth", "earth", "Land"],
		["earth", "earth", "pressure"],
		["earthquake", "earth", "mountain"],
		["earth", "energy", "earthquake"],
		["earth", "farmer", "field"],
		["earth", "fire", "lava"],
		["hammer", "earth", "Ore"],
		["earth", "idea", "Solid"],
		["Land", "earth", "Continent"],
		["lava", "earth", "volcano"],
		["earth", "life", "human"],
		["earth", "life", "Soil"],
		["earth", "metal", "Plow"],
		["earth", "ocean", "Primordial soup"],
		["Organic matter", "earth", "Mineral"],
		["earth", "Organic matter", "Soil"],
		["paper", "earth", "map"],
		["plant", "earth", "grass"],
		["rain", "earth", "plant"],
		["Rock", "earth", "Boulder"],
		["earth", "Science", "Solid"],
		["earth", "sea", "Primordial soup"],
		["sky", "earth", "horizon"],
		["Small", "earth", "Pebble"],
		["earth", "space", "planet"],
		["steam", "earth", "geyser"],
		["earth", "steel", "Plow"],
		["earth", "stone", "Land"],
		["earth", "tool", "field"],
		["earth", "vegetable", "Potato"],
		["water", "earth", "mud"],
		["earth", "wave", "earthquake"],
		["earth", "wood", "Plow"],
		["ocean", "earthquake", "tsunami"],
		["sea", "earthquake", "tsunami"],
		["egg", "fire", "omelette"],
		["egg", "fish", "Roe"],
		["flour", "egg", "pasta"],
		["egg", "flying fish", "Roe"],
		["egg", "hay", "nest"],
		["egg", "lake", "Roe"],
		["egg", "livestock", "chicken"],
		["egg", "ocean", "hard roe"],
		["egg", "ocean", "Roe"],
		["egg", "oil", "mayonnaise"],
		["egg", "pond", "hard roe"],
		["egg", "sand", "turtle"],
		["egg", "sea", "hard roe"],
		["egg", "sea", "Roe"],
		["egg", "sky", "bird"],
		["egg", "swamp", "lizard"],
		["egg", "watch", "egg timer"],
		["egg", "water", "hard roe"],
		["egg", "water", "Roe"],
		["electric car", "house", "Garage"],
		["moon", "electric car", "Moon rover"],
		["electric car", "wall", "Garage"],
		["fish", "electricity", "electric eel"],
		["electricity", "flashlight", "light"],
		["electricity", "glass", "light bulb"],
		["gun", "electricity", "Stun gun"],
		["gun", "electricity", "taser"],
		["human", "electricity", "electrician"],
		["light bulb", "electricity", "light"],
		["electricity", "metal", "wire"],
		["electricity", "Mineral", "Battery"],
		["electricity", "needle", "sewing machine"],
		["electricity", "nerd", "computer"],
		["electricity", "Ore", "Battery"],
		["electricity", "oxygen", "ozone"],
		["electricity", "rain", "Lightning"],
		["sand", "electricity", "glass"],
		["electricity", "scythe", "lawn mower"],
		["electricity", "storm", "Lightning"],
		["electricity", "sugar", "cotton candy"],
		["sword", "electricity", "Light sword"],
		["electricity", "sword", "lightsaber"],
		["time", "electricity", "clock"],
		["windmill", "electricity", "wind turbine"],
		["zombie", "electricity", "frankenstein"],
		["zombie", "electricity", "Frankenstein's monster"],
		["energy", "explosion", "atomic bomb"],
		["fruit", "energy", "sugar"],
		["gun", "energy", "Stun gun"],
		["human", "energy", "wizard"],
		["juice", "energy", "sugar"],
		["energy", "Liquid", "Gas"],
		["metal", "energy", "electricity"],
		["energy", "milk", "butter"],
		["energy", "rain", "Lightning"],
		["sand", "energy", "sandstorm"],
		["energy", "snow", "avalanche"],
		["energy", "Solid", "Liquid"],
		["energy", "storm", "Lightning"],
		["swamp", "energy", "life"],
		["sword", "energy", "Light sword"],
		["energy", "sword", "lightsaber"],
		["volcano", "energy", "ash"],
		["volcano", "energy", "eruption"],
		["water", "energy", "steam"],
		["wind", "energy", "hurricane"],
		["energy", "witch", "Magic"],
		["energy", "wizard", "Magic"],
		["glass", "engineer", "Lens"],
		["engineer", "glasses", "safety glasses"],
		["engineer", "mountain", "tunnel"],
		["engineer", "paper", "blueprint"],
		["Quicksilver", "engineer", "Thermometer"],
		["engineer", "sugar", "Willy Wonka"],
		["tool", "engineer", "Machine"],
		["excalibur", "human", "monarch"],
		["explosion", "galaxy", "Supernova"],
		["explosion", "glasses", "safety glasses"],
		["explosion", "Machine", "Combustion engine"],
		["explosion", "metal", "grenade"],
		["explosion", "sky", "fireworks"],
		["explosion", "space", "Supernova"],
		["explosion", "star", "super nova"],
		["explosion", "star", "Supernova"],
		["explosion", "steam engine", "Combustion engine"],
		["explosion", "stone", "Pop Rocks"],
		["explosion", "sun", "Supernova"],
		["fabric", "hero", "cape"],
		["fabric", "house", "tent"],
		["fabric", "mountain goat", "cashmere"],
		["fabric", "paint", "Canvas"],
		["fabric", "pilot", "parachute"],
		["rain", "fabric", "umbrella"],
		["fabric", "smoke", "smoke signal"],
		["fabric", "wood", "tent"],
		["story", "fairy tale", "Legend"],
		["fairy tale", "time", "Legend"],
		["tree", "family", "family tree"],
		["wheat", "farm", "Silo"],
		["field", "farmer", "wheat"],
		["farmer", "grass", "hay"],
		["farmer", "house", "farm"],
		["farmer", "life", "livestock"],
		["plant", "farmer", "wheat"],
		["farmer", "Science", "Domestication"],
		["tree", "farmer", "fruit"],
		["tree", "farmer", "Nuts"],
		["farmer", "wild animal", "livestock"],
		["leaf", "fence", "hedge"],
		["plant", "fence", "hedge"],
		["field", "fruit tree", "orchard"],
		["field", "fruit", "vegetable"],
		["field", "human", "farmer"],
		["field", "lawn mower", "Lawn"],
		["field", "metal", "Plow"],
		["field", "steel", "Plow"],
		["field", "tool", "Plow"],
		["tree", "field", "Nuts"],
		["village", "field", "Park"],
		["field", "wood", "Plow"],
		["human", "fire extinguisher", "Firefighter"],
		["fire", "gun", "flamethrower"],
		["gunpowder", "fire", "explosion"],
		["human", "fire", "Firefighter"],
		["human", "fire", "fireman"],
		["fire", "ice", "water"],
		["fire", "idea", "Heat"],
		["jedi", "fire", "darth vader"],
		["juice", "fire", "sugar"],
		["lizard", "fire", "dragon"],
		["fire", "mountain", "volcano"],
		["mud", "fire", "brick"],
		["fire", "ocean", "salt"],
		["fire", "oil", "oil lamp"],
		["pig", "fire", "bacon"],
		["plant", "fire", "tobacco"],
		["pumpkin", "fire", "jack-o'-lantern"],
		["fire", "sand", "glass"],
		["sandwich", "fire", "toast"],
		["fire", "Science", "Heat"],
		["fire", "sea", "salt"],
		["fire", "sky", "sun"],
		["fire", "stone", "metal"],
		["sugar", "fire", "caramel"],
		["tree", "fire", "charcoal"],
		["vegetable", "fire", "pumpkin"],
		["fire", "wall", "Firewall"],
		["water", "fire", "steam"],
		["wax", "fire", "candle"],
		["fire", "wood", "campfire"],
		["wood", "fire", "charcoal"],
		["fire", "wood", "smoke"],
		["house", "Firefighter", "Firestation"],
		["Firefighter", "Land", "Firestation"],
		["Firefighter", "village", "Firestation"],
		["house", "fireplace", "chimney"],
		["santa", "fireplace", "gift"],
		["fireplace", "witch", "cauldron"],
		["wool", "fireplace", "christmas stocking"],
		["house", "firetruck", "Firestation"],
		["human", "firetruck", "Firefighter"],
		["human", "firetruck", "fireman"],
		["fish", "fish", "hard roe"],
		["fish", "french fries", "fish and chips"],
		["glass", "fish", "aquarium"],
		["fish", "horse", "seahorse"],
		["human", "fish", "mermaid"],
		["fish", "rope", "Net"],
		["fish", "seaweed", "sushi"],
		["sky", "fish", "flying fish"],
		["fish", "star", "starfish"],
		["fish", "sugar", "Swedish Fish"],
		["fish", "sword", "swordfish"],
		["tool", "fish", "fishing rod"],
		["wood", "fish", "fishing rod"],
		["human", "fishing rod", "angler"],
		["fishing rod", "rope", "Net"],
		["snowman", "flamethrower", "puddle"],
		["human", "flour", "baker"],
		["flour", "milk", "batter"],
		["flour", "paper", "recipe"],
		["water", "flour", "dough"],
		["flower", "flower", "garden"],
		["flower", "love", "rose"],
		["flower", "pond", "water lily"],
		["pottery", "flower", "vase"],
		["flower", "steam", "perfume"],
		["flower", "sun", "sunflower"],
		["time", "flower", "Seed"],
		["flower", "water", "perfume"],
		["flower", "wild animal", "bee"],
		["flower", "wild animal", "butterfly"],
		["flower", "wind", "Pollen"],
		["flute", "flute", "Pan flute"],
		["human", "flute", "music"],
		["human", "flute", "Musician"],
		["flying fish", "rope", "Net"],
		["fog", "grass", "dew"],
		["smoke", "fog", "smog"],
		["sword", "Force knight", "Light sword"],
		["life", "forest", "Animal"],
		["forest", "life", "wild animal"],
		["pig", "forest", "wild boar"],
		["rain", "forest", "Rainforest"],
		["village", "forest", "Park"],
		["human", "fossil", "Paleontologist"],
		["fossil", "ocean", "Coral"],
		["fossil", "pressure", "petroleum"],
		["Science", "fossil", "Paleontologist"],
		["fossil", "sea", "Coral"],
		["fossil", "time", "petroleum"],
		["house", "fox", "Cave"],
		["fox", "metal", "Cage"],
		["fox", "steel", "Cage"],
		["fox", "wall", "Cage"],
		["fruit tree", "fruit tree", "orchard"],
		["human", "fruit", "Cook"],
		["fruit", "juice", "Juicy Fruit"],
		["fruit", "monkey", "banana"],
		["palm", "fruit", "coconut"],
		["pressure", "fruit", "juice"],
		["fruit", "rocket", "Starburst"],
		["fruit", "time", "alcohol"],
		["fruit", "tree", "fruit tree"],
		["water", "fruit", "juice"],
		["fruit", "water", "lemonade"],
		["Galaxy cluster", "Galaxy cluster", "Universe"],
		["Galaxy cluster", "Philosophy", "Big"],
		["galaxy", "galaxy", "Galaxy cluster"],
		["galaxy", "Philosophy", "Big"],
		["train", "Garage", "Trainyard"],
		["human", "garden", "gardener"],
		["plant", "garden", "flower"],
		["garden", "statue", "gnome"],
		["village", "garden", "Park"],
		["water", "garden", "pond"],
		["tool", "gardener", "Shovel"],
		["planet", "Gas", "Jupiter"],
		["gift", "paper", "wrapping paper"],
		["house", "gingerbread man", "gingerbread house"],
		["glass", "glass", "glasses"],
		["glass", "house", "window"],
		["jam", "glass", "Jar"],
		["glass", "metal", "glasses"],
		["glass", "metal", "mirror"],
		["glass", "oil", "oil lamp"],
		["plant", "glass", "greenhouse"],
		["Quicksilver", "glass", "Thermometer"],
		["glass", "rainbow", "prism"],
		["sand", "glass", "hourglass"],
		["sand", "glass", "time"],
		["glass", "sky", "telescope"],
		["glass", "snow", "snow globe"],
		["glass", "snowman", "snow globe"],
		["glass", "space", "telescope"],
		["glass", "star", "telescope"],
		["glass", "tool", "Lens"],
		["water", "glass", "aquarium"],
		["witch", "glass", "crystal ball"],
		["wizard", "glass", "crystal ball"],
		["glasses", "glasses", "Binoculars"],
		["human", "glasses", "Hacker"],
		["human", "glasses", "nerd"],
		["glasses", "snow", "ski goggles"],
		["sun", "glasses", "sunglasses"],
		["tool", "glasses", "safety glasses"],
		["glasses", "water", "swim goggles"],
		["goat", "human", "faun"],
		["goat", "mountain range", "mountain goat"],
		["mountain", "goat", "mountain goat"],
		["house", "gold", "bank"],
		["human", "gold", "Alchemist"],
		["gold", "metal", "safe"],
		["gold", "monarch", "crown"],
		["paper", "gold", "money"],
		["gold", "Philosophy", "Alchemist"],
		["gold", "steel", "safe"],
		["house", "grass", "garden"],
		["grass", "house", "Lawn"],
		["grass", "lawn mower", "Lawn"],
		["grass", "livestock", "cow"],
		["mud", "grass", "swamp"],
		["plant", "grass", "garden"],
		["grass", "pond", "Reed"],
		["grass", "puddle", "Reed"],
		["grass", "river", "Reed"],
		["grass", "sandwich", "picnic"],
		["grass", "scythe", "hay"],
		["grass", "sun", "hay"],
		["grass", "swamp", "Reed"],
		["time", "grass", "Peat"],
		["grass", "tool", "lawn mower"],
		["village", "grass", "Park"],
		["water", "grass", "dew"],
		["grass", "wild animal", "ant"],
		["grave", "grave", "graveyard"],
		["grave", "Philosophy", "Death"],
		["grave", "stone", "gravestone"],
		["gravestone", "gravestone", "graveyard"],
		["graveyard", "night", "ghost"],
		["graveyard", "Philosophy", "Death"],
		["human", "grim reaper", "corpse"],
		["human", "gun", "corpse"],
		["gun", "sword", "bayonet"],
		["water", "gun", "water gun"],
		["gun", "wire", "Stun gun"],
		["gunpowder", "metal", "bullet"],
		["gunpowder", "pirate ship", "cannon"],
		["gunpowder", "wire", "dynamite"],
		["hammer", "Hill", "Ore"],
		["metal", "hammer", "Bell"],
		["hammer", "mountain", "Ore"],
		["hammer", "Rock", "Ore"],
		["steel", "hammer", "Bell"],
		["hammer", "stone", "Ore"],
		["hamster", "house", "Cage"],
		["hamster", "wall", "Cage"],
		["hard roe", "human", "caviar"],
		["hard roe", "time", "fish"],
		["hay", "hay", "hay bale"],
		["house", "hay", "barn"],
		["human", "hay", "scarecrow"],
		["hay", "livestock", "horse"],
		["metal", "hay", "needle"],
		["tool", "hay", "pitchfork"],
		["wood", "hay", "broom"],
		["Heat", "Heat", "Plasma"],
		["Heat", "human", "Warmth"],
		["ocean", "Heat", "Current"],
		["planet", "Heat", "Mercury"],
		["Heat", "pressure", "Plasma"],
		["Sap", "Heat", "Maple syrup"],
		["sea", "Heat", "Current"],
		["helicopter", "house", "Hangar"],
		["helicopter", "wall", "Hangar"],
		["Organic matter", "Hill", "Mineral"],
		["Small", "Hill", "Boulder"],
		["horse", "human", "centaur"],
		["horse", "leather", "saddle"],
		["metal", "horse", "horseshoe"],
		["ocean", "horse", "seahorse"],
		["rainbow", "horse", "unicorn"],
		["horse", "river", "hippo"],
		["horse", "rope", "lasso"],
		["horse", "sea", "seahorse"],
		["sky", "horse", "pegasus"],
		["horse", "water", "hippo"],
		["horse", "wood", "trojan horse"],
		["human", "hospital", "doctor"],
		["house", "house", "village"],
		["human", "house", "family"],
		["ice cream truck", "house", "Garage"],
		["house", "ice", "igloo"],
		["house", "knight", "castle"],
		["house", "lake", "Swimming pool"],
		["letter", "house", "Post office"],
		["light", "house", "lighthouse"],
		["house", "lion", "Cave"],
		["livestock", "house", "barn"],
		["mailman", "house", "Post office"],
		["house", "money", "bank"],
		["motorcycle", "house", "Garage"],
		["Philosophy", "house", "Container"],
		["rocket", "house", "Hangar"],
		["rv", "house", "Garage"],
		["house", "safe", "bank"],
		["seaplane", "house", "Hangar"],
		["house", "sickness", "hospital"],
		["house", "sky", "skyscraper"],
		["Sleigh", "house", "Garage"],
		["house", "snow", "igloo"],
		["snowmobile", "house", "Garage"],
		["space", "house", "space station"],
		["spaceship", "house", "Hangar"],
		["house", "swimmer", "Swimming pool"],
		["time", "house", "ruins"],
		["house", "tool", "Factory"],
		["tractor", "house", "Garage"],
		["train", "house", "Trainyard"],
		["tree", "house", "treehouse"],
		["wheat", "house", "Silo"],
		["house", "wind", "windmill"],
		["house", "wolf", "Cave"],
		["wood", "house", "log cabin"],
		["human", "human", "love"],
		["human", "ice", "Chill"],
		["human", "idea", "Philosophy"],
		["human", "internet", "Hacker"],
		["human", "Katana", "Samurai"],
		["human", "letter", "mailman"],
		["human", "library", "Librarian"],
		["human", "light bulb", "idea"],
		["human", "Light sword", "Force knight"],
		["lightsaber", "human", "jedi"],
		["human", "lion", "sphinx"],
		["human", "meat", "butcher"],
		["human", "medusa", "statue"],
		["metal", "human", "tool"],
		["human", "microscope", "Science"],
		["human", "moon", "astronaut"],
		["human", "mountain range", "Skier"],
		["human", "mountain", "Skier"],
		["human", "music", "Musician"],
		["human", "needle", "Tailor"],
		["human", "Nuts", "Cook"],
		["human", "oxygen", "carbon dioxide"],
		["human", "paint", "Painter"],
		["human", "Painting", "Painter"],
		["human", "Pan flute", "Musician"],
		["human", "pencil", "Writer"],
		["human", "pitchfork", "farmer"],
		["human", "plant", "farmer"],
		["human", "pottery", "Potter"],
		["human", "rain", "cold"],
		["human", "rain", "sickness"],
		["human", "robot", "cyborg"],
		["rocket", "human", "astronaut"],
		["ruins", "human", "Archeologist"],
		["human", "sailboat", "sailor"],
		["Scuba tank", "human", "Diver"],
		["human", "scythe", "grim reaper"],
		["seaplane", "human", "pilot"],
		["human", "sewing machine", "Tailor"],
		["human", "sheet music", "Musician"],
		["shuriken", "human", "ninja"],
		["human", "ski goggles", "Skier"],
		["human", "snake", "medusa"],
		["snow", "human", "snowball"],
		["snow", "human", "snowman"],
		["human", "snowboard", "Snowboarder"],
		["human", "sound", "music"],
		["human", "space station", "astronaut"],
		["human", "space", "astronaut"],
		["human", "story", "Philosophy"],
		["human", "swim goggles", "swimmer"],
		["sword", "human", "warrior"],
		["human", "telescope", "Astronomer"],
		["human", "telescope", "Science"],
		["human", "thread", "Tailor"],
		["human", "tool", "engineer"],
		["human", "Universe", "Science"],
		["human", "vampire", "vampire"],
		["human", "vegetable", "Cook"],
		["human", "wave", "surfer"],
		["werewolf", "human", "werewolf"],
		["wild animal", "human", "dog"],
		["wild animal", "human", "livestock"],
		["human", "wine", "drunk"],
		["human", "wire", "electrician"],
		["wolf", "human", "werewolf"],
		["wood", "human", "house"],
		["human", "wool", "sweater"],
		["human", "zombie", "zombie"],
		["sand", "hurricane", "sandstorm"],
		["ice cream truck", "wall", "Garage"],
		["milk", "ice cream", "milk shake"],
		["juice", "ice", "popsicle"],
		["metal", "ice", "fridge"],
		["milk", "ice", "ice cream"],
		["ice", "mountain", "glacier"],
		["ocean", "ice", "iceberg"],
		["rain", "ice", "hail"],
		["sea", "ice", "iceberg"],
		["ice", "statue", "Ice sculpture"],
		["ice", "storm", "hail"],
		["sun", "ice", "puddle"],
		["ice", "tea", "iced tea"],
		["wagon", "ice", "Sleigh"],
		["ice", "wild animal", "penguin"],
		["ice", "yogurt", "frozen yogurt"],
		["steamboat", "iceberg", "titanic"],
		["water", "idea", "Liquid"],
		["wind", "idea", "Motion"],
		["letter", "internet", "email"],
		["isle", "isle", "archipelago"],
		["isle", "tree", "palm"],
		["jedi", "lava", "darth vader"],
		["jedi", "swamp", "yoda"],
		["juice", "sugar", "jam"],
		["juice", "time", "alcohol"],
		["knight", "Light sword", "Force knight"],
		["knight", "lightsaber", "jedi"],
		["knight", "story", "fairy tale"],
		["knight", "windmill", "Don Quixote"],
		["Scuba tank", "lake", "Diver"],
		["lake", "story", "Nessie"],
		["lava", "lamp", "lava lamp"],
		["Land", "Land", "Continent"],
		["life", "Land", "Animal"],
		["Land", "life", "Soil"],
		["Land", "Organic matter", "Soil"],
		["Land", "storm", "Lightning"],
		["Laptop", "Small", "Tablet"],
		["lava", "mountain", "volcano"],
		["lava", "ocean", "Primordial soup"],
		["lava", "Philosophy", "Heat"],
		["lava", "pressure", "granite"],
		["lava", "Science", "Magma"],
		["lava", "sea", "Primordial soup"],
		["lava", "water", "obsidian"],
		["leaf", "sickness", "herb"],
		["water", "leaf", "tea"],
		["leather", "money", "wallet"],
		["wood", "leather", "drum"],
		["letter", "letter", "Post office"],
		["mailman", "letter", "Post office"],
		["letter", "metal", "Mailbox"],
		["letter", "steel", "Mailbox"],
		["letter", "wall", "Post office"],
		["letter", "wood", "Mailbox"],
		["metal", "life", "robot"],
		["life", "mountain range", "Animal"],
		["life", "mountain", "Animal"],
		["ocean", "life", "plankton"],
		["life", "rainbow", "Magic"],
		["rainbow", "life", "unicorn"],
		["life", "Science", "Organic matter"],
		["sea", "life", "plankton"],
		["life", "sky", "bird"],
		["life", "space", "alien"],
		["steel", "life", "robot"],
		["life", "stone", "egg"],
		["swamp", "life", "bacteria"],
		["time", "life", "Death"],
		["water", "life", "plankton"],
		["wood", "life", "pinocchio"],
		["metal", "light bulb", "lamp"],
		["light bulb", "nerd", "idea"],
		["light bulb", "tree", "christmas tree"],
		["warrior", "Light sword", "Force knight"],
		["light", "Machine", "Spotlight"],
		["light", "metal", "Spotlight"],
		["light", "ocean", "lighthouse"],
		["rain", "light", "rainbow"],
		["light", "sea", "lighthouse"],
		["light", "skeleton", "x-ray"],
		["light", "solar cell", "electricity"],
		["light", "steel", "Spotlight"],
		["sword", "light", "Light sword"],
		["light", "sword", "lightsaber"],
		["tool", "light", "flashlight"],
		["vegetable", "light", "pumpkin"],
		["wire", "light", "optical fiber"],
		["zombie", "Lightning", "Frankenstein's monster"],
		["lion", "metal", "Cage"],
		["lion", "steel", "Cage"],
		["lion", "wall", "Cage"],
		["metal", "Liquid", "Quicksilver"],
		["livestock", "mountain", "goat"],
		["livestock", "mud", "pig"],
		["livestock", "santa", "reindeer"],
		["lizard", "lizard", "egg"],
		["lizard", "rainbow", "chameleon"],
		["lizard", "river", "alligator"],
		["lizard", "swamp", "alligator"],
		["lizard", "time", "dinosaur"],
		["plant", "love", "rose"],
		["love", "sugar", "Sweethearts"],
		["love", "time", "life"],
		["petroleum", "Machine", "Combustion engine"],
		["mailman", "metal", "Mailbox"],
		["mailman", "steel", "Mailbox"],
		["mailman", "wall", "Post office"],
		["mailman", "wood", "Mailbox"],
		["pirate", "map", "treasure map"],
		["meat", "salt", "jerky"],
		["meat", "smoke", "ham"],
		["meat", "sun", "jerky"],
		["metal", "monarch", "crown"],
		["metal", "money", "safe"],
		["metal", "oxygen", "rust"],
		["metal", "rainbow", "gold"],
		["river", "metal", "bridge"],
		["metal", "rope", "chain"],
		["sound", "metal", "Bell"],
		["steam engine", "metal", "train"],
		["steam", "metal", "boiler"],
		["metal", "stone", "blade"],
		["metal", "sun", "gold"],
		["metal", "thread", "needle"],
		["tool", "metal", "armor"],
		["wheel", "metal", "car"],
		["metal", "witch", "cauldron"],
		["wolf", "metal", "Cage"],
		["metal", "wood", "hammer"],
		["sky", "meteoroid", "meteor"],
		["milk", "pressure", "butter"],
		["milk", "space", "Milky Way"],
		["time", "milk", "cheese"],
		["wheat", "milk", "cereal"],
		["wild animal", "milk", "cat"],
		["story", "monarch", "fairy tale"],
		["pig", "money", "piggy bank"],
		["money", "steel", "safe"],
		["ocean", "moon", "tide"],
		["sea", "moon", "tide"],
		["sky", "moon", "night"],
		["moon", "star", "space"],
		["sun", "moon", "eclipse"],
		["moon", "time", "night"],
		["wild animal", "moon", "wolf"],
		["ocean", "Motion", "Current"],
		["pond", "Motion", "Stream"],
		["puddle", "Motion", "Rivulet"],
		["sea", "Motion", "Current"],
		["storm", "Motion", "Tornado"],
		["wind", "Motion", "Tornado"],
		["snow", "motorcycle", "snowmobile"],
		["motorcycle", "wall", "Garage"],
		["mountain goat", "scissors", "cashmere"],
		["mountain goat", "thread", "cashmere"],
		["mountain goat", "tool", "cashmere"],
		["mountain goat", "wool", "cashmere"],
		["mountain range", "mountain range", "Continent"],
		["mountain range", "rope", "Cable car"],
		["mountain range", "story", "Yeti"],
		["mountain range", "wire", "Cable car"],
		["mountain", "mountain", "mountain range"],
		["Organic matter", "mountain", "Mineral"],
		["rain", "mountain", "river"],
		["mountain", "river", "waterfall"],
		["mountain", "rope", "Cable car"],
		["mountain", "sheep", "alpaca"],
		["mountain", "Small", "Hill"],
		["mountain", "story", "Yeti"],
		["mountain", "train", "roller coaster"],
		["mountain", "water", "river"],
		["mountain", "wire", "Cable car"],
		["mouse", "needle", "Hedgehog"],
		["mouse", "sky", "bat"],
		["mouse", "tree", "squirrel"],
		["wheel", "mouse", "hamster"],
		["mud", "plant", "swamp"],
		["sand", "mud", "clay"],
		["mud", "sun", "brick"],
		["paper", "music", "sheet music"],
		["rat", "needle", "Hedgehog"],
		["needle", "robot", "sewing machine"],
		["tool", "needle", "Syringe"],
		["nerd", "sugar", "Nerds"],
		["tool", "nerd", "computer"],
		["wire", "nerd", "computer"],
		["plant", "night", "carbon dioxide"],
		["sky", "night", "Darkness"],
		["sky", "night", "star"],
		["night", "sun", "day"],
		["night", "telescope", "star"],
		["time", "night", "Dawn"],
		["time", "night", "day"],
		["tree", "night", "carbon dioxide"],
		["sword", "ninja", "Katana"],
		["ninja", "turtle", "Ninja Turtle"],
		["Nuts", "pressure", "Peanut butter"],
		["planet", "ocean", "Primordial soup"],
		["ocean", "plant", "algae"],
		["plant", "ocean", "seaweed"],
		["ocean", "sand", "beach"],
		["ocean", "Science", "Current"],
		["Scuba tank", "ocean", "Diver"],
		["sickness", "ocean", "seasickness"],
		["ocean", "sky", "horizon"],
		["ocean", "star", "starfish"],
		["ocean", "sun", "salt"],
		["tree", "ocean", "Coral"],
		["unicorn", "ocean", "narwhal"],
		["volcano", "ocean", "Island"],
		["ocean", "volcano", "isle"],
		["ocean", "wild animal", "shark"],
		["ocean", "wind", "wave"],
		["oil", "pottery", "oil lamp"],
		["oil", "rope", "oil lamp"],
		["oil", "vegetable", "french fries"],
		["Organic matter", "Rock", "Mineral"],
		["Organic matter", "stone", "Mineral"],
		["oxygen", "oxygen", "ozone"],
		["Philosophy", "oxygen", "Small"],
		["steel", "oxygen", "rust"],
		["oxygen", "wine", "vinegar"],
		["Philosophy", "ozone", "Small"],
		["Paper cup", "thread", "String phone"],
		["Paper cup", "wire", "String phone"],
		["paper", "paper", "newspaper"],
		["paper", "pencil", "letter"],
		["sand", "paper", "sandpaper"],
		["paper", "scissors", "confetti"],
		["sky", "paper", "kite"],
		["paper", "story", "book"],
		["tobacco", "paper", "cigarette"],
		["wind", "paper", "kite"],
		["paper", "wood", "book"],
		["pasta", "thread", "spaghetti"],
		["Pebble", "Pebble", "Rock"],
		["Philosophy", "Pebble", "Small"],
		["pencil", "rainbow", "crayon"],
		["water", "pencil", "paint"],
		["wood", "pencil", "ruler"],
		["petroleum", "steam engine", "Combustion engine"],
		["petroleum", "wheel", "Combustion engine"],
		["planet", "Philosophy", "Big"],
		["Philosophy", "pottery", "Container"],
		["river", "Philosophy", "Motion"],
		["Philosophy", "Rivulet", "Small"],
		["Philosophy", "safe", "Container"],
		["Philosophy", "scorpion", "Small"],
		["Philosophy", "seahorse", "Small"],
		["skeleton", "Philosophy", "Death"],
		["solar system", "Philosophy", "Big"],
		["Philosophy", "spider", "Small"],
		["Stream", "Philosophy", "Motion"],
		["sun", "Philosophy", "Big"],
		["Tornado", "Philosophy", "Motion"],
		["Universe", "Philosophy", "Big"],
		["wind", "Philosophy", "Motion"],
		["pottery", "pig", "piggy bank"],
		["pig", "tool", "meat"],
		["pig", "wild animal", "wild boar"],
		["pilot", "umbrella", "parachute"],
		["water", "pipe", "water pipe"],
		["sailor", "pirate ship", "pirate"],
		["wild animal", "pirate ship", "rat"],
		["sailboat", "pirate", "pirate ship"],
		["pirate", "treasure map", "treasure"],
		["pitchfork", "Small", "Fork"],
		["planet", "ring", "saturn"],
		["rust", "planet", "mars"],
		["planet", "sea", "Primordial soup"],
		["planet", "Small", "Mercury"],
		["planet", "smog", "Venus"],
		["planet", "storm", "Jupiter"],
		["sun", "planet", "solar system"],
		["planet", "volcano", "Venus"],
		["plant", "plant", "garden"],
		["Pollen", "plant", "Seed"],
		["plant", "pond", "Reed"],
		["plant", "pottery", "vase"],
		["pressure", "plant", "coal"],
		["plant", "puddle", "Reed"],
		["plant", "river", "Reed"],
		["sand", "plant", "cactus"],
		["sea", "plant", "algae"],
		["plant", "sea", "seaweed"],
		["plant", "sickness", "herb"],
		["plant", "stone", "moss"],
		["plant", "sun", "energy"],
		["plant", "sun", "oxygen"],
		["plant", "sun", "sunflower"],
		["swamp", "plant", "Peat"],
		["plant", "swamp", "Reed"],
		["plant", "time", "tree"],
		["plant", "wall", "ivy"],
		["water", "plant", "algae"],
		["plant", "wind", "Pollen"],
		["water", "pond", "lake"],
		["wild animal", "pond", "frog"],
		["tree", "pottery", "bonsai tree"],
		["sky", "pressure", "atmosphere"],
		["star", "pressure", "black hole"],
		["sunflower", "pressure", "oil"],
		["swamp", "pressure", "Peat"],
		["wood", "pressure", "paper"],
		["Quicksilver", "tool", "Thermometer"],
		["rain", "rain", "flood"],
		["rain", "smog", "acid rain"],
		["rain", "smoke", "acid rain"],
		["rain", "sun", "rainbow"],
		["rain", "time", "flood"],
		["tool", "rain", "umbrella"],
		["rainbow", "rainbow", "double rainbow!"],
		["rainbow", "sugar", "Skittles"],
		["water", "rainbow", "paint"],
		["rainbow", "wax", "crayon"],
		["Rainforest", "rope", "Vine"],
		["Rainforest", "thread", "Vine"],
		["Rainforest", "wire", "Vine"],
		["ring", "volcano", "The One Ring"],
		["river", "Science", "Motion"],
		["river", "Small", "Stream"],
		["river", "steel", "bridge"],
		["wall", "river", "dam"],
		["river", "wheel", "waterwheel"],
		["river", "Willy Wonka", "chocolate"],
		["river", "wood", "bridge"],
		["robot", "vacuum cleaner", "Robot vacuum"],
		["robot", "vacuum cleaner", "roomba"],
		["Rock", "Rock", "Boulder"],
		["Small", "Rock", "Pebble"],
		["Rock", "stone", "Boulder"],
		["rocket", "wall", "Hangar"],
		["rope", "steel", "chain"],
		["swordfish", "rope", "Net"],
		["wood", "rope", "Bow"],
		["rose", "steam", "perfume"],
		["rose", "water", "perfume"],
		["ruins", "Science", "Archeologist"],
		["rv", "wall", "Garage"],
		["tool", "safe", "Toolbox"],
		["wheat", "safe", "Silo"],
		["sailboat", "sickness", "seasickness"],
		["sailboat", "wild animal", "rat"],
		["sword", "sailor", "pirate"],
		["sand", "sand", "desert"],
		["sea", "sand", "beach"],
		["stone", "sand", "sandstone"],
		["sand", "storm", "sandstorm"],
		["sand", "sugar", "Fun Dip"],
		["sand", "swamp", "quicksand"],
		["water", "sand", "beach"],
		["wild animal", "sand", "scorpion"],
		["sand", "wind", "dune"],
		["santa", "wild animal", "reindeer"],
		["Sap", "sugar", "Maple syrup"],
		["sea", "Science", "Current"],
		["Science", "star", "Plasma"],
		["Stream", "Science", "Motion"],
		["Science", "sun", "Plasma"],
		["Tornado", "Science", "Motion"],
		["volcano", "Science", "Magma"],
		["water", "Science", "Liquid"],
		["wind", "Science", "Motion"],
		["scissors", "sheep", "wool"],
		["tree", "scissors", "bonsai tree"],
		["Scuba tank", "sea", "Diver"],
		["Scuba tank", "swimmer", "Diver"],
		["sea", "sea", "ocean"],
		["sickness", "sea", "seasickness"],
		["sea", "sky", "horizon"],
		["sea", "star", "starfish"],
		["sea", "sun", "salt"],
		["tree", "sea", "Coral"],
		["sea", "unicorn", "narwhal"],
		["volcano", "sea", "Island"],
		["volcano", "sea", "isle"],
		["water", "sea", "ocean"],
		["sea", "wild animal", "shark"],
		["sea", "wind", "wave"],
		["seaplane", "wall", "Hangar"],
		["sheep", "tool", "wool"],
		["Shovel", "Small", "Spoon"],
		["sword", "shuriken", "Katana"],
		["steamboat", "sickness", "seasickness"],
		["sky", "squirrel", "flying squirrel"],
		["sky", "star", "space"],
		["sky", "stone", "moon"],
		["sky", "sun", "day"],
		["sky", "twilight", "Darkness"],
		["skyscraper", "skyscraper", "city"],
		["Sleigh", "wall", "Garage"],
		["Small", "stone", "Pebble"],
		["Stream", "Small", "Rivulet"],
		["Small", "Tablet", "Smartphone"],
		["wind", "Small", "Gust"],
		["snow", "snow", "blizzard"],
		["snow", "storm", "blizzard"],
		["snow", "surfer", "snowboard"],
		["snow", "wagon", "sledge"],
		["wagon", "snow", "Sleigh"],
		["snow", "wind", "blizzard"],
		["wood", "snow", "snowboard"],
		["snowball", "snowball", "snowman"],
		["snowboard", "wheel", "skateboard"],
		["sun", "snowman", "carrot"],
		["sun", "snowman", "coal"],
		["sun", "snowman", "puddle"],
		["snowman", "vegetable", "carrot"],
		["snowmobile", "wall", "Garage"],
		["soap", "water", "soap bubble"],
		["Soil", "Soil", "Land"],
		["solar cell", "sun", "electricity"],
		["sound", "steel", "Bell"],
		["sound", "wood", "Bell"],
		["stone", "space", "meteoroid"],
		["sword", "space", "Light sword"],
		["space", "time", "Tardis"],
		["spaceship", "wall", "Hangar"],
		["spider", "thread", "web"],
		["squirrel", "tree", "nut"],
		["squirrel", "wind", "flying squirrel"],
		["star", "star", "constellation"],
		["star", "star", "galaxy"],
		["sun", "star", "space"],
		["tree", "star", "christmas tree"],
		["statue", "water", "fountain"],
		["steam engine", "steel", "train"],
		["steam engine", "wagon", "train"],
		["steam engine", "water", "steamboat"],
		["steam engine", "wheel", "train"],
		["tool", "steel", "armor"],
		["steel", "witch", "cauldron"],
		["wolf", "steel", "Cage"],
		["steel", "wool", "steel wool"],
		["sword", "stone", "excalibur"],
		["stone", "tool", "statue"],
		["wheat", "stone", "flour"],
		["wind", "stone", "sand"],
		["storm", "storm", "Tornado"],
		["storm", "wind", "Tornado"],
		["story", "story", "Legend"],
		["story", "time", "Legend"],
		["wild animal", "sugar", "ant"],
		["sugar", "wire", "Red Vines"],
		["sun", "time", "day"],
		["sun", "tool", "solar cell"],
		["sun", "tree", "fruit"],
		["sun", "vampire", "dust"],
		["wind", "surfer", "Windsurfer"],
		["swamp", "time", "Peat"],
		["telescope", "telescope", "Binoculars"],
		["thread", "thread", "rope"],
		["thread", "tool", "fabric"],
		["wax", "thread", "candle"],
		["wild animal", "thread", "spider"],
		["time", "tool", "clock"],
		["time", "wheel", "clock"],
		["wild animal", "time", "sloth"],
		["time", "wine", "vinegar"],
		["tobacco", "wood", "pipe"],
		["tool", "tool", "Machine"],
		["tool", "tree", "wood"],
		["tool", "wheel", "Machine"],
		["tool", "wood", "wheel"],
		["wool", "tool", "sweater"],
		["tractor", "wall", "Garage"],
		["train", "wall", "Trainyard"],
		["tree", "tree", "forest"],
		["tree", "wild animal", "monkey"],
		["tree", "wind", "leaf"],
		["turtle", "turtle", "egg"],
		["unicorn", "water", "narwhal"],
		["village", "village", "city"],
		["wall", "wall", "house"],
		["wheat", "wall", "Silo"],
		["wolf", "wall", "Cage"],
		["wall", "wood", "fence"],
		["water", "water", "sea"],
		["water", "wheel", "waterwheel"],
		["water", "wood", "boat"],
		["waterwheel", "wheat", "flour"],
		["windmill", "wheat", "flour"],
		["wheel", "wheel", "bicycle"],
		["wheel", "wind", "windmill"],
		["wheel", "wood", "cart"],
		["wheel", "wool", "thread"],
		["wild animal", "wire", "snake"],
		["wild animal", "wood", "beaver"],
		["wind turbine", "wind", "electricity"],
		["wind", "wind", "Tornado"],
		["wood", "wind", "flute"],
		["wine", "wood", "Barrel"],
		["wood", "wire", "Bow"],
		["wire", "wool", "steel wool"],
		["wizard", "wood", "wand"]
	]
};

const form = document.getElementById("combine-form");
const firstSelect = document.getElementById("first-element");
const secondSelect = document.getElementById("second-element");
const resultText = document.getElementById("result-text");
const totalCount = document.getElementById("total-count");
const copySaveButton = document.getElementById("copy-save-button");
const importSaveButton = document.getElementById("import-save-button");
const clearSaveButton = document.getElementById("clear-save-button");
const saveDataInput = document.getElementById("save-data-input");

const SAVE_KEY = "alchemist-save-v1";
const SAVE_INTERVAL_MS = 2000;
const SAVE_FORMAT_PREFIX_V4 = "b4:";
const DATA_ID = "e776-r1655-4b33bc6d";

const elementNameByLower = new Map();
for (const element of DATA.elements) {
	elementNameByLower.set(element.toLowerCase(), element);
}

const activeElementSet = new Set(DATA.elements.map((name) => toCanonicalName(name)));
let recipeIndex = new Map();
const unlocked = new Set(DATA.baseElements.map((name) => toCanonicalName(name)));

function toCanonicalName(name) {
	const normalized = String(name).toLowerCase();
	return elementNameByLower.get(normalized) || String(name);
}

function toRecipeKey(first, second) {
	return [first.toLowerCase(), second.toLowerCase()].sort().join("|");
}

function rebuildActiveData() {
	recipeIndex = new Map();
	for (const recipe of DATA.recipes) {
		const first = toCanonicalName(recipe[0]);
		const second = toCanonicalName(recipe[1]);
		const result = toCanonicalName(recipe[2]);
		const key = toRecipeKey(first, second);
		const results = recipeIndex.get(key) || [];
		if (!results.includes(result)) {
			results.push(result);
		}
		recipeIndex.set(key, results);
	}
}

function populateElementOptions() {
	const sorted = Array.from(unlocked).sort((a, b) => a.localeCompare(b));
	const firstValue = firstSelect.value;
	const secondValue = secondSelect.value;
	const html = sorted.map((element) => `<option value=\"${element}\">${element}</option>`).join("");
	firstSelect.innerHTML = html;
	secondSelect.innerHTML = html;
	if (firstValue && unlocked.has(firstValue)) {
		firstSelect.value = firstValue;
	}
	if (secondValue && unlocked.has(secondValue)) {
		secondSelect.value = secondValue;
	}
}

function combineSelectedElements() {
	const first = firstSelect.value;
	const second = secondSelect.value;
	const key = toRecipeKey(first, second);
	const results = recipeIndex.get(key);
	if (!results || results.length === 0) {
		resultText.textContent = `No recipe for ${first} + ${second}.`;
		return;
	}
	const newlyUnlocked = [];
	for (const result of results) {
		if (unlocked.has(result)) {
			continue;
		}
		unlocked.add(result);
		newlyUnlocked.push(result);
	}
	if (newlyUnlocked.length === 0) {
		resultText.textContent = `already unlocked ${results.join(", ")}.`;
		return;
	}
	resultText.textContent = `Unlocked ${newlyUnlocked.join(", ")}!`;
	populateElementOptions();
	renderInventory();
	saveDataInput.value = getEncodedSavePayload();
	saveGame();
}

function renderInventory() {
	const total = activeElementSet.size;
	const count = Array.from(unlocked).filter((name) => activeElementSet.has(name)).length;
	const percent = total === 0 ? 0 : (count / total) * 100;
	totalCount.textContent = `${count}/${total} elements unlocked (${percent.toFixed(1)}%)`;
}

function bytesToBase64(bytes) {
	let binary = "";
	for (const value of bytes) {
		binary += String.fromCharCode(value);
	}
	return btoa(binary);
}

function base64ToBytes(encoded) {
	const binary = atob(encoded);
	const bytes = new Uint8Array(binary.length);
	for (let i = 0; i < binary.length; i += 1) {
		bytes[i] = binary.charCodeAt(i);
	}
	return bytes;
}

function getOrderedElements() {
	return Array.from(activeElementSet).sort((a, b) => a.localeCompare(b));
}

function encodeBitsetForElements(orderedElements) {
	const byteLength = Math.ceil(orderedElements.length / 8);
	const bits = new Uint8Array(byteLength);
	for (let i = 0; i < orderedElements.length; i += 1) {
		if (!unlocked.has(orderedElements[i])) {
			continue;
		}
		bits[i >> 3] |= 1 << (i & 7);
	}
	return bits;
}

function decodeBitsetToNames(bitsetBytes, orderedElements) {
	const neededBytes = Math.ceil(orderedElements.length / 8);
	if (bitsetBytes.length < neededBytes) {
		return null;
	}
	const names = [];
	for (let i = 0; i < orderedElements.length; i += 1) {
		const bit = (bitsetBytes[i >> 3] >> (i & 7)) & 1;
		if (bit === 1) {
			names.push(orderedElements[i]);
		}
	}
	return names;
}

function applyUnlockedNames(names) {
	unlocked.clear();
	for (const item of names) {
		const canonicalName = toCanonicalName(item);
		if (activeElementSet.has(canonicalName)) {
			unlocked.add(canonicalName);
		}
	}
	if (unlocked.size === 0) {
		for (const element of DATA.baseElements) {
			unlocked.add(toCanonicalName(element));
		}
	}
	return true;
}

function getEncodedSavePayload() {
	const ordered = getOrderedElements();
	const bits = encodeBitsetForElements(ordered);
	const payload = bytesToBase64(bits);
	return `${SAVE_FORMAT_PREFIX_V4}${DATA_ID}:${payload}`;
}

function tryApplyV4Save(encoded) {
	if (!encoded.startsWith(SAVE_FORMAT_PREFIX_V4)) {
		return false;
	}
	const body = encoded.slice(SAVE_FORMAT_PREFIX_V4.length);
	const split = body.indexOf(":");
	if (split < 0) {
		return false;
	}
	const incomingDataId = body.slice(0, split);
	const bitsetPart = body.slice(split + 1);
	if (incomingDataId !== DATA_ID) {
		return false;
	}
	const bytes = base64ToBytes(bitsetPart);
	const names = decodeBitsetToNames(bytes, getOrderedElements());
	if (!names) {
		return false;
	}
	return applyUnlockedNames(names);
}

function tryApplyLegacyJsonSave(encoded) {
	const binary = atob(encoded);
	const bytes = new Uint8Array(binary.length);
	for (let i = 0; i < binary.length; i += 1) {
		bytes[i] = binary.charCodeAt(i);
	}
	const raw = new TextDecoder().decode(bytes);
	const parsed = JSON.parse(raw);
	if (!parsed || !Array.isArray(parsed.unlocked)) {
		return false;
	}
	return applyUnlockedNames(parsed.unlocked);
}

function saveGame() {
	try {
		localStorage.setItem(SAVE_KEY, getEncodedSavePayload());
	} catch (error) {
	}
}

function loadGame() {
	try {
		const encoded = localStorage.getItem(SAVE_KEY);
		if (!encoded) {
			return;
		}
		if (tryApplyV4Save(encoded)) {
			return;
		}
		if (tryApplyLegacyJsonSave(encoded)) {
			saveGame();
		}
	} catch (error) {
	}
}

async function copySaveDataToClipboard() {
	const encodedSave = getEncodedSavePayload();
	saveDataInput.value = encodedSave;
	try {
		await navigator.clipboard.writeText(encodedSave);
		resultText.textContent = "save data copied to clipboard.";
	} catch (error) {
		resultText.textContent = "could not copy save data.";
	}
}

function importSaveData() {
	const encoded = saveDataInput.value.trim();
	if (!encoded) {
		resultText.textContent = "could not import save data.";
		return;
	}
	try {
		const ok = tryApplyV4Save(encoded) || tryApplyLegacyJsonSave(encoded);
		if (!ok) {
			resultText.textContent = "could not import save data.";
			return;
		}
		populateElementOptions();
		renderInventory();
		saveGame();
		saveDataInput.value = getEncodedSavePayload();
		resultText.textContent = "save data imported.";
	} catch (error) {
		resultText.textContent = "could not import save data.";
	}
}

function clearSaveData() {
	unlocked.clear();
	for (const element of DATA.baseElements) {
		unlocked.add(toCanonicalName(element));
	}
	saveDataInput.value = "";
	localStorage.removeItem(SAVE_KEY);
	populateElementOptions();
	renderInventory();
	resultText.textContent = "save data cleared.";
}

rebuildActiveData();
loadGame();
populateElementOptions();
renderInventory();
saveDataInput.value = getEncodedSavePayload();
saveGame();
setInterval(saveGame, SAVE_INTERVAL_MS);

form.addEventListener("submit", (event) => {
	event.preventDefault();
	combineSelectedElements();
});

function handleSelectEnterKey(event) {
	if (event.key !== "Enter") {
		return;
	}
	event.preventDefault();
	combineSelectedElements();
}

firstSelect.addEventListener("keydown", handleSelectEnterKey);
secondSelect.addEventListener("keydown", handleSelectEnterKey);

copySaveButton.addEventListener("click", () => {
	copySaveDataToClipboard();
});

importSaveButton.addEventListener("click", () => {
	importSaveData();
});

clearSaveButton.addEventListener("click", () => {
	if (confirm("Are you sure you want to clear your save? This cannot be undone.")) {
		clearSaveData();
	}
});
