"use strict";

const DATA = {
	baseElements: [
		"air",
		"earth",
		"fire",
		"water"
	],
	elements: [
		"acid rain",
		"air",
		"airplane",
		"alarm clock",
		"alcohol",
		"algae",
		"alien",
		"allergy",
		"alligator",
		"alpaca",
		"ambulance",
		"angel",
		"angler",
		"ant",
		"antarctica",
		"aquarium",
		"archipelago",
		"armadillo",
		"armor",
		"ash",
		"astronaut",
		"Astronaut Ice Cream",
		"atmosphere",
		"atomic bomb",
		"aurora",
		"avalanche",
		"axe",
		"bacon",
		"bacteria",
		"baker",
		"bakery",
		"banana",
		"banana bread",
		"bandage",
		"bank",
		"barn",
		"bat",
		"batman",
		"batter",
		"bayonet",
		"bbq",
		"beach",
		"beaver",
		"bee",
		"beehive",
		"beer",
		"bicycle",
		"bird",
		"birdhouse",
		"black hole",
		"blade",
		"blender",
		"blizzard",
		"blood",
		"blueprint",
		"boat",
		"boiler",
		"bone",
		"bonsai tree",
		"book",
		"bread",
		"brick",
		"bridge",
		"broom",
		"bullet",
		"bulletproof vest",
		"bus",
		"butcher",
		"butter",
		"butterfly",
		"cactus",
		"Cadbury Eggs",
		"cake",
		"camel",
		"campfire",
		"candle",
		"candy cane",
		"cannon",
		"cape",
		"car",
		"caramel",
		"Caramel Apple",
		"Caramelo",
		"carbon dioxide",
		"carrot",
		"cart",
		"cashmere",
		"castle",
		"cat",
		"catnip",
		"cauldron",
		"caviar",
		"centaur",
		"cereal",
		"chain",
		"chainsaw",
		"chameleon",
		"charcoal",
		"cheese",
		"cheeseburger",
		"chicken",
		"chicken soup",
		"chicken wing",
		"chimney",
		"chocolate",
		"chocolate milk",
		"christmas stocking",
		"christmas tree",
		"cigarette",
		"city",
		"clay",
		"clock",
		"cloud",
		"coal",
		"coconut",
		"coconut milk",
		"coffin",
		"cold",
		"computer",
		"computer mouse",
		"confetti",
		"constellation",
		"cookbook",
		"cookie",
		"cookie dough",
		"corpse",
		"cotton",
		"cotton candy",
		"cow",
		"crayon",
		"crow",
		"crown",
		"crystal ball",
		"cuckoo",
		"cyborg",
		"cyclist",
		"dam",
		"darth vader",
		"day",
		"desert",
		"dew",
		"diamond",
		"dinosaur",
		"doctor",
		"dog",
		"Doge",
		"doghouse",
		"Don Quixote",
		"donut",
		"double rainbow!",
		"dough",
		"dragon",
		"drone",
		"drum",
		"drunk",
		"dry ice",
		"duck",
		"duckling",
		"dune",
		"dust",
		"dynamite",
		"eagle",
		"earth",
		"earthquake",
		"eclipse",
		"egg",
		"egg timer",
		"electric car",
		"electric eel",
		"electrician",
		"electricity",
		"email",
		"energy",
		"engineer",
		"eruption",
		"excalibur",
		"explosion",
		"fabric",
		"fairy tale",
		"family",
		"family tree",
		"farm",
		"farmer",
		"faun",
		"fence",
		"field",
		"fire",
		"fire extinguisher",
		"fireman",
		"fireplace",
		"firetruck",
		"fireworks",
		"fish",
		"fish and chips",
		"fishing rod",
		"flamethrower",
		"flashlight",
		"flood",
		"flour",
		"flower",
		"flute",
		"flying fish",
		"flying squirrel",
		"fog",
		"forest",
		"fortune cookie",
		"fossil",
		"fountain",
		"fox",
		"frankenstein",
		"french fries",
		"fridge",
		"frog",
		"frozen yogurt",
		"fruit",
		"fruit tree",
		"Fun Dip",
		"galaxy",
		"garden",
		"gardener",
		"geyser",
		"ghost",
		"gift",
		"gingerbread house",
		"gingerbread man",
		"glacier",
		"glass",
		"glasses",
		"gnome",
		"goat",
		"godzilla",
		"gold",
		"Goldfish",
		"golem",
		"granite",
		"grass",
		"grave",
		"gravestone",
		"graveyard",
		"greenhouse",
		"grenade",
		"grilled cheese",
		"grim reaper",
		"Guinness Float",
		"gun",
		"gunpowder",
		"hail",
		"ham",
		"hamburger",
		"hammer",
		"hamster",
		"hard roe",
		"harp",
		"hay",
		"hay bale",
		"hedge",
		"helicopter",
		"herb",
		"hero",
		"hippo",
		"honey",
		"horizon",
		"horse",
		"horseshoe",
		"hospital",
		"hourglass",
		"house",
		"human",
		"hummingbird",
		"hurricane",
		"husky",
		"ice",
		"ice cream",
		"ice cream truck",
		"iceberg",
		"iced tea",
		"idea",
		"igloo",
		"internet",
		"isle",
		"ivy",
		"jack-o'-lantern",
		"jam",
		"jedi",
		"jerky",
		"juice",
		"Juicy Fruit",
		"Keyboard Cat",
		"kite",
		"knight",
		"lake",
		"lamp",
		"lasso",
		"lava",
		"lava lamp",
		"lawn mower",
		"leaf",
		"leather",
		"lemonade",
		"letter",
		"library",
		"life",
		"light",
		"light bulb",
		"lighthouse",
		"lightsaber",
		"lion",
		"livestock",
		"lizard",
		"log cabin",
		"love",
		"lumberjack",
		"mac and cheese",
		"mailman",
		"manatee",
		"map",
		"mars",
		"marshmallows",
		"mayonnaise",
		"meat",
		"medusa",
		"mermaid",
		"metal",
		"meteor",
		"meteoroid",
		"microscope",
		"milk",
		"milk shake",
		"Milky Way",
		"minotaur",
		"mirror",
		"mold",
		"monarch",
		"money",
		"monkey",
		"moon",
		"moss",
		"moth",
		"motorcycle",
		"Mounds",
		"mountain",
		"mountain goat",
		"mountain range",
		"mouse",
		"mousetrap",
		"mud",
		"mummy",
		"music",
		"narwhal",
		"needle",
		"nerd",
		"Nerds",
		"Nessie",
		"nest",
		"newspaper",
		"night",
		"ninja",
		"Ninja Turtle",
		"nut",
		"oasis",
		"obsidian",
		"ocean",
		"oil",
		"oil lamp",
		"omelette",
		"optical fiber",
		"orchard",
		"origami",
		"ostrich",
		"owl",
		"oxygen",
		"ozone",
		"paint",
		"palm",
		"paper",
		"paper airplane",
		"parachute",
		"parrot",
		"pasta",
		"peacock",
		"Peeps",
		"pegasus",
		"pencil",
		"pencil sharpener",
		"penguin",
		"penicillin",
		"perfume",
		"petroleum",
		"phoenix",
		"picnic",
		"pie",
		"pig",
		"pigeon",
		"piggy bank",
		"pillow",
		"pilot",
		"pinocchio",
		"pipe",
		"piranha",
		"pirate",
		"pirate ship",
		"pitchfork",
		"pizza",
		"planet",
		"plankton",
		"plant",
		"platypus",
		"Pokki",
		"pond",
		"Pop Rocks",
		"popsicle",
		"pottery",
		"pressure",
		"printer",
		"prism",
		"pterodactyl",
		"puddle",
		"pumpkin",
		"pyramid",
		"quicksand",
		"rabbit",
		"rain",
		"rainbow",
		"rat",
		"recipe",
		"Red Vines",
		"reindeer",
		"ring",
		"Ring Pop",
		"river",
		"robot",
		"rocket",
		"roller coaster",
		"roomba",
		"rope",
		"rose",
		"ruins",
		"ruler",
		"rust",
		"rv",
		"saddle",
		"safe",
		"safety glasses",
		"sailboat",
		"sailor",
		"salt",
		"sand",
		"sand castle",
		"sandpaper",
		"sandstone",
		"sandstorm",
		"sandwich",
		"santa",
		"saturn",
		"scalpel",
		"scarecrow",
		"scissors",
		"scorpion",
		"scythe",
		"sea",
		"seagull",
		"seahorse",
		"seal",
		"seaplane",
		"seasickness",
		"seaweed",
		"sewing machine",
		"shark",
		"sheep",
		"sheet music",
		"shuriken",
		"sickness",
		"skateboard",
		"skeleton",
		"ski goggles",
		"Skittles",
		"sky",
		"skyscraper",
		"sledge",
		"sloth",
		"smog",
		"smoke",
		"smoke signal",
		"smoothie",
		"snake",
		"snow",
		"snow globe",
		"snowball",
		"snowboard",
		"snowman",
		"snowmobile",
		"soap",
		"soap bubble",
		"soda",
		"solar cell",
		"solar system",
		"sound",
		"space",
		"space station",
		"spaceship",
		"spaghetti",
		"sphinx",
		"spider",
		"sprinkles",
		"squirrel",
		"star",
		"Starburst",
		"starfish",
		"statue",
		"steak",
		"steam",
		"steam engine",
		"steamboat",
		"steel",
		"steel wool",
		"stethoscope",
		"stone",
		"storm",
		"story",
		"sugar",
		"sun",
		"sundial",
		"sunflower",
		"sunglasses",
		"super nova",
		"surfer",
		"sushi",
		"swamp",
		"sweater",
		"Swedish Fish",
		"Sweethearts",
		"swim goggles",
		"swimmer",
		"sword",
		"swordfish",
		"tank",
		"Tardis",
		"taser",
		"tea",
		"telescope",
		"tent",
		"The Doctor",
		"The One Ring",
		"thread",
		"tide",
		"time",
		"titanic",
		"toast",
		"tobacco",
		"tool",
		"toucan",
		"tractor",
		"train",
		"treasure",
		"treasure map",
		"tree",
		"treehouse",
		"trojan horse",
		"tsunami",
		"tunnel",
		"turtle",
		"twilight",
		"Twix",
		"tyrannosaurus rex",
		"ufo",
		"umbrella",
		"unicorn",
		"vacuum cleaner",
		"vampire",
		"vase",
		"vegetable",
		"village",
		"vinegar",
		"volcano",
		"vulture",
		"wagon",
		"wall",
		"wallet",
		"wand",
		"warrior",
		"watch",
		"water",
		"water gun",
		"water lily",
		"water pipe",
		"waterfall",
		"waterwheel",
		"wave",
		"wax",
		"web",
		"werewolf",
		"wheat",
		"wheel",
		"wild animal",
		"wild boar",
		"Willy Wonka",
		"wind",
		"wind turbine",
		"windmill",
		"window",
		"wine",
		"wire",
		"witch",
		"wizard",
		"wolf",
		"wood",
		"woodpecker",
		"wool",
		"wrapping paper",
		"x-ray",
		"yak",
		"Yeti",
		"yoda",
		"yogurt",
		"zombie"
	],
	recipes: [
		["air", "air", "pressure"],
		["air", "cloud", "sky"],
		["air", "dinosaur", "pterodactyl"],
		["earth", "air", "dust"],
		["egg", "air", "bird"],
		["air", "energy", "wind"],
		["air", "fire", "energy"],
		["air", "lava", "stone"],
		["air", "life", "bird"],
		["air", "metal", "rust"],
		["air", "pressure", "atmosphere"],
		["pressure", "air", "wind"],
		["air", "soap", "soap bubble"],
		["air", "steam", "cloud"],
		["air", "steel", "rust"],
		["air", "stone", "sand"],
		["water", "air", "rain"],
		["air", "wave", "sound"],
		["air", "wine", "vinegar"],
		["airplane", "alien", "ufo"],
		["airplane", "astronaut", "spaceship"],
		["blade", "airplane", "helicopter"],
		["airplane", "human", "pilot"],
		["airplane", "ocean", "seaplane"],
		["airplane", "paper", "paper airplane"],
		["airplane", "robot", "drone"],
		["airplane", "sea", "seaplane"],
		["airplane", "space", "rocket"],
		["squirrel", "airplane", "flying squirrel"],
		["airplane", "water", "seaplane"],
		["windmill", "airplane", "helicopter"],
		["alcohol", "flower", "perfume"],
		["fruit", "alcohol", "wine"],
		["human", "alcohol", "drunk"],
		["alcohol", "rose", "perfume"],
		["alcohol", "wheat", "beer"],
		["algae", "stone", "moss"],
		["rocket", "alien", "ufo"],
		["house", "ambulance", "hospital"],
		["angel", "music", "harp"],
		["antarctica", "atmosphere", "aurora"],
		["ocean", "antarctica", "iceberg"],
		["sea", "antarctica", "iceberg"],
		["sky", "antarctica", "aurora"],
		["sun", "antarctica", "aurora"],
		["bullet", "armor", "bulletproof vest"],
		["car", "armor", "tank"],
		["human", "armor", "knight"],
		["life", "armor", "robot"],
		["wild animal", "armor", "armadillo"],
		["oil", "ash", "soap"],
		["astronaut", "ice cream", "Astronaut Ice Cream"],
		["meteoroid", "atmosphere", "meteor"],
		["axe", "electricity", "chainsaw"],
		["axe", "human", "lumberjack"],
		["bread", "bacon", "sandwich"],
		["glass", "bacteria", "microscope"],
		["bacteria", "glasses", "microscope"],
		["human", "bacteria", "sickness"],
		["milk", "bacteria", "yogurt"],
		["house", "baker", "bakery"],
		["paper", "baker", "recipe"],
		["bread", "banana", "banana bread"],
		["farmer", "barn", "farm"],
		["bat", "human", "batman"],
		["meat", "bbq", "steak"],
		["bird", "beach", "seagull"],
		["beach", "glasses", "sunglasses"],
		["light", "beach", "lighthouse"],
		["beach", "sandwich", "picnic"],
		["tree", "beach", "palm"],
		["beach", "wind", "dune"],
		["beaver", "duck", "platypus"],
		["beaver", "river", "dam"],
		["beaver", "tree", "dam"],
		["beaver", "wood", "dam"],
		["bee", "beehive", "honey"],
		["bee", "beehive", "wax"],
		["bee", "flower", "honey"],
		["bee", "house", "beehive"],
		["bee", "tree", "beehive"],
		["beer", "human", "drunk"],
		["beer", "ice cream", "Guinness Float"],
		["bicycle", "energy", "motorcycle"],
		["bicycle", "human", "cyclist"],
		["bicycle", "steel", "motorcycle"],
		["bird", "bird", "egg"],
		["bird", "city", "pigeon"],
		["clock", "bird", "cuckoo"],
		["bird", "corpse", "vulture"],
		["bird", "dinosaur", "pterodactyl"],
		["bird", "earth", "ostrich"],
		["bird", "farmer", "chicken"],
		["bird", "field", "crow"],
		["fire", "bird", "phoenix"],
		["fish", "bird", "flying fish"],
		["bird", "flower", "hummingbird"],
		["bird", "hay", "nest"],
		["bird", "horse", "pegasus"],
		["bird", "house", "birdhouse"],
		["human", "bird", "angel"],
		["ice", "bird", "penguin"],
		["bird", "lake", "duck"],
		["bird", "letter", "pigeon"],
		["livestock", "bird", "chicken"],
		["bird", "metal", "airplane"],
		["mountain", "bird", "eagle"],
		["mouse", "bird", "bat"],
		["night", "bird", "owl"],
		["bird", "ocean", "seagull"],
		["bird", "paper", "origami"],
		["bird", "pirate", "parrot"],
		["bird", "pond", "duck"],
		["bird", "rainbow", "peacock"],
		["bird", "rainbow", "toucan"],
		["bird", "sand", "ostrich"],
		["bird", "scarecrow", "crow"],
		["bird", "sea", "seagull"],
		["bird", "snow", "penguin"],
		["squirrel", "bird", "flying squirrel"],
		["bird", "statue", "pigeon"],
		["bird", "steel", "airplane"],
		["bird", "tree", "nest"],
		["bird", "unicorn", "pegasus"],
		["water", "bird", "duck"],
		["bird", "wizard", "owl"],
		["bird", "wood", "woodpecker"],
		["blade", "blade", "scissors"],
		["cow", "blade", "leather"],
		["blade", "doctor", "scalpel"],
		["blade", "electricity", "blender"],
		["glass", "blade", "blender"],
		["blade", "grass", "scythe"],
		["gun", "blade", "bayonet"],
		["blade", "hospital", "scalpel"],
		["human", "blade", "blood"],
		["blade", "livestock", "meat"],
		["blade", "metal", "sword"],
		["paper", "blade", "confetti"],
		["blade", "pencil", "pencil sharpener"],
		["pig", "blade", "leather"],
		["blade", "pumpkin", "jack-o'-lantern"],
		["star", "blade", "shuriken"],
		["blade", "steel", "sword"],
		["blade", "wheat", "scythe"],
		["blade", "wood", "axe"],
		["fruit", "blender", "smoothie"],
		["blood", "fabric", "bandage"],
		["fish", "blood", "piranha"],
		["human", "blood", "vampire"],
		["blood", "ocean", "shark"],
		["sea", "blood", "shark"],
		["boat", "fabric", "sailboat"],
		["human", "boat", "sailor"],
		["boat", "pirate", "pirate ship"],
		["boat", "sickness", "seasickness"],
		["steam engine", "boat", "steamboat"],
		["boat", "wind", "sailboat"],
		["boiler", "tool", "steam engine"],
		["boiler", "wheel", "steam engine"],
		["bone", "bone", "skeleton"],
		["chicken", "bone", "chicken wing"],
		["bone", "light", "x-ray"],
		["wolf", "bone", "dog"],
		["book", "house", "library"],
		["book", "recipe", "cookbook"],
		["cheese", "bread", "sandwich"],
		["bread", "fire", "toast"],
		["bread", "ham", "sandwich"],
		["house", "bread", "bakery"],
		["human", "bread", "baker"],
		["meat", "bread", "hamburger"],
		["time", "bread", "mold"],
		["brick", "brick", "wall"],
		["campfire", "brick", "fireplace"],
		["fireplace", "brick", "chimney"],
		["human", "brick", "house"],
		["smoke", "brick", "chimney"],
		["tool", "brick", "house"],
		["electricity", "broom", "vacuum cleaner"],
		["human", "broom", "witch"],
		["wizard", "broom", "witch"],
		["metal", "bullet", "gun"],
		["cow", "butcher", "meat"],
		["livestock", "butcher", "meat"],
		["pig", "butcher", "meat"],
		["butterfly", "moon", "moth"],
		["butterfly", "night", "moth"],
		["sand", "cactus", "desert"],
		["campfire", "fabric", "smoke signal"],
		["campfire", "garden", "bbq"],
		["house", "campfire", "fireplace"],
		["human", "campfire", "story"],
		["campfire", "meat", "bbq"],
		["sugar", "campfire", "marshmallows"],
		["campfire", "wall", "fireplace"],
		["campfire", "witch", "cauldron"],
		["dough", "candle", "cake"],
		["pumpkin", "candle", "jack-o'-lantern"],
		["car", "car", "bus"],
		["doctor", "car", "ambulance"],
		["car", "electricity", "electric car"],
		["farmer", "car", "tractor"],
		["field", "car", "tractor"],
		["fireman", "car", "firetruck"],
		["car", "gun", "tank"],
		["hospital", "car", "ambulance"],
		["house", "car", "rv"],
		["car", "ice cream", "ice cream truck"],
		["snow", "car", "snowmobile"],
		["caramel", "chocolate", "Caramelo"],
		["caramel", "orchard", "Caramel Apple"],
		["Caramelo", "cookie", "Twix"],
		["carbon dioxide", "cold", "dry ice"],
		["fire", "carbon dioxide", "fire extinguisher"],
		["ice", "carbon dioxide", "dry ice"],
		["juice", "carbon dioxide", "soda"],
		["metal", "carbon dioxide", "fire extinguisher"],
		["plant", "carbon dioxide", "oxygen"],
		["pressure", "carbon dioxide", "fire extinguisher"],
		["water", "carbon dioxide", "soda"],
		["snow", "carrot", "snowman"],
		["snowball", "carrot", "snowman"],
		["carrot", "wild animal", "rabbit"],
		["cart", "horse", "wagon"],
		["cart", "mountain", "roller coaster"],
		["snow", "cart", "sledge"],
		["gunpowder", "castle", "cannon"],
		["human", "castle", "monarch"],
		["castle", "night", "ghost"],
		["sand", "castle", "sand castle"],
		["story", "castle", "fairy tale"],
		["time", "castle", "ruins"],
		["cat", "music", "Keyboard Cat"],
		["cat", "plant", "catnip"],
		["wild animal", "cat", "lion"],
		["caviar", "seaweed", "sushi"],
		["human", "chainsaw", "lumberjack"],
		["wood", "charcoal", "pencil"],
		["cheese", "dough", "pizza"],
		["cheese", "fish", "Goldfish"],
		["cheese", "hamburger", "cheeseburger"],
		["metal", "cheese", "mousetrap"],
		["cheese", "pasta", "mac and cheese"],
		["sky", "cheese", "moon"],
		["cheese", "toast", "grilled cheese"],
		["cheese", "wild animal", "mouse"],
		["wood", "cheese", "mousetrap"],
		["chicken", "sugar", "Peeps"],
		["water", "chicken", "chicken soup"],
		["chicken", "wild animal", "fox"],
		["santa", "chimney", "gift"],
		["chocolate", "coconut", "Mounds"],
		["chocolate", "egg", "Cadbury Eggs"],
		["chocolate", "milk", "chocolate milk"],
		["santa", "christmas stocking", "gift"],
		["christmas tree", "glass", "snow globe"],
		["human", "christmas tree", "santa"],
		["santa", "christmas tree", "gift"],
		["sugar", "christmas tree", "candy cane"],
		["dinosaur", "city", "godzilla"],
		["fog", "city", "smog"],
		["clay", "fire", "brick"],
		["fire", "clay", "pottery"],
		["clay", "life", "golem"],
		["clay", "oil", "oil lamp"],
		["clay", "sun", "brick"],
		["clay", "tool", "pottery"],
		["clay", "wheel", "pottery"],
		["egg", "clock", "egg timer"],
		["human", "clock", "watch"],
		["clock", "sound", "alarm clock"],
		["clock", "sun", "sundial"],
		["earth", "cloud", "fog"],
		["cloud", "electricity", "storm"],
		["energy", "cloud", "storm"],
		["ice", "cloud", "hail"],
		["cloud", "livestock", "sheep"],
		["plant", "cloud", "cotton"],
		["cloud", "sugar", "cotton candy"],
		["cloud", "water", "rain"],
		["metal", "coal", "steel"],
		["pressure", "coal", "diamond"],
		["coal", "time", "diamond"],
		["wood", "coal", "pencil"],
		["milk", "coconut", "coconut milk"],
		["coconut", "tool", "coconut milk"],
		["coffin", "earth", "grave"],
		["electricity", "cold", "fridge"],
		["juice", "cold", "popsicle"],
		["metal", "cold", "fridge"],
		["milk", "cold", "ice cream"],
		["rain", "cold", "snow"],
		["steam", "cold", "snow"],
		["cold", "tea", "iced tea"],
		["water", "cold", "ice"],
		["cold", "yogurt", "frozen yogurt"],
		["computer", "computer", "internet"],
		["computer", "dog", "Doge"],
		["letter", "computer", "email"],
		["mouse", "computer", "computer mouse"],
		["paper", "computer", "printer"],
		["computer", "squirrel", "Pokki"],
		["computer", "web", "internet"],
		["computer", "wire", "internet"],
		["confetti", "sugar", "sprinkles"],
		["cookie", "dough", "cookie dough"],
		["paper", "cookie", "fortune cookie"],
		["santa", "cookie", "gift"],
		["corpse", "earth", "grave"],
		["electricity", "corpse", "frankenstein"],
		["corpse", "life", "zombie"],
		["corpse", "pyramid", "mummy"],
		["corpse", "scythe", "grim reaper"],
		["corpse", "time", "bone"],
		["corpse", "time", "skeleton"],
		["wood", "corpse", "coffin"],
		["cotton", "fabric", "pillow"],
		["cotton", "tool", "thread"],
		["farmer", "cow", "milk"],
		["fire", "cow", "steak"],
		["cow", "house", "barn"],
		["cow", "human", "milk"],
		["human", "cow", "minotaur"],
		["cow", "mountain", "yak"],
		["cow", "rope", "lasso"],
		["cow", "sea", "manatee"],
		["cow", "tool", "meat"],
		["crown", "human", "monarch"],
		["snow", "crystal ball", "snow globe"],
		["river", "dam", "lake"],
		["wild animal", "dam", "beaver"],
		["day", "night", "twilight"],
		["time", "day", "night"],
		["day", "vampire", "dust"],
		["desert", "grave", "pyramid"],
		["desert", "horse", "camel"],
		["ice", "desert", "antarctica"],
		["livestock", "desert", "camel"],
		["desert", "palm", "oasis"],
		["desert", "plant", "cactus"],
		["snow", "desert", "antarctica"],
		["desert", "stone", "pyramid"],
		["tree", "desert", "oasis"],
		["desert", "water", "oasis"],
		["desert", "wild animal", "camel"],
		["desert", "wind", "dune"],
		["diamond", "gold", "ring"],
		["diamond", "metal", "ring"],
		["diamond", "sugar", "Ring Pop"],
		["dinosaur", "earth", "fossil"],
		["meat", "dinosaur", "tyrannosaurus rex"],
		["stone", "dinosaur", "fossil"],
		["dinosaur", "time", "fossil"],
		["house", "doctor", "hospital"],
		["doctor", "mold", "penicillin"],
		["doctor", "Tardis", "The Doctor"],
		["tool", "doctor", "stethoscope"],
		["dog", "forest", "wolf"],
		["dog", "house", "doghouse"],
		["dog", "ice", "husky"],
		["dog", "internet", "Doge"],
		["dog", "sea", "seal"],
		["dog", "snow", "husky"],
		["wild animal", "dog", "wolf"],
		["double rainbow!", "horse", "unicorn"],
		["double rainbow!", "life", "unicorn"],
		["dough", "fire", "bread"],
		["dough", "fruit", "pie"],
		["house", "dough", "gingerbread house"],
		["human", "dough", "baker"],
		["life", "dough", "gingerbread man"],
		["dough", "oil", "donut"],
		["dough", "sugar", "cookie"],
		["knight", "dragon", "hero"],
		["dragon", "story", "fairy tale"],
		["egg", "duck", "duckling"],
		["time", "duckling", "duck"],
		["wild animal", "dune", "scorpion"],
		["fire", "dust", "gunpowder"],
		["human", "dust", "allergy"],
		["earth", "earth", "pressure"],
		["earthquake", "earth", "mountain"],
		["earth", "energy", "earthquake"],
		["earth", "farmer", "field"],
		["earth", "fire", "lava"],
		["lava", "earth", "volcano"],
		["earth", "life", "human"],
		["paper", "earth", "map"],
		["plant", "earth", "grass"],
		["rain", "earth", "plant"],
		["sky", "earth", "horizon"],
		["earth", "space", "planet"],
		["steam", "earth", "geyser"],
		["earth", "tool", "field"],
		["water", "earth", "mud"],
		["earth", "wave", "earthquake"],
		["ocean", "earthquake", "tsunami"],
		["sea", "earthquake", "tsunami"],
		["egg", "fire", "omelette"],
		["flour", "egg", "pasta"],
		["egg", "hay", "nest"],
		["egg", "livestock", "chicken"],
		["egg", "ocean", "hard roe"],
		["egg", "oil", "mayonnaise"],
		["egg", "pond", "hard roe"],
		["egg", "sand", "turtle"],
		["egg", "sea", "hard roe"],
		["egg", "sky", "bird"],
		["egg", "swamp", "lizard"],
		["egg", "watch", "egg timer"],
		["egg", "water", "hard roe"],
		["fish", "electricity", "electric eel"],
		["electricity", "flashlight", "light"],
		["electricity", "glass", "light bulb"],
		["gun", "electricity", "taser"],
		["human", "electricity", "electrician"],
		["light bulb", "electricity", "light"],
		["electricity", "metal", "wire"],
		["electricity", "needle", "sewing machine"],
		["electricity", "nerd", "computer"],
		["electricity", "oxygen", "ozone"],
		["sand", "electricity", "glass"],
		["electricity", "scythe", "lawn mower"],
		["electricity", "sugar", "cotton candy"],
		["electricity", "sword", "lightsaber"],
		["time", "electricity", "clock"],
		["windmill", "electricity", "wind turbine"],
		["zombie", "electricity", "frankenstein"],
		["energy", "explosion", "atomic bomb"],
		["fruit", "energy", "sugar"],
		["human", "energy", "wizard"],
		["juice", "energy", "sugar"],
		["metal", "energy", "electricity"],
		["energy", "milk", "butter"],
		["sand", "energy", "sandstorm"],
		["energy", "snow", "avalanche"],
		["swamp", "energy", "life"],
		["energy", "sword", "lightsaber"],
		["volcano", "energy", "ash"],
		["volcano", "energy", "eruption"],
		["water", "energy", "steam"],
		["wind", "energy", "hurricane"],
		["engineer", "glasses", "safety glasses"],
		["engineer", "mountain", "tunnel"],
		["engineer", "paper", "blueprint"],
		["engineer", "sugar", "Willy Wonka"],
		["excalibur", "human", "monarch"],
		["explosion", "glasses", "safety glasses"],
		["explosion", "metal", "grenade"],
		["explosion", "sky", "fireworks"],
		["explosion", "star", "super nova"],
		["explosion", "stone", "Pop Rocks"],
		["fabric", "hero", "cape"],
		["fabric", "house", "tent"],
		["fabric", "mountain goat", "cashmere"],
		["fabric", "pilot", "parachute"],
		["rain", "fabric", "umbrella"],
		["fabric", "smoke", "smoke signal"],
		["fabric", "wood", "tent"],
		["tree", "family", "family tree"],
		["field", "farmer", "wheat"],
		["farmer", "grass", "hay"],
		["farmer", "house", "farm"],
		["farmer", "life", "livestock"],
		["plant", "farmer", "wheat"],
		["tree", "farmer", "fruit"],
		["farmer", "wild animal", "livestock"],
		["leaf", "fence", "hedge"],
		["plant", "fence", "hedge"],
		["field", "fruit tree", "orchard"],
		["field", "fruit", "vegetable"],
		["field", "human", "farmer"],
		["fire", "gun", "flamethrower"],
		["gunpowder", "fire", "explosion"],
		["human", "fire", "fireman"],
		["fire", "ice", "water"],
		["jedi", "fire", "darth vader"],
		["juice", "fire", "sugar"],
		["lizard", "fire", "dragon"],
		["fire", "mountain", "volcano"],
		["mud", "fire", "brick"],
		["fire", "ocean", "salt"],
		["fire", "oil", "oil lamp"],
		["pig", "fire", "bacon"],
		["plant", "fire", "tobacco"],
		["pumpkin", "fire", "jack-o'-lantern"],
		["fire", "sand", "glass"],
		["sandwich", "fire", "toast"],
		["fire", "sea", "salt"],
		["fire", "sky", "sun"],
		["fire", "stone", "metal"],
		["sugar", "fire", "caramel"],
		["tree", "fire", "charcoal"],
		["vegetable", "fire", "pumpkin"],
		["water", "fire", "steam"],
		["wax", "fire", "candle"],
		["fire", "wood", "campfire"],
		["wood", "fire", "charcoal"],
		["fire", "wood", "smoke"],
		["house", "fireplace", "chimney"],
		["santa", "fireplace", "gift"],
		["fireplace", "witch", "cauldron"],
		["wool", "fireplace", "christmas stocking"],
		["human", "firetruck", "fireman"],
		["fish", "fish", "hard roe"],
		["fish", "french fries", "fish and chips"],
		["glass", "fish", "aquarium"],
		["fish", "horse", "seahorse"],
		["human", "fish", "mermaid"],
		["fish", "seaweed", "sushi"],
		["sky", "fish", "flying fish"],
		["fish", "star", "starfish"],
		["fish", "sugar", "Swedish Fish"],
		["fish", "sword", "swordfish"],
		["tool", "fish", "fishing rod"],
		["wood", "fish", "fishing rod"],
		["human", "fishing rod", "angler"],
		["snowman", "flamethrower", "puddle"],
		["human", "flour", "baker"],
		["flour", "milk", "batter"],
		["flour", "paper", "recipe"],
		["water", "flour", "dough"],
		["flower", "flower", "garden"],
		["flower", "love", "rose"],
		["flower", "pond", "water lily"],
		["pottery", "flower", "vase"],
		["flower", "steam", "perfume"],
		["flower", "sun", "sunflower"],
		["flower", "water", "perfume"],
		["flower", "wild animal", "bee"],
		["flower", "wild animal", "butterfly"],
		["human", "flute", "music"],
		["fog", "grass", "dew"],
		["smoke", "fog", "smog"],
		["forest", "life", "wild animal"],
		["pig", "forest", "wild boar"],
		["fossil", "pressure", "petroleum"],
		["fossil", "time", "petroleum"],
		["fruit tree", "fruit tree", "orchard"],
		["fruit", "juice", "Juicy Fruit"],
		["fruit", "monkey", "banana"],
		["palm", "fruit", "coconut"],
		["pressure", "fruit", "juice"],
		["fruit", "rocket", "Starburst"],
		["fruit", "time", "alcohol"],
		["fruit", "tree", "fruit tree"],
		["water", "fruit", "juice"],
		["fruit", "water", "lemonade"],
		["human", "garden", "gardener"],
		["plant", "garden", "flower"],
		["garden", "statue", "gnome"],
		["water", "garden", "pond"],
		["gift", "paper", "wrapping paper"],
		["house", "gingerbread man", "gingerbread house"],
		["glass", "glass", "glasses"],
		["glass", "house", "window"],
		["glass", "metal", "glasses"],
		["glass", "metal", "mirror"],
		["glass", "oil", "oil lamp"],
		["plant", "glass", "greenhouse"],
		["glass", "rainbow", "prism"],
		["sand", "glass", "hourglass"],
		["sand", "glass", "time"],
		["glass", "sky", "telescope"],
		["glass", "snow", "snow globe"],
		["glass", "snowman", "snow globe"],
		["glass", "space", "telescope"],
		["glass", "star", "telescope"],
		["water", "glass", "aquarium"],
		["witch", "glass", "crystal ball"],
		["wizard", "glass", "crystal ball"],
		["human", "glasses", "nerd"],
		["glasses", "snow", "ski goggles"],
		["sun", "glasses", "sunglasses"],
		["tool", "glasses", "safety glasses"],
		["glasses", "water", "swim goggles"],
		["goat", "human", "faun"],
		["goat", "mountain range", "mountain goat"],
		["mountain", "goat", "mountain goat"],
		["house", "gold", "bank"],
		["gold", "metal", "safe"],
		["gold", "monarch", "crown"],
		["paper", "gold", "money"],
		["gold", "steel", "safe"],
		["house", "grass", "garden"],
		["grass", "livestock", "cow"],
		["mud", "grass", "swamp"],
		["plant", "grass", "garden"],
		["grass", "sandwich", "picnic"],
		["grass", "scythe", "hay"],
		["grass", "sun", "hay"],
		["grass", "tool", "lawn mower"],
		["water", "grass", "dew"],
		["grass", "wild animal", "ant"],
		["grave", "grave", "graveyard"],
		["grave", "stone", "gravestone"],
		["gravestone", "gravestone", "graveyard"],
		["graveyard", "night", "ghost"],
		["human", "grim reaper", "corpse"],
		["human", "gun", "corpse"],
		["gun", "sword", "bayonet"],
		["water", "gun", "water gun"],
		["gunpowder", "metal", "bullet"],
		["gunpowder", "pirate ship", "cannon"],
		["gunpowder", "wire", "dynamite"],
		["hard roe", "human", "caviar"],
		["hard roe", "time", "fish"],
		["hay", "hay", "hay bale"],
		["house", "hay", "barn"],
		["human", "hay", "scarecrow"],
		["hay", "livestock", "horse"],
		["metal", "hay", "needle"],
		["tool", "hay", "pitchfork"],
		["wood", "hay", "broom"],
		["horse", "human", "centaur"],
		["horse", "leather", "saddle"],
		["metal", "horse", "horseshoe"],
		["ocean", "horse", "seahorse"],
		["rainbow", "horse", "unicorn"],
		["horse", "river", "hippo"],
		["horse", "rope", "lasso"],
		["horse", "sea", "seahorse"],
		["sky", "horse", "pegasus"],
		["horse", "water", "hippo"],
		["horse", "wood", "trojan horse"],
		["human", "hospital", "doctor"],
		["house", "house", "village"],
		["human", "house", "family"],
		["house", "ice", "igloo"],
		["house", "knight", "castle"],
		["light", "house", "lighthouse"],
		["livestock", "house", "barn"],
		["house", "money", "bank"],
		["house", "safe", "bank"],
		["house", "sickness", "hospital"],
		["house", "sky", "skyscraper"],
		["house", "snow", "igloo"],
		["space", "house", "space station"],
		["time", "house", "ruins"],
		["tree", "house", "treehouse"],
		["house", "wind", "windmill"],
		["wood", "house", "log cabin"],
		["human", "human", "love"],
		["human", "letter", "mailman"],
		["human", "light bulb", "idea"],
		["lightsaber", "human", "jedi"],
		["human", "lion", "sphinx"],
		["human", "meat", "butcher"],
		["human", "medusa", "statue"],
		["metal", "human", "tool"],
		["human", "moon", "astronaut"],
		["human", "oxygen", "carbon dioxide"],
		["human", "pitchfork", "farmer"],
		["human", "plant", "farmer"],
		["human", "rain", "cold"],
		["human", "rain", "sickness"],
		["human", "robot", "cyborg"],
		["rocket", "human", "astronaut"],
		["human", "sailboat", "sailor"],
		["human", "scythe", "grim reaper"],
		["seaplane", "human", "pilot"],
		["shuriken", "human", "ninja"],
		["human", "sickness", "sickness"],
		["human", "snake", "medusa"],
		["snow", "human", "snowball"],
		["snow", "human", "snowman"],
		["human", "sound", "music"],
		["human", "space station", "astronaut"],
		["human", "space", "astronaut"],
		["human", "swim goggles", "swimmer"],
		["sword", "human", "warrior"],
		["human", "tool", "engineer"],
		["human", "vampire", "vampire"],
		["human", "wave", "surfer"],
		["werewolf", "human", "werewolf"],
		["wild animal", "human", "dog"],
		["wild animal", "human", "livestock"],
		["human", "wine", "drunk"],
		["human", "wire", "electrician"],
		["wolf", "human", "werewolf"],
		["wood", "human", "house"],
		["human", "wool", "sweater"],
		["human", "zombie", "zombie"],
		["sand", "hurricane", "sandstorm"],
		["milk", "ice cream", "milk shake"],
		["juice", "ice", "popsicle"],
		["metal", "ice", "fridge"],
		["milk", "ice", "ice cream"],
		["ice", "mountain", "glacier"],
		["ocean", "ice", "iceberg"],
		["rain", "ice", "hail"],
		["sea", "ice", "iceberg"],
		["ice", "storm", "hail"],
		["sun", "ice", "puddle"],
		["ice", "tea", "iced tea"],
		["ice", "wild animal", "penguin"],
		["ice", "yogurt", "frozen yogurt"],
		["steamboat", "iceberg", "titanic"],
		["letter", "internet", "email"],
		["isle", "isle", "archipelago"],
		["isle", "tree", "palm"],
		["jedi", "lava", "darth vader"],
		["jedi", "swamp", "yoda"],
		["juice", "sugar", "jam"],
		["juice", "time", "alcohol"],
		["knight", "lightsaber", "jedi"],
		["knight", "story", "fairy tale"],
		["knight", "windmill", "Don Quixote"],
		["lake", "story", "Nessie"],
		["lava", "lamp", "lava lamp"],
		["lava", "mountain", "volcano"],
		["lava", "pressure", "granite"],
		["lava", "water", "obsidian"],
		["leaf", "sickness", "herb"],
		["water", "leaf", "tea"],
		["leather", "money", "wallet"],
		["wood", "leather", "drum"],
		["metal", "life", "robot"],
		["ocean", "life", "plankton"],
		["rainbow", "life", "unicorn"],
		["sea", "life", "plankton"],
		["life", "sky", "bird"],
		["life", "space", "alien"],
		["steel", "life", "robot"],
		["life", "stone", "egg"],
		["swamp", "life", "bacteria"],
		["water", "life", "plankton"],
		["wood", "life", "pinocchio"],
		["metal", "light bulb", "lamp"],
		["light bulb", "nerd", "idea"],
		["light bulb", "tree", "christmas tree"],
		["light", "ocean", "lighthouse"],
		["rain", "light", "rainbow"],
		["light", "sea", "lighthouse"],
		["light", "skeleton", "x-ray"],
		["light", "solar cell", "electricity"],
		["light", "sword", "lightsaber"],
		["tool", "light", "flashlight"],
		["vegetable", "light", "pumpkin"],
		["wire", "light", "optical fiber"],
		["livestock", "mountain", "goat"],
		["livestock", "mud", "pig"],
		["livestock", "santa", "reindeer"],
		["lizard", "lizard", "egg"],
		["lizard", "rainbow", "chameleon"],
		["lizard", "river", "alligator"],
		["lizard", "swamp", "alligator"],
		["lizard", "time", "dinosaur"],
		["plant", "love", "rose"],
		["love", "sugar", "Sweethearts"],
		["love", "time", "life"],
		["pirate", "map", "treasure map"],
		["meat", "salt", "jerky"],
		["meat", "smoke", "ham"],
		["meat", "sun", "jerky"],
		["metal", "monarch", "crown"],
		["metal", "money", "safe"],
		["metal", "oxygen", "rust"],
		["metal", "rainbow", "gold"],
		["river", "metal", "bridge"],
		["metal", "rope", "chain"],
		["steam engine", "metal", "train"],
		["steam", "metal", "boiler"],
		["metal", "stone", "blade"],
		["metal", "sun", "gold"],
		["metal", "thread", "needle"],
		["tool", "metal", "armor"],
		["wheel", "metal", "car"],
		["metal", "witch", "cauldron"],
		["metal", "wood", "hammer"],
		["sky", "meteoroid", "meteor"],
		["milk", "pressure", "butter"],
		["milk", "space", "Milky Way"],
		["time", "milk", "cheese"],
		["wheat", "milk", "cereal"],
		["wild animal", "milk", "cat"],
		["story", "monarch", "fairy tale"],
		["pig", "money", "piggy bank"],
		["money", "steel", "safe"],
		["ocean", "moon", "tide"],
		["sea", "moon", "tide"],
		["sky", "moon", "night"],
		["moon", "star", "space"],
		["sun", "moon", "eclipse"],
		["moon", "time", "night"],
		["wild animal", "moon", "wolf"],
		["snow", "motorcycle", "snowmobile"],
		["mountain goat", "scissors", "cashmere"],
		["mountain goat", "thread", "cashmere"],
		["mountain goat", "tool", "cashmere"],
		["mountain goat", "wool", "cashmere"],
		["mountain range", "story", "Yeti"],
		["mountain", "mountain", "mountain range"],
		["rain", "mountain", "river"],
		["mountain", "river", "waterfall"],
		["mountain", "sheep", "alpaca"],
		["mountain", "story", "Yeti"],
		["mountain", "train", "roller coaster"],
		["mountain", "water", "river"],
		["mouse", "sky", "bat"],
		["mouse", "tree", "squirrel"],
		["wheel", "mouse", "hamster"],
		["mud", "plant", "swamp"],
		["sand", "mud", "clay"],
		["mud", "sun", "brick"],
		["paper", "music", "sheet music"],
		["needle", "robot", "sewing machine"],
		["nerd", "sugar", "Nerds"],
		["tool", "nerd", "computer"],
		["wire", "nerd", "computer"],
		["plant", "night", "carbon dioxide"],
		["sky", "night", "star"],
		["night", "sun", "day"],
		["night", "telescope", "star"],
		["time", "night", "day"],
		["tree", "night", "carbon dioxide"],
		["ninja", "turtle", "Ninja Turtle"],
		["ocean", "plant", "algae"],
		["plant", "ocean", "seaweed"],
		["ocean", "sand", "beach"],
		["sickness", "ocean", "seasickness"],
		["ocean", "sky", "horizon"],
		["ocean", "star", "starfish"],
		["ocean", "sun", "salt"],
		["unicorn", "ocean", "narwhal"],
		["ocean", "volcano", "isle"],
		["ocean", "wild animal", "shark"],
		["ocean", "wind", "wave"],
		["oil", "pottery", "oil lamp"],
		["oil", "rope", "oil lamp"],
		["oil", "vegetable", "french fries"],
		["oxygen", "oxygen", "ozone"],
		["steel", "oxygen", "rust"],
		["oxygen", "wine", "vinegar"],
		["paper", "paper", "newspaper"],
		["paper", "pencil", "letter"],
		["sand", "paper", "sandpaper"],
		["paper", "scissors", "confetti"],
		["sky", "paper", "kite"],
		["paper", "story", "book"],
		["tobacco", "paper", "cigarette"],
		["wind", "paper", "kite"],
		["paper", "wood", "book"],
		["pasta", "thread", "spaghetti"],
		["pencil", "rainbow", "crayon"],
		["water", "pencil", "paint"],
		["wood", "pencil", "ruler"],
		["pottery", "pig", "piggy bank"],
		["pig", "tool", "meat"],
		["pig", "wild animal", "wild boar"],
		["pilot", "umbrella", "parachute"],
		["water", "pipe", "water pipe"],
		["sailor", "pirate ship", "pirate"],
		["wild animal", "pirate ship", "rat"],
		["sailboat", "pirate", "pirate ship"],
		["pirate", "treasure map", "treasure"],
		["planet", "ring", "saturn"],
		["rust", "planet", "mars"],
		["sun", "planet", "solar system"],
		["plant", "plant", "garden"],
		["plant", "pottery", "vase"],
		["pressure", "plant", "coal"],
		["sand", "plant", "cactus"],
		["sea", "plant", "algae"],
		["plant", "sea", "seaweed"],
		["plant", "sickness", "herb"],
		["plant", "stone", "moss"],
		["plant", "sun", "energy"],
		["plant", "sun", "oxygen"],
		["plant", "sun", "sunflower"],
		["plant", "time", "tree"],
		["plant", "wall", "ivy"],
		["water", "plant", "algae"],
		["water", "pond", "lake"],
		["wild animal", "pond", "frog"],
		["tree", "pottery", "bonsai tree"],
		["sky", "pressure", "atmosphere"],
		["star", "pressure", "black hole"],
		["sunflower", "pressure", "oil"],
		["wood", "pressure", "paper"],
		["rain", "rain", "flood"],
		["rain", "smog", "acid rain"],
		["rain", "smoke", "acid rain"],
		["rain", "sun", "rainbow"],
		["rain", "time", "flood"],
		["tool", "rain", "umbrella"],
		["rainbow", "rainbow", "double rainbow!"],
		["rainbow", "sugar", "Skittles"],
		["water", "rainbow", "paint"],
		["rainbow", "wax", "crayon"],
		["ring", "volcano", "The One Ring"],
		["river", "steel", "bridge"],
		["wall", "river", "dam"],
		["river", "wheel", "waterwheel"],
		["river", "Willy Wonka", "chocolate"],
		["river", "wood", "bridge"],
		["robot", "vacuum cleaner", "roomba"],
		["rope", "steel", "chain"],
		["rose", "steam", "perfume"],
		["rose", "water", "perfume"],
		["sailboat", "sickness", "seasickness"],
		["sailboat", "wild animal", "rat"],
		["sword", "sailor", "pirate"],
		["sand", "sand", "desert"],
		["sea", "sand", "beach"],
		["stone", "sand", "sandstone"],
		["sand", "storm", "sandstorm"],
		["sand", "sugar", "Fun Dip"],
		["sand", "swamp", "quicksand"],
		["water", "sand", "beach"],
		["wild animal", "sand", "scorpion"],
		["sand", "wind", "dune"],
		["santa", "wild animal", "reindeer"],
		["scissors", "sheep", "wool"],
		["tree", "scissors", "bonsai tree"],
		["sea", "sea", "ocean"],
		["sickness", "sea", "seasickness"],
		["sea", "sky", "horizon"],
		["sea", "star", "starfish"],
		["sea", "sun", "salt"],
		["sea", "unicorn", "narwhal"],
		["volcano", "sea", "isle"],
		["water", "sea", "ocean"],
		["sea", "wild animal", "shark"],
		["sea", "wind", "wave"],
		["sheep", "tool", "wool"],
		["steamboat", "sickness", "seasickness"],
		["sky", "squirrel", "flying squirrel"],
		["sky", "star", "space"],
		["sky", "stone", "moon"],
		["sky", "sun", "day"],
		["skyscraper", "skyscraper", "city"],
		["snow", "snow", "blizzard"],
		["snow", "storm", "blizzard"],
		["snow", "surfer", "snowboard"],
		["snow", "wagon", "sledge"],
		["snow", "wind", "blizzard"],
		["wood", "snow", "snowboard"],
		["snowball", "snowball", "snowman"],
		["snowboard", "wheel", "skateboard"],
		["sun", "snowman", "carrot"],
		["sun", "snowman", "coal"],
		["sun", "snowman", "puddle"],
		["snowman", "vegetable", "carrot"],
		["soap", "water", "soap bubble"],
		["solar cell", "sun", "electricity"],
		["stone", "space", "meteoroid"],
		["space", "time", "Tardis"],
		["spider", "thread", "web"],
		["squirrel", "tree", "nut"],
		["squirrel", "wind", "flying squirrel"],
		["star", "star", "constellation"],
		["star", "star", "galaxy"],
		["sun", "star", "space"],
		["tree", "star", "christmas tree"],
		["statue", "water", "fountain"],
		["steam engine", "steel", "train"],
		["steam engine", "wagon", "train"],
		["steam engine", "water", "steamboat"],
		["steam engine", "wheel", "train"],
		["tool", "steel", "armor"],
		["steel", "witch", "cauldron"],
		["steel", "wool", "steel wool"],
		["sword", "stone", "excalibur"],
		["stone", "tool", "statue"],
		["wheat", "stone", "flour"],
		["wind", "stone", "sand"],
		["wild animal", "sugar", "ant"],
		["sugar", "wire", "Red Vines"],
		["sun", "time", "day"],
		["sun", "tool", "solar cell"],
		["sun", "tree", "fruit"],
		["sun", "vampire", "dust"],
		["thread", "thread", "rope"],
		["thread", "tool", "fabric"],
		["wax", "thread", "candle"],
		["wild animal", "thread", "spider"],
		["time", "tool", "clock"],
		["time", "wheel", "clock"],
		["wild animal", "time", "sloth"],
		["time", "wine", "vinegar"],
		["tobacco", "wood", "pipe"],
		["tool", "tree", "wood"],
		["tool", "wood", "wheel"],
		["wool", "tool", "sweater"],
		["tree", "tree", "forest"],
		["tree", "wild animal", "monkey"],
		["tree", "wind", "leaf"],
		["turtle", "turtle", "egg"],
		["unicorn", "water", "narwhal"],
		["village", "village", "city"],
		["wall", "wall", "house"],
		["wall", "wood", "fence"],
		["water", "water", "sea"],
		["water", "wheel", "waterwheel"],
		["water", "wood", "boat"],
		["waterwheel", "wheat", "flour"],
		["windmill", "wheat", "flour"],
		["wheel", "wheel", "bicycle"],
		["wheel", "wind", "windmill"],
		["wheel", "wood", "cart"],
		["wheel", "wool", "thread"],
		["wild animal", "wire", "snake"],
		["wild animal", "wood", "beaver"],
		["wind turbine", "wind", "electricity"],
		["wood", "wind", "flute"],
		["wire", "wool", "steel wool"],
		["wizard", "wood", "wand"]
	]
};

const elementNameByLower = new Map();
for (const element of DATA.elements) {
	elementNameByLower.set(element.toLowerCase(), element);
}
const recipeIndex = buildRecipeIndex(DATA.recipes);
const unlocked = new Set(DATA.baseElements.map(toCanonicalName));
const form = document.getElementById("combine-form");
const firstSelect = document.getElementById("first-element");
const secondSelect = document.getElementById("second-element");
const resultText = document.getElementById("result-text");
const totalCount = document.getElementById("total-count");
const copySaveButton = document.getElementById("copy-save-button");
const importSaveButton = document.getElementById("import-save-button");
const clearSaveButton = document.getElementById("clear-save-button");
const saveDataInput = document.getElementById("save-data-input");
const SAVE_KEY = "alchemist-save-v1";
const SAVE_INTERVAL_MS = 2000;

function toCanonicalName(name) {
	const normalized = name.toLowerCase();
	return elementNameByLower.get(normalized) || name;
}

function buildRecipeIndex(recipes) {
	const index = new Map();
	for (const recipe of recipes) {
		const first = toCanonicalName(recipe[0]);
		const second = toCanonicalName(recipe[1]);
		const result = toCanonicalName(recipe[2]);
		const key = toRecipeKey(first, second);
		const results = index.get(key) || [];
		if (!results.includes(result)) {
			results.push(result);
		}
		index.set(key, results);
	}
	return index;
}

function toRecipeKey(first, second) {
	return [first.toLowerCase(), second.toLowerCase()].sort().join("|");
}

function populateElementOptions() {
	const sorted = Array.from(unlocked).sort((a, b) => a.localeCompare(b));
	const firstValue = firstSelect.value;
	const secondValue = secondSelect.value;
	const html = sorted.map((element) => {
		return `<option value=\"${element}\">${element}</option>`;
	}).join("");
	firstSelect.innerHTML = html;
	secondSelect.innerHTML = html;
	if (firstValue && unlocked.has(firstValue)) {
		firstSelect.value = firstValue;
	}
	if (secondValue && unlocked.has(secondValue)) {
		secondSelect.value = secondValue;
	}
}

function combineSelectedElements() {
	const first = firstSelect.value;
	const second = secondSelect.value;
	const key = toRecipeKey(first, second);
	const results = recipeIndex.get(key);
	if (!results || results.length === 0) {
		resultText.textContent = `No recipe for ${first} + ${second}.`;
		return;
	}
	const newlyUnlocked = [];
	for (const result of results) {
		if (unlocked.has(result)) {
			continue;
		}
		unlocked.add(result);
		newlyUnlocked.push(result);
	}
	if (newlyUnlocked.length === 0) {
		resultText.textContent = `already unlocked ${results.join(", ")}.`;
		return;
	}
	populateElementOptions();
	renderInventory();
	resultText.textContent = `Unlocked ${newlyUnlocked.join(", ")}!`;
}

function renderInventory() {
	const total = DATA.elements.length;
	const count = unlocked.size;
	const percent = total === 0 ? 0 : (count / total) * 100;
	totalCount.textContent = `${count}/${total} elements unlocked (${percent.toFixed(1)}%)`;
}

function getSavePayload() {
	return {
		version: 1,
		unlocked: Array.from(unlocked).sort((a, b) => a.localeCompare(b))
	};
}

function encodeBase64(text) {
	const bytes = new TextEncoder().encode(text);
	let binary = "";
	for (const byte of bytes) {
		binary += String.fromCharCode(byte);
	}
	return btoa(binary);
}

function decodeBase64(encoded) {
	const binary = atob(encoded);
	const bytes = new Uint8Array(binary.length);
	for (let i = 0; i < binary.length; i += 1) {
		bytes[i] = binary.charCodeAt(i);
	}
	return new TextDecoder().decode(bytes);
}

function getEncodedSavePayload() {
	return encodeBase64(JSON.stringify(getSavePayload()));
}

function applySavePayload(payload) {
	if (!payload || !Array.isArray(payload.unlocked)) {
		return false;
	}
	unlocked.clear();
	for (const item of payload.unlocked) {
		const canonical = toCanonicalName(String(item));
		if (elementNameByLower.has(canonical.toLowerCase())) {
			unlocked.add(canonical);
		}
	}
	if (unlocked.size === 0) {
		for (const base of DATA.baseElements) {
			unlocked.add(toCanonicalName(base));
		}
	}
	return true;
}

function saveGame() {
	try {
		localStorage.setItem(SAVE_KEY, getEncodedSavePayload());
	} catch (error) {
	}
}

function loadGame() {
	try {
		const encoded = localStorage.getItem(SAVE_KEY);
		if (!encoded) {
			return;
		}
		const raw = decodeBase64(encoded);
		const parsed = JSON.parse(raw);
		if (!applySavePayload(parsed)) {
			return;
		}
	} catch (error) {
	}
}

async function copySaveDataToClipboard() {
	const encodedSave = getEncodedSavePayload();
	saveDataInput.value = encodedSave;
	try {
		await navigator.clipboard.writeText(encodedSave);
		resultText.textContent = "save data copied to clipboard.";
	} catch (error) {
		resultText.textContent = "could not copy save data.";
	}
}

function importSaveData() {
	const encoded = saveDataInput.value.trim();
	if (!encoded) {
		resultText.textContent = "could not import save data.";
		return;
	}
	try {
		const raw = decodeBase64(encoded);
		const parsed = JSON.parse(raw);
		const ok = applySavePayload(parsed);
		if (!ok) {
			resultText.textContent = "could not import save data.";
			return;
		}
		populateElementOptions();
		renderInventory();
		saveGame();
		resultText.textContent = "save data imported.";
	} catch (error) {
		resultText.textContent = "could not import save data.";
	}
}

function clearSaveData() {
	unlocked.clear();
	for (const base of DATA.baseElements) {
		unlocked.add(toCanonicalName(base));
	}
	saveDataInput.value = "";
	localStorage.removeItem(SAVE_KEY);
	populateElementOptions();
	renderInventory();
	resultText.textContent = "save data cleared.";
}

loadGame();
populateElementOptions();
renderInventory();
saveDataInput.value = getEncodedSavePayload();
saveGame();
setInterval(saveGame, SAVE_INTERVAL_MS);

form.addEventListener("submit", (event) => {
	event.preventDefault();
	combineSelectedElements();
});

function handleSelectEnterKey(event) {
	if (event.key !== "Enter") {
		return;
	}
	event.preventDefault();
	combineSelectedElements();
}

firstSelect.addEventListener("keydown", handleSelectEnterKey);
secondSelect.addEventListener("keydown", handleSelectEnterKey);

copySaveButton.addEventListener("click", () => {
	copySaveDataToClipboard();
});

importSaveButton.addEventListener("click", () => {
	importSaveData();
});

clearSaveButton.addEventListener("click", () => {
	clearSaveData();
});
