"use strict";

/*
	Stage 1: Little Alchemy 1 merged dataset.
	Stage 2: Little Alchemy 2 dataset.
*/
const STAGE_ONE = {
	baseElements: [
		"air",
		"earth",
		"fire",
		"water"
	],
	elements: [
		"acid rain",
		"air",
		"airplane",
		"alarm clock",
		"alcohol",
		"algae",
		"alien",
		"allergy",
		"alligator",
		"alpaca",
		"ambulance",
		"angel",
		"angler",
		"ant",
		"antarctica",
		"aquarium",
		"archipelago",
		"armadillo",
		"armor",
		"ash",
		"astronaut",
		"Astronaut Ice Cream",
		"atmosphere",
		"atomic bomb",
		"aurora",
		"avalanche",
		"axe",
		"bacon",
		"bacteria",
		"baker",
		"bakery",
		"banana",
		"banana bread",
		"bandage",
		"bank",
		"barn",
		"bat",
		"batman",
		"batter",
		"bayonet",
		"bbq",
		"beach",
		"beaver",
		"bee",
		"beehive",
		"beer",
		"bicycle",
		"bird",
		"birdhouse",
		"black hole",
		"blade",
		"blender",
		"blizzard",
		"blood",
		"blueprint",
		"boat",
		"boiler",
		"bone",
		"bonsai tree",
		"book",
		"bread",
		"brick",
		"bridge",
		"broom",
		"bullet",
		"bulletproof vest",
		"bus",
		"butcher",
		"butter",
		"butterfly",
		"cactus",
		"Cadbury Eggs",
		"cake",
		"camel",
		"campfire",
		"candle",
		"candy cane",
		"cannon",
		"cape",
		"car",
		"caramel",
		"Caramel Apple",
		"Caramelo",
		"carbon dioxide",
		"carrot",
		"cart",
		"cashmere",
		"castle",
		"cat",
		"catnip",
		"cauldron",
		"caviar",
		"centaur",
		"cereal",
		"chain",
		"chainsaw",
		"chameleon",
		"charcoal",
		"cheese",
		"cheeseburger",
		"chicken",
		"chicken soup",
		"chicken wing",
		"chimney",
		"chocolate",
		"chocolate milk",
		"christmas stocking",
		"christmas tree",
		"cigarette",
		"city",
		"clay",
		"clock",
		"cloud",
		"coal",
		"coconut",
		"coconut milk",
		"coffin",
		"cold",
		"computer",
		"computer mouse",
		"confetti",
		"constellation",
		"cookbook",
		"cookie",
		"cookie dough",
		"corpse",
		"cotton",
		"cotton candy",
		"cow",
		"crayon",
		"crow",
		"crown",
		"crystal ball",
		"cuckoo",
		"cyborg",
		"cyclist",
		"dam",
		"darth vader",
		"day",
		"desert",
		"dew",
		"diamond",
		"dinosaur",
		"doctor",
		"dog",
		"Doge",
		"doghouse",
		"Don Quixote",
		"donut",
		"double rainbow!",
		"dough",
		"dragon",
		"drone",
		"drum",
		"drunk",
		"dry ice",
		"duck",
		"duckling",
		"dune",
		"dust",
		"dynamite",
		"eagle",
		"earth",
		"earthquake",
		"eclipse",
		"egg",
		"egg timer",
		"electric car",
		"electric eel",
		"electrician",
		"electricity",
		"email",
		"energy",
		"engineer",
		"eruption",
		"excalibur",
		"explosion",
		"fabric",
		"fairy tale",
		"family",
		"family tree",
		"farm",
		"farmer",
		"faun",
		"fence",
		"field",
		"fire",
		"fire extinguisher",
		"fireman",
		"fireplace",
		"firetruck",
		"fireworks",
		"fish",
		"fish and chips",
		"fishing rod",
		"flamethrower",
		"flashlight",
		"flood",
		"flour",
		"flower",
		"flute",
		"flying fish",
		"flying squirrel",
		"fog",
		"forest",
		"fortune cookie",
		"fossil",
		"fountain",
		"fox",
		"frankenstein",
		"french fries",
		"fridge",
		"frog",
		"frozen yogurt",
		"fruit",
		"fruit tree",
		"Fun Dip",
		"galaxy",
		"garden",
		"gardener",
		"geyser",
		"ghost",
		"gift",
		"gingerbread house",
		"gingerbread man",
		"glacier",
		"glass",
		"glasses",
		"gnome",
		"goat",
		"godzilla",
		"gold",
		"Goldfish",
		"golem",
		"granite",
		"grass",
		"grave",
		"gravestone",
		"graveyard",
		"greenhouse",
		"grenade",
		"grilled cheese",
		"grim reaper",
		"Guinness Float",
		"gun",
		"gunpowder",
		"hail",
		"ham",
		"hamburger",
		"hammer",
		"hamster",
		"hard roe",
		"harp",
		"hay",
		"hay bale",
		"hedge",
		"helicopter",
		"herb",
		"hero",
		"hippo",
		"honey",
		"horizon",
		"horse",
		"horseshoe",
		"hospital",
		"hourglass",
		"house",
		"human",
		"hummingbird",
		"hurricane",
		"husky",
		"ice",
		"ice cream",
		"ice cream truck",
		"iceberg",
		"iced tea",
		"idea",
		"igloo",
		"internet",
		"isle",
		"ivy",
		"jack-o'-lantern",
		"jam",
		"jedi",
		"jerky",
		"juice",
		"Juicy Fruit",
		"Keyboard Cat",
		"kite",
		"knight",
		"lake",
		"lamp",
		"lasso",
		"lava",
		"lava lamp",
		"lawn mower",
		"leaf",
		"leather",
		"lemonade",
		"letter",
		"library",
		"life",
		"light",
		"light bulb",
		"lighthouse",
		"lightsaber",
		"lion",
		"livestock",
		"lizard",
		"log cabin",
		"love",
		"lumberjack",
		"mac and cheese",
		"mailman",
		"manatee",
		"map",
		"mars",
		"marshmallows",
		"mayonnaise",
		"meat",
		"medusa",
		"mermaid",
		"metal",
		"meteor",
		"meteoroid",
		"microscope",
		"milk",
		"milk shake",
		"Milky Way",
		"minotaur",
		"mirror",
		"mold",
		"monarch",
		"money",
		"monkey",
		"moon",
		"moss",
		"moth",
		"motorcycle",
		"Mounds",
		"mountain",
		"mountain goat",
		"mountain range",
		"mouse",
		"mousetrap",
		"mud",
		"mummy",
		"music",
		"narwhal",
		"needle",
		"nerd",
		"Nerds",
		"Nessie",
		"nest",
		"newspaper",
		"night",
		"ninja",
		"Ninja Turtle",
		"nut",
		"oasis",
		"obsidian",
		"ocean",
		"oil",
		"oil lamp",
		"omelette",
		"optical fiber",
		"orchard",
		"origami",
		"ostrich",
		"owl",
		"oxygen",
		"ozone",
		"paint",
		"palm",
		"paper",
		"paper airplane",
		"parachute",
		"parrot",
		"pasta",
		"peacock",
		"Peeps",
		"pegasus",
		"pencil",
		"pencil sharpener",
		"penguin",
		"penicillin",
		"perfume",
		"petroleum",
		"phoenix",
		"picnic",
		"pie",
		"pig",
		"pigeon",
		"piggy bank",
		"pillow",
		"pilot",
		"pinocchio",
		"pipe",
		"piranha",
		"pirate",
		"pirate ship",
		"pitchfork",
		"pizza",
		"planet",
		"plankton",
		"plant",
		"platypus",
		"Pokki",
		"pond",
		"Pop Rocks",
		"popsicle",
		"pottery",
		"pressure",
		"printer",
		"prism",
		"pterodactyl",
		"puddle",
		"pumpkin",
		"pyramid",
		"quicksand",
		"rabbit",
		"rain",
		"rainbow",
		"rat",
		"recipe",
		"Red Vines",
		"reindeer",
		"ring",
		"Ring Pop",
		"river",
		"robot",
		"rocket",
		"roller coaster",
		"roomba",
		"rope",
		"rose",
		"ruins",
		"ruler",
		"rust",
		"rv",
		"saddle",
		"safe",
		"safety glasses",
		"sailboat",
		"sailor",
		"salt",
		"sand",
		"sand castle",
		"sandpaper",
		"sandstone",
		"sandstorm",
		"sandwich",
		"santa",
		"saturn",
		"scalpel",
		"scarecrow",
		"scissors",
		"scorpion",
		"scythe",
		"sea",
		"seagull",
		"seahorse",
		"seal",
		"seaplane",
		"seasickness",
		"seaweed",
		"sewing machine",
		"shark",
		"sheep",
		"sheet music",
		"shuriken",
		"sickness",
		"skateboard",
		"skeleton",
		"ski goggles",
		"Skittles",
		"sky",
		"skyscraper",
		"sledge",
		"sloth",
		"smog",
		"smoke",
		"smoke signal",
		"smoothie",
		"snake",
		"snow",
		"snow globe",
		"snowball",
		"snowboard",
		"snowman",
		"snowmobile",
		"soap",
		"soap bubble",
		"soda",
		"solar cell",
		"solar system",
		"sound",
		"space",
		"space station",
		"spaceship",
		"spaghetti",
		"sphinx",
		"spider",
		"sprinkles",
		"squirrel",
		"star",
		"Starburst",
		"starfish",
		"statue",
		"steak",
		"steam",
		"steam engine",
		"steamboat",
		"steel",
		"steel wool",
		"stethoscope",
		"stone",
		"storm",
		"story",
		"sugar",
		"sun",
		"sundial",
		"sunflower",
		"sunglasses",
		"super nova",
		"surfer",
		"sushi",
		"swamp",
		"sweater",
		"Swedish Fish",
		"Sweethearts",
		"swim goggles",
		"swimmer",
		"sword",
		"swordfish",
		"tank",
		"Tardis",
		"taser",
		"tea",
		"telescope",
		"tent",
		"The Doctor",
		"The One Ring",
		"thread",
		"tide",
		"time",
		"titanic",
		"toast",
		"tobacco",
		"tool",
		"toucan",
		"tractor",
		"train",
		"treasure",
		"treasure map",
		"tree",
		"treehouse",
		"trojan horse",
		"tsunami",
		"tunnel",
		"turtle",
		"twilight",
		"Twix",
		"tyrannosaurus rex",
		"ufo",
		"umbrella",
		"unicorn",
		"vacuum cleaner",
		"vampire",
		"vase",
		"vegetable",
		"village",
		"vinegar",
		"volcano",
		"vulture",
		"wagon",
		"wall",
		"wallet",
		"wand",
		"warrior",
		"watch",
		"water",
		"water gun",
		"water lily",
		"water pipe",
		"waterfall",
		"waterwheel",
		"wave",
		"wax",
		"web",
		"werewolf",
		"wheat",
		"wheel",
		"wild animal",
		"wild boar",
		"Willy Wonka",
		"wind",
		"wind turbine",
		"windmill",
		"window",
		"wine",
		"wire",
		"witch",
		"wizard",
		"wolf",
		"wood",
		"woodpecker",
		"wool",
		"wrapping paper",
		"x-ray",
		"yak",
		"Yeti",
		"yoda",
		"yogurt",
		"zombie"
	],
	recipes: [
		["air", "air", "pressure"],
		["air", "cloud", "sky"],
		["air", "dinosaur", "pterodactyl"],
		["earth", "air", "dust"],
		["egg", "air", "bird"],
		["air", "energy", "wind"],
		["air", "fire", "energy"],
		["air", "lava", "stone"],
		["air", "life", "bird"],
		["air", "metal", "rust"],
		["air", "pressure", "atmosphere"],
		["pressure", "air", "wind"],
		["air", "soap", "soap bubble"],
		["air", "steam", "cloud"],
		["air", "steel", "rust"],
		["air", "stone", "sand"],
		["water", "air", "rain"],
		["air", "wave", "sound"],
		["air", "wine", "vinegar"],
		["airplane", "alien", "ufo"],
		["airplane", "astronaut", "spaceship"],
		["blade", "airplane", "helicopter"],
		["airplane", "human", "pilot"],
		["airplane", "ocean", "seaplane"],
		["airplane", "paper", "paper airplane"],
		["airplane", "robot", "drone"],
		["airplane", "sea", "seaplane"],
		["airplane", "space", "rocket"],
		["squirrel", "airplane", "flying squirrel"],
		["airplane", "water", "seaplane"],
		["windmill", "airplane", "helicopter"],
		["alcohol", "flower", "perfume"],
		["fruit", "alcohol", "wine"],
		["human", "alcohol", "drunk"],
		["alcohol", "rose", "perfume"],
		["alcohol", "wheat", "beer"],
		["algae", "stone", "moss"],
		["rocket", "alien", "ufo"],
		["house", "ambulance", "hospital"],
		["angel", "music", "harp"],
		["antarctica", "atmosphere", "aurora"],
		["ocean", "antarctica", "iceberg"],
		["sea", "antarctica", "iceberg"],
		["sky", "antarctica", "aurora"],
		["sun", "antarctica", "aurora"],
		["bullet", "armor", "bulletproof vest"],
		["car", "armor", "tank"],
		["human", "armor", "knight"],
		["life", "armor", "robot"],
		["wild animal", "armor", "armadillo"],
		["oil", "ash", "soap"],
		["astronaut", "ice cream", "Astronaut Ice Cream"],
		["meteoroid", "atmosphere", "meteor"],
		["axe", "electricity", "chainsaw"],
		["axe", "human", "lumberjack"],
		["bread", "bacon", "sandwich"],
		["glass", "bacteria", "microscope"],
		["bacteria", "glasses", "microscope"],
		["human", "bacteria", "sickness"],
		["milk", "bacteria", "yogurt"],
		["house", "baker", "bakery"],
		["paper", "baker", "recipe"],
		["bread", "banana", "banana bread"],
		["farmer", "barn", "farm"],
		["bat", "human", "batman"],
		["meat", "bbq", "steak"],
		["bird", "beach", "seagull"],
		["beach", "glasses", "sunglasses"],
		["light", "beach", "lighthouse"],
		["beach", "sandwich", "picnic"],
		["tree", "beach", "palm"],
		["beach", "wind", "dune"],
		["beaver", "duck", "platypus"],
		["beaver", "river", "dam"],
		["beaver", "tree", "dam"],
		["beaver", "wood", "dam"],
		["bee", "beehive", "honey"],
		["bee", "beehive", "wax"],
		["bee", "flower", "honey"],
		["bee", "house", "beehive"],
		["bee", "tree", "beehive"],
		["beer", "human", "drunk"],
		["beer", "ice cream", "Guinness Float"],
		["bicycle", "energy", "motorcycle"],
		["bicycle", "human", "cyclist"],
		["bicycle", "steel", "motorcycle"],
		["bird", "bird", "egg"],
		["bird", "city", "pigeon"],
		["clock", "bird", "cuckoo"],
		["bird", "corpse", "vulture"],
		["bird", "dinosaur", "pterodactyl"],
		["bird", "earth", "ostrich"],
		["bird", "farmer", "chicken"],
		["bird", "field", "crow"],
		["fire", "bird", "phoenix"],
		["fish", "bird", "flying fish"],
		["bird", "flower", "hummingbird"],
		["bird", "hay", "nest"],
		["bird", "horse", "pegasus"],
		["bird", "house", "birdhouse"],
		["human", "bird", "angel"],
		["ice", "bird", "penguin"],
		["bird", "lake", "duck"],
		["bird", "letter", "pigeon"],
		["livestock", "bird", "chicken"],
		["bird", "metal", "airplane"],
		["mountain", "bird", "eagle"],
		["mouse", "bird", "bat"],
		["night", "bird", "owl"],
		["bird", "ocean", "seagull"],
		["bird", "paper", "origami"],
		["bird", "pirate", "parrot"],
		["bird", "pond", "duck"],
		["bird", "rainbow", "peacock"],
		["bird", "rainbow", "toucan"],
		["bird", "sand", "ostrich"],
		["bird", "scarecrow", "crow"],
		["bird", "sea", "seagull"],
		["bird", "snow", "penguin"],
		["squirrel", "bird", "flying squirrel"],
		["bird", "statue", "pigeon"],
		["bird", "steel", "airplane"],
		["bird", "tree", "nest"],
		["bird", "unicorn", "pegasus"],
		["water", "bird", "duck"],
		["bird", "wizard", "owl"],
		["bird", "wood", "woodpecker"],
		["blade", "blade", "scissors"],
		["cow", "blade", "leather"],
		["blade", "doctor", "scalpel"],
		["blade", "electricity", "blender"],
		["glass", "blade", "blender"],
		["blade", "grass", "scythe"],
		["gun", "blade", "bayonet"],
		["blade", "hospital", "scalpel"],
		["human", "blade", "blood"],
		["blade", "livestock", "meat"],
		["blade", "metal", "sword"],
		["paper", "blade", "confetti"],
		["blade", "pencil", "pencil sharpener"],
		["pig", "blade", "leather"],
		["blade", "pumpkin", "jack-o'-lantern"],
		["star", "blade", "shuriken"],
		["blade", "steel", "sword"],
		["blade", "wheat", "scythe"],
		["blade", "wood", "axe"],
		["fruit", "blender", "smoothie"],
		["blood", "fabric", "bandage"],
		["fish", "blood", "piranha"],
		["human", "blood", "vampire"],
		["blood", "ocean", "shark"],
		["sea", "blood", "shark"],
		["boat", "fabric", "sailboat"],
		["human", "boat", "sailor"],
		["boat", "pirate", "pirate ship"],
		["boat", "sickness", "seasickness"],
		["steam engine", "boat", "steamboat"],
		["boat", "wind", "sailboat"],
		["boiler", "tool", "steam engine"],
		["boiler", "wheel", "steam engine"],
		["bone", "bone", "skeleton"],
		["chicken", "bone", "chicken wing"],
		["bone", "light", "x-ray"],
		["wolf", "bone", "dog"],
		["book", "house", "library"],
		["book", "recipe", "cookbook"],
		["cheese", "bread", "sandwich"],
		["bread", "fire", "toast"],
		["bread", "ham", "sandwich"],
		["house", "bread", "bakery"],
		["human", "bread", "baker"],
		["meat", "bread", "hamburger"],
		["time", "bread", "mold"],
		["brick", "brick", "wall"],
		["campfire", "brick", "fireplace"],
		["fireplace", "brick", "chimney"],
		["human", "brick", "house"],
		["smoke", "brick", "chimney"],
		["tool", "brick", "house"],
		["electricity", "broom", "vacuum cleaner"],
		["human", "broom", "witch"],
		["wizard", "broom", "witch"],
		["metal", "bullet", "gun"],
		["cow", "butcher", "meat"],
		["livestock", "butcher", "meat"],
		["pig", "butcher", "meat"],
		["butterfly", "moon", "moth"],
		["butterfly", "night", "moth"],
		["sand", "cactus", "desert"],
		["campfire", "fabric", "smoke signal"],
		["campfire", "garden", "bbq"],
		["house", "campfire", "fireplace"],
		["human", "campfire", "story"],
		["campfire", "meat", "bbq"],
		["sugar", "campfire", "marshmallows"],
		["campfire", "wall", "fireplace"],
		["campfire", "witch", "cauldron"],
		["dough", "candle", "cake"],
		["pumpkin", "candle", "jack-o'-lantern"],
		["car", "car", "bus"],
		["doctor", "car", "ambulance"],
		["car", "electricity", "electric car"],
		["farmer", "car", "tractor"],
		["field", "car", "tractor"],
		["fireman", "car", "firetruck"],
		["car", "gun", "tank"],
		["hospital", "car", "ambulance"],
		["house", "car", "rv"],
		["car", "ice cream", "ice cream truck"],
		["snow", "car", "snowmobile"],
		["caramel", "chocolate", "Caramelo"],
		["caramel", "orchard", "Caramel Apple"],
		["Caramelo", "cookie", "Twix"],
		["carbon dioxide", "cold", "dry ice"],
		["fire", "carbon dioxide", "fire extinguisher"],
		["ice", "carbon dioxide", "dry ice"],
		["juice", "carbon dioxide", "soda"],
		["metal", "carbon dioxide", "fire extinguisher"],
		["plant", "carbon dioxide", "oxygen"],
		["pressure", "carbon dioxide", "fire extinguisher"],
		["water", "carbon dioxide", "soda"],
		["snow", "carrot", "snowman"],
		["snowball", "carrot", "snowman"],
		["carrot", "wild animal", "rabbit"],
		["cart", "horse", "wagon"],
		["cart", "mountain", "roller coaster"],
		["snow", "cart", "sledge"],
		["gunpowder", "castle", "cannon"],
		["human", "castle", "monarch"],
		["castle", "night", "ghost"],
		["sand", "castle", "sand castle"],
		["story", "castle", "fairy tale"],
		["time", "castle", "ruins"],
		["cat", "music", "Keyboard Cat"],
		["cat", "plant", "catnip"],
		["wild animal", "cat", "lion"],
		["caviar", "seaweed", "sushi"],
		["human", "chainsaw", "lumberjack"],
		["wood", "charcoal", "pencil"],
		["cheese", "dough", "pizza"],
		["cheese", "fish", "Goldfish"],
		["cheese", "hamburger", "cheeseburger"],
		["metal", "cheese", "mousetrap"],
		["cheese", "pasta", "mac and cheese"],
		["sky", "cheese", "moon"],
		["cheese", "toast", "grilled cheese"],
		["cheese", "wild animal", "mouse"],
		["wood", "cheese", "mousetrap"],
		["chicken", "sugar", "Peeps"],
		["water", "chicken", "chicken soup"],
		["chicken", "wild animal", "fox"],
		["santa", "chimney", "gift"],
		["chocolate", "coconut", "Mounds"],
		["chocolate", "egg", "Cadbury Eggs"],
		["chocolate", "milk", "chocolate milk"],
		["santa", "christmas stocking", "gift"],
		["christmas tree", "glass", "snow globe"],
		["human", "christmas tree", "santa"],
		["santa", "christmas tree", "gift"],
		["sugar", "christmas tree", "candy cane"],
		["dinosaur", "city", "godzilla"],
		["fog", "city", "smog"],
		["clay", "fire", "brick"],
		["fire", "clay", "pottery"],
		["clay", "life", "golem"],
		["clay", "oil", "oil lamp"],
		["clay", "sun", "brick"],
		["clay", "tool", "pottery"],
		["clay", "wheel", "pottery"],
		["egg", "clock", "egg timer"],
		["human", "clock", "watch"],
		["clock", "sound", "alarm clock"],
		["clock", "sun", "sundial"],
		["earth", "cloud", "fog"],
		["cloud", "electricity", "storm"],
		["energy", "cloud", "storm"],
		["ice", "cloud", "hail"],
		["cloud", "livestock", "sheep"],
		["plant", "cloud", "cotton"],
		["cloud", "sugar", "cotton candy"],
		["cloud", "water", "rain"],
		["metal", "coal", "steel"],
		["pressure", "coal", "diamond"],
		["coal", "time", "diamond"],
		["wood", "coal", "pencil"],
		["milk", "coconut", "coconut milk"],
		["coconut", "tool", "coconut milk"],
		["coffin", "earth", "grave"],
		["electricity", "cold", "fridge"],
		["juice", "cold", "popsicle"],
		["metal", "cold", "fridge"],
		["milk", "cold", "ice cream"],
		["rain", "cold", "snow"],
		["steam", "cold", "snow"],
		["cold", "tea", "iced tea"],
		["water", "cold", "ice"],
		["cold", "yogurt", "frozen yogurt"],
		["computer", "computer", "internet"],
		["computer", "dog", "Doge"],
		["letter", "computer", "email"],
		["mouse", "computer", "computer mouse"],
		["paper", "computer", "printer"],
		["computer", "squirrel", "Pokki"],
		["computer", "web", "internet"],
		["computer", "wire", "internet"],
		["confetti", "sugar", "sprinkles"],
		["cookie", "dough", "cookie dough"],
		["paper", "cookie", "fortune cookie"],
		["santa", "cookie", "gift"],
		["corpse", "earth", "grave"],
		["electricity", "corpse", "frankenstein"],
		["corpse", "life", "zombie"],
		["corpse", "pyramid", "mummy"],
		["corpse", "scythe", "grim reaper"],
		["corpse", "time", "bone"],
		["corpse", "time", "skeleton"],
		["wood", "corpse", "coffin"],
		["cotton", "fabric", "pillow"],
		["cotton", "tool", "thread"],
		["farmer", "cow", "milk"],
		["fire", "cow", "steak"],
		["cow", "house", "barn"],
		["cow", "human", "milk"],
		["human", "cow", "minotaur"],
		["cow", "mountain", "yak"],
		["cow", "rope", "lasso"],
		["cow", "sea", "manatee"],
		["cow", "tool", "meat"],
		["crown", "human", "monarch"],
		["snow", "crystal ball", "snow globe"],
		["river", "dam", "lake"],
		["wild animal", "dam", "beaver"],
		["day", "night", "twilight"],
		["time", "day", "night"],
		["day", "vampire", "dust"],
		["desert", "grave", "pyramid"],
		["desert", "horse", "camel"],
		["ice", "desert", "antarctica"],
		["livestock", "desert", "camel"],
		["desert", "palm", "oasis"],
		["desert", "plant", "cactus"],
		["snow", "desert", "antarctica"],
		["desert", "stone", "pyramid"],
		["tree", "desert", "oasis"],
		["desert", "water", "oasis"],
		["desert", "wild animal", "camel"],
		["desert", "wind", "dune"],
		["diamond", "gold", "ring"],
		["diamond", "metal", "ring"],
		["diamond", "sugar", "Ring Pop"],
		["dinosaur", "earth", "fossil"],
		["meat", "dinosaur", "tyrannosaurus rex"],
		["stone", "dinosaur", "fossil"],
		["dinosaur", "time", "fossil"],
		["house", "doctor", "hospital"],
		["doctor", "mold", "penicillin"],
		["doctor", "Tardis", "The Doctor"],
		["tool", "doctor", "stethoscope"],
		["dog", "forest", "wolf"],
		["dog", "house", "doghouse"],
		["dog", "ice", "husky"],
		["dog", "internet", "Doge"],
		["dog", "sea", "seal"],
		["dog", "snow", "husky"],
		["wild animal", "dog", "wolf"],
		["double rainbow!", "horse", "unicorn"],
		["double rainbow!", "life", "unicorn"],
		["dough", "fire", "bread"],
		["dough", "fruit", "pie"],
		["house", "dough", "gingerbread house"],
		["human", "dough", "baker"],
		["life", "dough", "gingerbread man"],
		["dough", "oil", "donut"],
		["dough", "sugar", "cookie"],
		["knight", "dragon", "hero"],
		["dragon", "story", "fairy tale"],
		["egg", "duck", "duckling"],
		["time", "duckling", "duck"],
		["wild animal", "dune", "scorpion"],
		["fire", "dust", "gunpowder"],
		["human", "dust", "allergy"],
		["earth", "earth", "pressure"],
		["earthquake", "earth", "mountain"],
		["earth", "energy", "earthquake"],
		["earth", "farmer", "field"],
		["earth", "fire", "lava"],
		["lava", "earth", "volcano"],
		["earth", "life", "human"],
		["paper", "earth", "map"],
		["plant", "earth", "grass"],
		["rain", "earth", "plant"],
		["sky", "earth", "horizon"],
		["earth", "space", "planet"],
		["steam", "earth", "geyser"],
		["earth", "tool", "field"],
		["water", "earth", "mud"],
		["earth", "wave", "earthquake"],
		["ocean", "earthquake", "tsunami"],
		["sea", "earthquake", "tsunami"],
		["egg", "fire", "omelette"],
		["flour", "egg", "pasta"],
		["egg", "hay", "nest"],
		["egg", "livestock", "chicken"],
		["egg", "ocean", "hard roe"],
		["egg", "oil", "mayonnaise"],
		["egg", "pond", "hard roe"],
		["egg", "sand", "turtle"],
		["egg", "sea", "hard roe"],
		["egg", "sky", "bird"],
		["egg", "swamp", "lizard"],
		["egg", "watch", "egg timer"],
		["egg", "water", "hard roe"],
		["fish", "electricity", "electric eel"],
		["electricity", "flashlight", "light"],
		["electricity", "glass", "light bulb"],
		["gun", "electricity", "taser"],
		["human", "electricity", "electrician"],
		["light bulb", "electricity", "light"],
		["electricity", "metal", "wire"],
		["electricity", "needle", "sewing machine"],
		["electricity", "nerd", "computer"],
		["electricity", "oxygen", "ozone"],
		["sand", "electricity", "glass"],
		["electricity", "scythe", "lawn mower"],
		["electricity", "sugar", "cotton candy"],
		["electricity", "sword", "lightsaber"],
		["time", "electricity", "clock"],
		["windmill", "electricity", "wind turbine"],
		["zombie", "electricity", "frankenstein"],
		["energy", "explosion", "atomic bomb"],
		["fruit", "energy", "sugar"],
		["human", "energy", "wizard"],
		["juice", "energy", "sugar"],
		["metal", "energy", "electricity"],
		["energy", "milk", "butter"],
		["sand", "energy", "sandstorm"],
		["energy", "snow", "avalanche"],
		["swamp", "energy", "life"],
		["energy", "sword", "lightsaber"],
		["volcano", "energy", "ash"],
		["volcano", "energy", "eruption"],
		["water", "energy", "steam"],
		["wind", "energy", "hurricane"],
		["engineer", "glasses", "safety glasses"],
		["engineer", "mountain", "tunnel"],
		["engineer", "paper", "blueprint"],
		["engineer", "sugar", "Willy Wonka"],
		["excalibur", "human", "monarch"],
		["explosion", "glasses", "safety glasses"],
		["explosion", "metal", "grenade"],
		["explosion", "sky", "fireworks"],
		["explosion", "star", "super nova"],
		["explosion", "stone", "Pop Rocks"],
		["fabric", "hero", "cape"],
		["fabric", "house", "tent"],
		["fabric", "mountain goat", "cashmere"],
		["fabric", "pilot", "parachute"],
		["rain", "fabric", "umbrella"],
		["fabric", "smoke", "smoke signal"],
		["fabric", "wood", "tent"],
		["tree", "family", "family tree"],
		["field", "farmer", "wheat"],
		["farmer", "grass", "hay"],
		["farmer", "house", "farm"],
		["farmer", "life", "livestock"],
		["plant", "farmer", "wheat"],
		["tree", "farmer", "fruit"],
		["farmer", "wild animal", "livestock"],
		["leaf", "fence", "hedge"],
		["plant", "fence", "hedge"],
		["field", "fruit tree", "orchard"],
		["field", "fruit", "vegetable"],
		["field", "human", "farmer"],
		["fire", "gun", "flamethrower"],
		["gunpowder", "fire", "explosion"],
		["human", "fire", "fireman"],
		["fire", "ice", "water"],
		["jedi", "fire", "darth vader"],
		["juice", "fire", "sugar"],
		["lizard", "fire", "dragon"],
		["fire", "mountain", "volcano"],
		["mud", "fire", "brick"],
		["fire", "ocean", "salt"],
		["fire", "oil", "oil lamp"],
		["pig", "fire", "bacon"],
		["plant", "fire", "tobacco"],
		["pumpkin", "fire", "jack-o'-lantern"],
		["fire", "sand", "glass"],
		["sandwich", "fire", "toast"],
		["fire", "sea", "salt"],
		["fire", "sky", "sun"],
		["fire", "stone", "metal"],
		["sugar", "fire", "caramel"],
		["tree", "fire", "charcoal"],
		["vegetable", "fire", "pumpkin"],
		["water", "fire", "steam"],
		["wax", "fire", "candle"],
		["fire", "wood", "campfire"],
		["wood", "fire", "charcoal"],
		["fire", "wood", "smoke"],
		["house", "fireplace", "chimney"],
		["santa", "fireplace", "gift"],
		["fireplace", "witch", "cauldron"],
		["wool", "fireplace", "christmas stocking"],
		["human", "firetruck", "fireman"],
		["fish", "fish", "hard roe"],
		["fish", "french fries", "fish and chips"],
		["glass", "fish", "aquarium"],
		["fish", "horse", "seahorse"],
		["human", "fish", "mermaid"],
		["fish", "seaweed", "sushi"],
		["sky", "fish", "flying fish"],
		["fish", "star", "starfish"],
		["fish", "sugar", "Swedish Fish"],
		["fish", "sword", "swordfish"],
		["tool", "fish", "fishing rod"],
		["wood", "fish", "fishing rod"],
		["human", "fishing rod", "angler"],
		["snowman", "flamethrower", "puddle"],
		["human", "flour", "baker"],
		["flour", "milk", "batter"],
		["flour", "paper", "recipe"],
		["water", "flour", "dough"],
		["flower", "flower", "garden"],
		["flower", "love", "rose"],
		["flower", "pond", "water lily"],
		["pottery", "flower", "vase"],
		["flower", "steam", "perfume"],
		["flower", "sun", "sunflower"],
		["flower", "water", "perfume"],
		["flower", "wild animal", "bee"],
		["flower", "wild animal", "butterfly"],
		["human", "flute", "music"],
		["fog", "grass", "dew"],
		["smoke", "fog", "smog"],
		["forest", "life", "wild animal"],
		["pig", "forest", "wild boar"],
		["fossil", "pressure", "petroleum"],
		["fossil", "time", "petroleum"],
		["fruit tree", "fruit tree", "orchard"],
		["fruit", "juice", "Juicy Fruit"],
		["fruit", "monkey", "banana"],
		["palm", "fruit", "coconut"],
		["pressure", "fruit", "juice"],
		["fruit", "rocket", "Starburst"],
		["fruit", "time", "alcohol"],
		["fruit", "tree", "fruit tree"],
		["water", "fruit", "juice"],
		["fruit", "water", "lemonade"],
		["human", "garden", "gardener"],
		["plant", "garden", "flower"],
		["garden", "statue", "gnome"],
		["water", "garden", "pond"],
		["gift", "paper", "wrapping paper"],
		["house", "gingerbread man", "gingerbread house"],
		["glass", "glass", "glasses"],
		["glass", "house", "window"],
		["glass", "metal", "glasses"],
		["glass", "metal", "mirror"],
		["glass", "oil", "oil lamp"],
		["plant", "glass", "greenhouse"],
		["glass", "rainbow", "prism"],
		["sand", "glass", "hourglass"],
		["sand", "glass", "time"],
		["glass", "sky", "telescope"],
		["glass", "snow", "snow globe"],
		["glass", "snowman", "snow globe"],
		["glass", "space", "telescope"],
		["glass", "star", "telescope"],
		["water", "glass", "aquarium"],
		["witch", "glass", "crystal ball"],
		["wizard", "glass", "crystal ball"],
		["human", "glasses", "nerd"],
		["glasses", "snow", "ski goggles"],
		["sun", "glasses", "sunglasses"],
		["tool", "glasses", "safety glasses"],
		["glasses", "water", "swim goggles"],
		["goat", "human", "faun"],
		["goat", "mountain range", "mountain goat"],
		["mountain", "goat", "mountain goat"],
		["house", "gold", "bank"],
		["gold", "metal", "safe"],
		["gold", "monarch", "crown"],
		["paper", "gold", "money"],
		["gold", "steel", "safe"],
		["house", "grass", "garden"],
		["grass", "livestock", "cow"],
		["mud", "grass", "swamp"],
		["plant", "grass", "garden"],
		["grass", "sandwich", "picnic"],
		["grass", "scythe", "hay"],
		["grass", "sun", "hay"],
		["grass", "tool", "lawn mower"],
		["water", "grass", "dew"],
		["grass", "wild animal", "ant"],
		["grave", "grave", "graveyard"],
		["grave", "stone", "gravestone"],
		["gravestone", "gravestone", "graveyard"],
		["graveyard", "night", "ghost"],
		["human", "grim reaper", "corpse"],
		["human", "gun", "corpse"],
		["gun", "sword", "bayonet"],
		["water", "gun", "water gun"],
		["gunpowder", "metal", "bullet"],
		["gunpowder", "pirate ship", "cannon"],
		["gunpowder", "wire", "dynamite"],
		["hard roe", "human", "caviar"],
		["hard roe", "time", "fish"],
		["hay", "hay", "hay bale"],
		["house", "hay", "barn"],
		["human", "hay", "scarecrow"],
		["hay", "livestock", "horse"],
		["metal", "hay", "needle"],
		["tool", "hay", "pitchfork"],
		["wood", "hay", "broom"],
		["horse", "human", "centaur"],
		["horse", "leather", "saddle"],
		["metal", "horse", "horseshoe"],
		["ocean", "horse", "seahorse"],
		["rainbow", "horse", "unicorn"],
		["horse", "river", "hippo"],
		["horse", "rope", "lasso"],
		["horse", "sea", "seahorse"],
		["sky", "horse", "pegasus"],
		["horse", "water", "hippo"],
		["horse", "wood", "trojan horse"],
		["human", "hospital", "doctor"],
		["house", "house", "village"],
		["human", "house", "family"],
		["house", "ice", "igloo"],
		["house", "knight", "castle"],
		["light", "house", "lighthouse"],
		["livestock", "house", "barn"],
		["house", "money", "bank"],
		["house", "safe", "bank"],
		["house", "sickness", "hospital"],
		["house", "sky", "skyscraper"],
		["house", "snow", "igloo"],
		["space", "house", "space station"],
		["time", "house", "ruins"],
		["tree", "house", "treehouse"],
		["house", "wind", "windmill"],
		["wood", "house", "log cabin"],
		["human", "human", "love"],
		["human", "letter", "mailman"],
		["human", "light bulb", "idea"],
		["lightsaber", "human", "jedi"],
		["human", "lion", "sphinx"],
		["human", "meat", "butcher"],
		["human", "medusa", "statue"],
		["metal", "human", "tool"],
		["human", "moon", "astronaut"],
		["human", "oxygen", "carbon dioxide"],
		["human", "pitchfork", "farmer"],
		["human", "plant", "farmer"],
		["human", "rain", "cold"],
		["human", "rain", "sickness"],
		["human", "robot", "cyborg"],
		["rocket", "human", "astronaut"],
		["human", "sailboat", "sailor"],
		["human", "scythe", "grim reaper"],
		["seaplane", "human", "pilot"],
		["shuriken", "human", "ninja"],
		["human", "sickness", "sickness"],
		["human", "snake", "medusa"],
		["snow", "human", "snowball"],
		["snow", "human", "snowman"],
		["human", "sound", "music"],
		["human", "space station", "astronaut"],
		["human", "space", "astronaut"],
		["human", "swim goggles", "swimmer"],
		["sword", "human", "warrior"],
		["human", "tool", "engineer"],
		["human", "vampire", "vampire"],
		["human", "wave", "surfer"],
		["werewolf", "human", "werewolf"],
		["wild animal", "human", "dog"],
		["wild animal", "human", "livestock"],
		["human", "wine", "drunk"],
		["human", "wire", "electrician"],
		["wolf", "human", "werewolf"],
		["wood", "human", "house"],
		["human", "wool", "sweater"],
		["human", "zombie", "zombie"],
		["sand", "hurricane", "sandstorm"],
		["milk", "ice cream", "milk shake"],
		["juice", "ice", "popsicle"],
		["metal", "ice", "fridge"],
		["milk", "ice", "ice cream"],
		["ice", "mountain", "glacier"],
		["ocean", "ice", "iceberg"],
		["rain", "ice", "hail"],
		["sea", "ice", "iceberg"],
		["ice", "storm", "hail"],
		["sun", "ice", "puddle"],
		["ice", "tea", "iced tea"],
		["ice", "wild animal", "penguin"],
		["ice", "yogurt", "frozen yogurt"],
		["steamboat", "iceberg", "titanic"],
		["letter", "internet", "email"],
		["isle", "isle", "archipelago"],
		["isle", "tree", "palm"],
		["jedi", "lava", "darth vader"],
		["jedi", "swamp", "yoda"],
		["juice", "sugar", "jam"],
		["juice", "time", "alcohol"],
		["knight", "lightsaber", "jedi"],
		["knight", "story", "fairy tale"],
		["knight", "windmill", "Don Quixote"],
		["lake", "story", "Nessie"],
		["lava", "lamp", "lava lamp"],
		["lava", "mountain", "volcano"],
		["lava", "pressure", "granite"],
		["lava", "water", "obsidian"],
		["leaf", "sickness", "herb"],
		["water", "leaf", "tea"],
		["leather", "money", "wallet"],
		["wood", "leather", "drum"],
		["metal", "life", "robot"],
		["ocean", "life", "plankton"],
		["rainbow", "life", "unicorn"],
		["sea", "life", "plankton"],
		["life", "sky", "bird"],
		["life", "space", "alien"],
		["steel", "life", "robot"],
		["life", "stone", "egg"],
		["swamp", "life", "bacteria"],
		["water", "life", "plankton"],
		["wood", "life", "pinocchio"],
		["metal", "light bulb", "lamp"],
		["light bulb", "nerd", "idea"],
		["light bulb", "tree", "christmas tree"],
		["light", "ocean", "lighthouse"],
		["rain", "light", "rainbow"],
		["light", "sea", "lighthouse"],
		["light", "skeleton", "x-ray"],
		["light", "solar cell", "electricity"],
		["light", "sword", "lightsaber"],
		["tool", "light", "flashlight"],
		["vegetable", "light", "pumpkin"],
		["wire", "light", "optical fiber"],
		["livestock", "mountain", "goat"],
		["livestock", "mud", "pig"],
		["livestock", "santa", "reindeer"],
		["lizard", "lizard", "egg"],
		["lizard", "rainbow", "chameleon"],
		["lizard", "river", "alligator"],
		["lizard", "swamp", "alligator"],
		["lizard", "time", "dinosaur"],
		["plant", "love", "rose"],
		["love", "sugar", "Sweethearts"],
		["love", "time", "life"],
		["pirate", "map", "treasure map"],
		["meat", "salt", "jerky"],
		["meat", "smoke", "ham"],
		["meat", "sun", "jerky"],
		["metal", "monarch", "crown"],
		["metal", "money", "safe"],
		["metal", "oxygen", "rust"],
		["metal", "rainbow", "gold"],
		["river", "metal", "bridge"],
		["metal", "rope", "chain"],
		["steam engine", "metal", "train"],
		["steam", "metal", "boiler"],
		["metal", "stone", "blade"],
		["metal", "sun", "gold"],
		["metal", "thread", "needle"],
		["tool", "metal", "armor"],
		["wheel", "metal", "car"],
		["metal", "witch", "cauldron"],
		["metal", "wood", "hammer"],
		["sky", "meteoroid", "meteor"],
		["milk", "pressure", "butter"],
		["milk", "space", "Milky Way"],
		["time", "milk", "cheese"],
		["wheat", "milk", "cereal"],
		["wild animal", "milk", "cat"],
		["story", "monarch", "fairy tale"],
		["pig", "money", "piggy bank"],
		["money", "steel", "safe"],
		["ocean", "moon", "tide"],
		["sea", "moon", "tide"],
		["sky", "moon", "night"],
		["moon", "star", "space"],
		["sun", "moon", "eclipse"],
		["moon", "time", "night"],
		["wild animal", "moon", "wolf"],
		["snow", "motorcycle", "snowmobile"],
		["mountain goat", "scissors", "cashmere"],
		["mountain goat", "thread", "cashmere"],
		["mountain goat", "tool", "cashmere"],
		["mountain goat", "wool", "cashmere"],
		["mountain range", "story", "Yeti"],
		["mountain", "mountain", "mountain range"],
		["rain", "mountain", "river"],
		["mountain", "river", "waterfall"],
		["mountain", "sheep", "alpaca"],
		["mountain", "story", "Yeti"],
		["mountain", "train", "roller coaster"],
		["mountain", "water", "river"],
		["mouse", "sky", "bat"],
		["mouse", "tree", "squirrel"],
		["wheel", "mouse", "hamster"],
		["mud", "plant", "swamp"],
		["sand", "mud", "clay"],
		["mud", "sun", "brick"],
		["paper", "music", "sheet music"],
		["needle", "robot", "sewing machine"],
		["nerd", "sugar", "Nerds"],
		["tool", "nerd", "computer"],
		["wire", "nerd", "computer"],
		["plant", "night", "carbon dioxide"],
		["sky", "night", "star"],
		["night", "sun", "day"],
		["night", "telescope", "star"],
		["time", "night", "day"],
		["tree", "night", "carbon dioxide"],
		["ninja", "turtle", "Ninja Turtle"],
		["ocean", "plant", "algae"],
		["plant", "ocean", "seaweed"],
		["ocean", "sand", "beach"],
		["sickness", "ocean", "seasickness"],
		["ocean", "sky", "horizon"],
		["ocean", "star", "starfish"],
		["ocean", "sun", "salt"],
		["unicorn", "ocean", "narwhal"],
		["ocean", "volcano", "isle"],
		["ocean", "wild animal", "shark"],
		["ocean", "wind", "wave"],
		["oil", "pottery", "oil lamp"],
		["oil", "rope", "oil lamp"],
		["oil", "vegetable", "french fries"],
		["oxygen", "oxygen", "ozone"],
		["steel", "oxygen", "rust"],
		["oxygen", "wine", "vinegar"],
		["paper", "paper", "newspaper"],
		["paper", "pencil", "letter"],
		["sand", "paper", "sandpaper"],
		["paper", "scissors", "confetti"],
		["sky", "paper", "kite"],
		["paper", "story", "book"],
		["tobacco", "paper", "cigarette"],
		["wind", "paper", "kite"],
		["paper", "wood", "book"],
		["pasta", "thread", "spaghetti"],
		["pencil", "rainbow", "crayon"],
		["water", "pencil", "paint"],
		["wood", "pencil", "ruler"],
		["pottery", "pig", "piggy bank"],
		["pig", "tool", "meat"],
		["pig", "wild animal", "wild boar"],
		["pilot", "umbrella", "parachute"],
		["water", "pipe", "water pipe"],
		["sailor", "pirate ship", "pirate"],
		["wild animal", "pirate ship", "rat"],
		["sailboat", "pirate", "pirate ship"],
		["pirate", "treasure map", "treasure"],
		["planet", "ring", "saturn"],
		["rust", "planet", "mars"],
		["sun", "planet", "solar system"],
		["plant", "plant", "garden"],
		["plant", "pottery", "vase"],
		["pressure", "plant", "coal"],
		["sand", "plant", "cactus"],
		["sea", "plant", "algae"],
		["plant", "sea", "seaweed"],
		["plant", "sickness", "herb"],
		["plant", "stone", "moss"],
		["plant", "sun", "energy"],
		["plant", "sun", "oxygen"],
		["plant", "sun", "sunflower"],
		["plant", "time", "tree"],
		["plant", "wall", "ivy"],
		["water", "plant", "algae"],
		["water", "pond", "lake"],
		["wild animal", "pond", "frog"],
		["tree", "pottery", "bonsai tree"],
		["sky", "pressure", "atmosphere"],
		["star", "pressure", "black hole"],
		["sunflower", "pressure", "oil"],
		["wood", "pressure", "paper"],
		["rain", "rain", "flood"],
		["rain", "smog", "acid rain"],
		["rain", "smoke", "acid rain"],
		["rain", "sun", "rainbow"],
		["rain", "time", "flood"],
		["tool", "rain", "umbrella"],
		["rainbow", "rainbow", "double rainbow!"],
		["rainbow", "sugar", "Skittles"],
		["water", "rainbow", "paint"],
		["rainbow", "wax", "crayon"],
		["ring", "volcano", "The One Ring"],
		["river", "steel", "bridge"],
		["wall", "river", "dam"],
		["river", "wheel", "waterwheel"],
		["river", "Willy Wonka", "chocolate"],
		["river", "wood", "bridge"],
		["robot", "vacuum cleaner", "roomba"],
		["rope", "steel", "chain"],
		["rose", "steam", "perfume"],
		["rose", "water", "perfume"],
		["sailboat", "sickness", "seasickness"],
		["sailboat", "wild animal", "rat"],
		["sword", "sailor", "pirate"],
		["sand", "sand", "desert"],
		["sea", "sand", "beach"],
		["stone", "sand", "sandstone"],
		["sand", "storm", "sandstorm"],
		["sand", "sugar", "Fun Dip"],
		["sand", "swamp", "quicksand"],
		["water", "sand", "beach"],
		["wild animal", "sand", "scorpion"],
		["sand", "wind", "dune"],
		["santa", "wild animal", "reindeer"],
		["scissors", "sheep", "wool"],
		["tree", "scissors", "bonsai tree"],
		["sea", "sea", "ocean"],
		["sickness", "sea", "seasickness"],
		["sea", "sky", "horizon"],
		["sea", "star", "starfish"],
		["sea", "sun", "salt"],
		["sea", "unicorn", "narwhal"],
		["volcano", "sea", "isle"],
		["water", "sea", "ocean"],
		["sea", "wild animal", "shark"],
		["sea", "wind", "wave"],
		["sheep", "tool", "wool"],
		["steamboat", "sickness", "seasickness"],
		["sky", "squirrel", "flying squirrel"],
		["sky", "star", "space"],
		["sky", "stone", "moon"],
		["sky", "sun", "day"],
		["skyscraper", "skyscraper", "city"],
		["snow", "snow", "blizzard"],
		["snow", "storm", "blizzard"],
		["snow", "surfer", "snowboard"],
		["snow", "wagon", "sledge"],
		["snow", "wind", "blizzard"],
		["wood", "snow", "snowboard"],
		["snowball", "snowball", "snowman"],
		["snowboard", "wheel", "skateboard"],
		["sun", "snowman", "carrot"],
		["sun", "snowman", "coal"],
		["sun", "snowman", "puddle"],
		["snowman", "vegetable", "carrot"],
		["soap", "water", "soap bubble"],
		["solar cell", "sun", "electricity"],
		["stone", "space", "meteoroid"],
		["space", "time", "Tardis"],
		["spider", "thread", "web"],
		["squirrel", "tree", "nut"],
		["squirrel", "wind", "flying squirrel"],
		["star", "star", "constellation"],
		["star", "star", "galaxy"],
		["sun", "star", "space"],
		["tree", "star", "christmas tree"],
		["statue", "water", "fountain"],
		["steam engine", "steel", "train"],
		["steam engine", "wagon", "train"],
		["steam engine", "water", "steamboat"],
		["steam engine", "wheel", "train"],
		["tool", "steel", "armor"],
		["steel", "witch", "cauldron"],
		["steel", "wool", "steel wool"],
		["sword", "stone", "excalibur"],
		["stone", "tool", "statue"],
		["wheat", "stone", "flour"],
		["wind", "stone", "sand"],
		["wild animal", "sugar", "ant"],
		["sugar", "wire", "Red Vines"],
		["sun", "time", "day"],
		["sun", "tool", "solar cell"],
		["sun", "tree", "fruit"],
		["sun", "vampire", "dust"],
		["thread", "thread", "rope"],
		["thread", "tool", "fabric"],
		["wax", "thread", "candle"],
		["wild animal", "thread", "spider"],
		["time", "tool", "clock"],
		["time", "wheel", "clock"],
		["wild animal", "time", "sloth"],
		["time", "wine", "vinegar"],
		["tobacco", "wood", "pipe"],
		["tool", "tree", "wood"],
		["tool", "wood", "wheel"],
		["wool", "tool", "sweater"],
		["tree", "tree", "forest"],
		["tree", "wild animal", "monkey"],
		["tree", "wind", "leaf"],
		["turtle", "turtle", "egg"],
		["unicorn", "water", "narwhal"],
		["village", "village", "city"],
		["wall", "wall", "house"],
		["wall", "wood", "fence"],
		["water", "water", "sea"],
		["water", "wheel", "waterwheel"],
		["water", "wood", "boat"],
		["waterwheel", "wheat", "flour"],
		["windmill", "wheat", "flour"],
		["wheel", "wheel", "bicycle"],
		["wheel", "wind", "windmill"],
		["wheel", "wood", "cart"],
		["wheel", "wool", "thread"],
		["wild animal", "wire", "snake"],
		["wild animal", "wood", "beaver"],
		["wind turbine", "wind", "electricity"],
		["wood", "wind", "flute"],
		["wire", "wool", "steel wool"],
		["wizard", "wood", "wand"]
	]
};

const STAGE_TWO = {
	baseElements: [
		"Air",
		"Earth",
		"Fire",
		"Water"
	],
	elements: [
		"Alchemist",
		"Animal",
		"Ant farm",
		"Anthill",
		"Apron",
		"Archeologist",
		"Arctic",
		"Arrow",
		"Astronomer",
		"Aviary",
		"Baast",
		"Baba yaga",
		"Babe the blue ox",
		"Barrel",
		"Battery",
		"Beekeeper",
		"Bell",
		"Big",
		"Binoculars",
		"Birdcage",
		"Blood bag",
		"Book of the dead",
		"Bottle",
		"Boulder",
		"Bow",
		"Box",
		"Bucket",
		"Butterfly net",
		"Cable car",
		"Cage",
		"Canvas",
		"Cave",
		"Chicken coop",
		"Chill",
		"Circus",
		"Closet",
		"Cockatrice",
		"Combustion engine",
		"Container",
		"Continent",
		"Cook",
		"Cookie cutter",
		"Coral",
		"Cosmic egg",
		"Cup",
		"Cupid",
		"Current",
		"Curse",
		"Cutting board",
		"Cyclops",
		"Darkness",
		"Dawn",
		"Death",
		"Deity",
		"Demon",
		"Dionysus",
		"Diver",
		"Domestication",
		"Elf",
		"Excavator",
		"Factory",
		"Faerie",
		"Firefighter",
		"Firestation",
		"Firewall",
		"Force knight",
		"Fork",
		"Frankenstein's monster",
		"Galaxy cluster",
		"Garage",
		"Gas",
		"Good",
		"Gust",
		"Hacker",
		"Hangar",
		"Heat",
		"Heaven",
		"Hedgehog",
		"Hill",
		"Holy grail",
		"Holy water",
		"Hot chocolate",
		"Ice sculpture",
		"Island",
		"Jar",
		"Jiangshi",
		"Jupiter",
		"Kaiju",
		"Katana",
		"Knife",
		"Land",
		"Laptop",
		"Lawn",
		"Legend",
		"Lens",
		"Librarian",
		"Light sword",
		"Lightning",
		"Liquid",
		"Little alchemy (element)",
		"Machine",
		"Magic",
		"Magma",
		"Mail truck",
		"Mailbox",
		"Maple syrup",
		"Maui's fishhook",
		"Mercury",
		"Mineral",
		"Mist",
		"Monster",
		"Moon rover",
		"Motion",
		"Musician",
		"Necromancer",
		"Net",
		"Nuts",
		"Ore",
		"Organic matter",
		"Painter",
		"Painting",
		"Paladin",
		"Paleontologist",
		"Pan flute",
		"Paper cup",
		"Paraglider",
		"Park",
		"Paul bunyan",
		"Peach of immortality",
		"Peanut butter",
		"Peat",
		"Pebble",
		"Philosopher's stone",
		"Philosophy",
		"Plasma",
		"Plow",
		"Polar bear",
		"Pollen",
		"Post office",
		"Potato",
		"Potter",
		"Primordial soup",
		"Quicksilver",
		"Rainforest",
		"Reed",
		"Restaurant",
		"Rivulet",
		"Robot vacuum",
		"Rock",
		"Roe",
		"Sack",
		"Samurai",
		"Sap",
		"Science",
		"Scuba tank",
		"Seed",
		"Selkie",
		"Shovel",
		"Silo",
		"Skier",
		"Sleigh",
		"Small",
		"Smartphone",
		"Snowboarder",
		"Soil",
		"Solid",
		"Spoon",
		"Spotlight",
		"Stream",
		"String phone",
		"Stun gun",
		"Supernova",
		"Swimming pool",
		"Syringe",
		"Tablet",
		"Tailor",
		"Thermometer",
		"Toolbox",
		"Tornado",
		"Trainyard",
		"Troll",
		"Universe",
		"Vault",
		"Venus",
		"Vine",
		"Warmth",
		"Windsurfer",
		"Writer",
		"Zeus",
		"Zoo"
	],
	recipes: [
		["Soil", "Soil", "Land"],
		["Soil", "Big", "Land"],
		["Continent", "Small", "Land"],
		["Earth", "Earth", "Land"],
		["Earth", "Stone", "Land"],
		["Air", "Water", "Mist"],
		["Air", "Steam", "Mist"],
		["Air", "Rain", "Mist"],
		["Land", "Big", "Continent"],
		["Land", "Land", "Continent"],
		["Land", "Earth", "Continent"],
		["Mountain range", "Mountain range", "Continent"],
		["Fire", "Idea", "Heat"],
		["Fire", "Science", "Heat"],
		["Lava", "Philosophy", "Heat"],
		["Air", "Energy", "Heat"],
		["Science", "Star", "Plasma"],
		["Science", "Sun", "Plasma"],
		["Heat", "Heat", "Plasma"],
		["Heat", "Pressure", "Plasma"],
		["Storm", "Storm", "Tornado"],
		["Storm", "Wind", "Tornado"],
		["Storm", "Motion", "Tornado"],
		["Wind", "Big", "Tornado"],
		["Wind", "Wind", "Tornado"],
		["Wind", "Motion", "Tornado"],
		["Heat", "Air", "Warmth"],
		["Heat", "Human", "Warmth"],
		["Fire", "Wall", "Firewall"],
		["Planet", "Small", "Mercury"],
		["Planet", "Heat", "Mercury"],
		["Earth", "Metal", "Plow"],
		["Earth", "Steel", "Plow"],
		["Earth", "Wood", "Plow"],
		["Field", "Metal", "Plow"],
		["Field", "Steel", "Plow"],
		["Field", "Wood", "Plow"],
		["Field", "Tool", "Plow"],
		["Planet", "Acid rain", "Venus"],
		["Planet", "Smog", "Venus"],
		["Planet", "Volcano", "Venus"],
		["Ocean", "Motion", "Current"],
		["Ocean", "Heat", "Current"],
		["Ocean", "Cold", "Current"],
		["Ocean", "Science", "Current"],
		["Sea", "Motion", "Current"],
		["Sea", "Heat", "Current"],
		["Sea", "Cold", "Current"],
		["Sea", "Science", "Current"],
		["House", "Chimney", "Factory"],
		["House", "Tool", "Factory"],
		["Volcano", "Sea", "Island"],
		["Volcano", "Ocean", "Island"],
		["Maui's fishhook", "Ocean", "Island"],
		["Maui's fishhook", "Sea", "Island"],
		["Blade", "Heat", "Katana"],
		["Blade", "Shuriken", "Katana"],
		["Blade", "Ninja", "Katana"],
		["Sword", "Shuriken", "Katana"],
		["Sword", "Ninja", "Katana"],
		["Lava", "Ocean", "Primordial soup"],
		["Lava", "Sea", "Primordial soup"],
		["Planet", "Ocean", "Primordial soup"],
		["Planet", "Sea", "Primordial soup"],
		["Earth", "Ocean", "Primordial soup"],
		["Earth", "Sea", "Primordial soup"],
		["Explosion", "Star", "Supernova"],
		["Explosion", "Sun", "Supernova"],
		["Explosion", "Galaxy", "Supernova"],
		["Explosion", "Space", "Supernova"],
		["House", "Lake", "Swimming pool"],
		["House", "Swimmer", "Swimming pool"],
		["Aquarium", "Big", "Swimming pool"],
		["Sound", "Metal", "Bell"],
		["Sound", "Steel", "Bell"],
		["Sound", "Wood", "Bell"],
		["Metal", "Hammer", "Bell"],
		["Steel", "Hammer", "Bell"],
		["Telescope", "Telescope", "Binoculars"],
		["Glasses", "Glasses", "Binoculars"],
		["Galaxy", "Galaxy", "Galaxy cluster"],
		["Galaxy", "Container", "Galaxy cluster"],
		["Airplane", "Container", "Hangar"],
		["Airplane", "House", "Hangar"],
		["Airplane", "Wall", "Hangar"],
		["Airplane", "Barn", "Hangar"],
		["Seaplane", "Container", "Hangar"],
		["Seaplane", "House", "Hangar"],
		["Seaplane", "Wall", "Hangar"],
		["Seaplane", "Barn", "Hangar"],
		["Helicopter", "Container", "Hangar"],
		["Helicopter", "House", "Hangar"],
		["Helicopter", "Wall", "Hangar"],
		["Helicopter", "Barn", "Hangar"],
		["Rocket", "Container", "Hangar"],
		["Rocket", "House", "Hangar"],
		["Rocket", "Wall", "Hangar"],
		["Rocket", "Barn", "Hangar"],
		["Spaceship", "Container", "Hangar"],
		["Spaceship", "House", "Hangar"],
		["Spaceship", "Wall", "Hangar"],
		["Spaceship", "Barn", "Hangar"],
		["Planet", "Cloud", "Jupiter"],
		["Planet", "Storm", "Jupiter"],
		["Planet", "Big", "Jupiter"],
		["Planet", "Gas", "Jupiter"],
		["Planet", "Zeus", "Jupiter"],
		["Saturn", "Big", "Jupiter"],
		["Sword", "Light", "Light sword"],
		["Sword", "Electricity", "Light sword"],
		["Sword", "Energy", "Light sword"],
		["Sword", "Space", "Light sword"],
		["Sword", "Force knight", "Light sword"],
		["Electricity", "Cloud", "Lightning"],
		["Electricity", "Storm", "Lightning"],
		["Electricity", "Rain", "Lightning"],
		["Energy", "Cloud", "Lightning"],
		["Energy", "Storm", "Lightning"],
		["Energy", "Rain", "Lightning"],
		["Land", "Storm", "Lightning"],
		["Zeus", "Tool", "Lightning"],
		["Cyclops", "Tool", "Lightning"],
		["City", "Forest", "Park"],
		["City", "Garden", "Park"],
		["City", "Grass", "Park"],
		["City", "Field", "Park"],
		["Village", "Forest", "Park"],
		["Village", "Garden", "Park"],
		["Village", "Grass", "Park"],
		["Village", "Field", "Park"],
		["Gun", "Electricity", "Stun gun"],
		["Gun", "Wire", "Stun gun"],
		["Gun", "Energy", "Stun gun"],
		["Bow", "Electricity", "Stun gun"],
		["Bow", "Energy", "Stun gun"],
		["Life", "Land", "Animal"],
		["Life", "Forest", "Animal"],
		["Life", "Mountain", "Animal"],
		["Life", "Mountain range", "Animal"],
		["Life", "Beach", "Animal"],
		["Life", "Desert", "Animal"],
		["Sky", "Night", "Darkness"],
		["Sky", "Twilight", "Darkness"],
		["Day", "Night", "Dawn"],
		["Time", "Night", "Dawn"],
		["Time", "Life", "Death"],
		["Corpse", "Philosophy", "Death"],
		["Skeleton", "Philosophy", "Death"],
		["Grave", "Philosophy", "Death"],
		["Graveyard", "Philosophy", "Death"],
		["Life", "Rainbow", "Magic"],
		["Life", "Double rainbow!", "Magic"],
		["Energy", "Witch", "Magic"],
		["Energy", "Wizard", "Magic"],
		["Earth", "Life", "Soil"],
		["Earth", "Organic matter", "Soil"],
		["Land", "Life", "Soil"],
		["Land", "Organic matter", "Soil"],
		["Space", "Container", "Universe"],
		["Galaxy cluster", "Galaxy cluster", "Universe"],
		["Galaxy cluster", "Container", "Universe"],
		["Primordial soup", "Cosmic egg", "Universe"],
		["Human", "Gold", "Alchemist"],
		["Gold", "Philosophy", "Alchemist"],
		["Ruins", "Human", "Archeologist"],
		["Ruins", "Science", "Archeologist"],
		["Human", "Telescope", "Astronomer"],
		["Mountain", "Car", "Cable car"],
		["Mountain", "Wire", "Cable car"],
		["Mountain", "Rope", "Cable car"],
		["Mountain range", "Car", "Cable car"],
		["Mountain range", "Wire", "Cable car"],
		["Mountain range", "Rope", "Cable car"],
		["Animal", "Human", "Domestication"],
		["Animal", "Farmer", "Domestication"],
		["Animal", "Science", "Domestication"],
		["Farmer", "Science", "Domestication"],
		["Human", "Fire", "Firefighter"],
		["Human", "Firetruck", "Firefighter"],
		["Human", "Fire extinguisher", "Firefighter"],
		["Human", "Light sword", "Force knight"],
		["Warrior", "Light sword", "Force knight"],
		["Knight", "Light sword", "Force knight"],
		["Human", "Computer", "Hacker"],
		["Human", "Computer mouse", "Hacker"],
		["Human", "Glasses", "Hacker"],
		["Human", "Internet", "Hacker"],
		["Life", "Death", "Organic matter"],
		["Life", "Science", "Organic matter"],
		["Bacteria", "Death", "Organic matter"],
		["Corpse", "Science", "Organic matter"],
		["Human", "Canvas", "Painter"],
		["Human", "Paint", "Painter"],
		["Human", "Painting", "Painter"],
		["Human", "Clay", "Potter"],
		["Human", "Pottery", "Potter"],
		["Human", "Katana", "Samurai"],
		["Human", "Telescope", "Science"],
		["Human", "Microscope", "Science"],
		["Human", "Universe", "Science"],
		["Human", "Ski goggles", "Skier"],
		["Human", "Mountain", "Skier"],
		["Human", "Mountain range", "Skier"],
		["Cold", "Sea", "Arctic"],
		["Cold", "Ocean", "Arctic"],
		["Bird", "Container", "Birdcage"],
		["Bird", "Safe", "Birdcage"],
		["Bird", "Wall", "Birdcage"],
		["Bird", "Cage", "Birdcage"],
		["Wolf", "Metal", "Cage"],
		["Wolf", "Steel", "Cage"],
		["Wolf", "Wall", "Cage"],
		["Fox", "Metal", "Cage"],
		["Fox", "Steel", "Cage"],
		["Fox", "Wall", "Cage"],
		["Lion", "Metal", "Cage"],
		["Lion", "Steel", "Cage"],
		["Lion", "Wall", "Cage"],
		["Hamster", "Container", "Cage"],
		["Hamster", "House", "Cage"],
		["Hamster", "Wall", "Cage"],
		["House", "Wolf", "Cave"],
		["House", "Lion", "Cave"],
		["House", "Fox", "Cave"],
		["House", "Bat", "Cave"],
		["Container", "Wolf", "Cave"],
		["Container", "Lion", "Cave"],
		["Container", "Fox", "Cave"],
		["Container", "Bat", "Cave"],
		["Air", "Cold", "Chill"],
		["Human", "Cold", "Chill"],
		["Human", "Ice", "Chill"],
		["House", "Firefighter", "Firestation"],
		["House", "Firetruck", "Firestation"],
		["Firefighter", "Land", "Firestation"],
		["Firefighter", "Village", "Firestation"],
		["Firefighter", "City", "Firestation"],
		["Corpse", "Legend", "Frankenstein's monster"],
		["Corpse", "Lightning", "Frankenstein's monster"],
		["Corpse", "Electricity", "Frankenstein's monster"],
		["Corpse", "Story", "Frankenstein's monster"],
		["Zombie", "Electricity", "Frankenstein's monster"],
		["Zombie", "Lightning", "Frankenstein's monster"],
		["Monster", "Story", "Frankenstein's monster"],
		["Monster", "Corpse", "Frankenstein's monster"],
		["Air", "Idea", "Gas"],
		["Air", "Science", "Gas"],
		["Energy", "Liquid", "Gas"],
		["Glass", "Tool", "Lens"],
		["Glass", "Engineer", "Lens"],
		["Water", "Science", "Liquid"],
		["Water", "Idea", "Liquid"],
		["Energy", "Solid", "Liquid"],
		["Tool", "Wheel", "Machine"],
		["Tool", "Tool", "Machine"],
		["Tool", "Chain", "Machine"],
		["Tool", "Engineer", "Machine"],
		["Boiler", "Wheel", "Machine"],
		["Boiler", "Tool", "Machine"],
		["Boiler", "Chain", "Machine"],
		["Lava", "Science", "Magma"],
		["Volcano", "Science", "Magma"],
		["Organic matter", "Stone", "Mineral"],
		["Organic matter", "Rock", "Mineral"],
		["Organic matter", "Earth", "Mineral"],
		["Organic matter", "Boulder", "Mineral"],
		["Organic matter", "Hill", "Mineral"],
		["Organic matter", "Mountain", "Mineral"],
		["Wind", "Science", "Motion"],
		["Wind", "Idea", "Motion"],
		["Wind", "Philosophy", "Motion"],
		["Tornado", "Science", "Motion"],
		["Tornado", "Philosophy", "Motion"],
		["Stream", "Science", "Motion"],
		["Stream", "Philosophy", "Motion"],
		["River", "Science", "Motion"],
		["River", "Philosophy", "Motion"],
		["Human", "Story", "Philosophy"],
		["Human", "Idea", "Philosophy"],
		["Egg", "Chicken", "Philosophy"],
		["Plant", "Dust", "Pollen"],
		["Plant", "Wind", "Pollen"],
		["Flower", "Dust", "Pollen"],
		["Flower", "Wind", "Pollen"],
		["Plant", "Pond", "Reed"],
		["Plant", "Puddle", "Reed"],
		["Plant", "Swamp", "Reed"],
		["Plant", "River", "Reed"],
		["Grass", "Pond", "Reed"],
		["Grass", "Puddle", "Reed"],
		["Grass", "Swamp", "Reed"],
		["Grass", "River", "Reed"],
		["Egg", "Fish", "Roe"],
		["Egg", "Water", "Roe"],
		["Egg", "Ocean", "Roe"],
		["Egg", "Sea", "Roe"],
		["Egg", "Lake", "Roe"],
		["Egg", "Flying fish", "Roe"],
		["Earth", "Idea", "Solid"],
		["Earth", "Science", "Solid"],
		["Light", "Machine", "Spotlight"],
		["Light", "Metal", "Spotlight"],
		["Light", "Steel", "Spotlight"],
		["Tool", "Container", "Toolbox"],
		["Tool", "Safe", "Toolbox"],
		["Tool", "Box", "Toolbox"],
		["Hammer", "Container", "Toolbox"],
		["Hammer", "Box", "Toolbox"],
		["Ruler", "Container", "Toolbox"],
		["Ruler", "Box", "Toolbox"],
		["Steel wool", "Container", "Toolbox"],
		["Steel wool", "Box", "Toolbox"],
		["Chain", "Box", "Toolbox"],
		["Chain", "Container", "Toolbox"],
		["Wind", "Surfer", "Windsurfer"],
		["Container", "Electricity", "Battery"],
		["Container", "Energy", "Battery"],
		["Electricity", "Mineral", "Battery"],
		["Electricity", "Ore", "Battery"],
		["Universe", "Philosophy", "Big"],
		["Galaxy", "Philosophy", "Big"],
		["Galaxy cluster", "Philosophy", "Big"],
		["Solar system", "Philosophy", "Big"],
		["Sun", "Philosophy", "Big"],
		["Planet", "Philosophy", "Big"],
		["Chicken", "House", "Chicken coop"],
		["Chicken", "Wall", "Chicken coop"],
		["Chicken", "Barn", "Chicken coop"],
		["Chicken", "Container", "Chicken coop"],
		["Cockatrice", "House", "Chicken coop"],
		["Cockatrice", "Barn", "Chicken coop"],
		["Cockatrice", "Container", "Chicken coop"],
		["Petroleum", "Machine", "Combustion engine"],
		["Petroleum", "Wheel", "Combustion engine"],
		["Petroleum", "Steam engine", "Combustion engine"],
		["Explosion", "Machine", "Combustion engine"],
		["Explosion", "Steam engine", "Combustion engine"],
		["Philosophy", "Safe", "Container"],
		["Philosophy", "Pottery", "Container"],
		["Philosophy", "House", "Container"],
		["Philosophy", "Box", "Container"],
		["Philosophy", "Bottle", "Container"],
		["Philosophy", "Bucket", "Container"],
		["Human", "Fruit", "Cook"],
		["Human", "Vegetable", "Cook"],
		["Human", "Campfire", "Cook"],
		["Human", "Nuts", "Cook"],
		["Tree", "Sea", "Coral"],
		["Tree", "Ocean", "Coral"],
		["Fossil", "Sea", "Coral"],
		["Fossil", "Ocean", "Coral"],
		["Bone", "Sea", "Coral"],
		["Bone", "Ocean", "Coral"],
		["Dinosaur", "City", "Kaiju"],
		["Dinosaur", "Skyscraper", "Kaiju"],
		["Dinosaur", "Legend", "Kaiju"],
		["Dinosaur", "Story", "Kaiju"],
		["Monster", "City", "Kaiju"],
		["Monster", "Skyscraper", "Kaiju"],
		["Grass", "House", "Lawn"],
		["Grass", "Container", "Lawn"],
		["Grass", "Lawn mower", "Lawn"],
		["Field", "Lawn mower", "Lawn"],
		["Story", "Time", "Legend"],
		["Story", "Story", "Legend"],
		["Story", "Big", "Legend"],
		["Story", "Fairy tale", "Legend"],
		["Fairy tale", "Time", "Legend"],
		["Fairy tale", "Big", "Legend"],
		["Angler", "Rope", "Net"],
		["Fishing rod", "Rope", "Net"],
		["Fish", "Rope", "Net"],
		["Swordfish", "Rope", "Net"],
		["Flying fish", "Rope", "Net"],
		["Tree", "Farmer", "Nuts"],
		["Tree", "Field", "Nuts"],
		["Tree", "Domestication", "Nuts"],
		["Hammer", "Boulder", "Ore"],
		["Hammer", "Earth", "Ore"],
		["Hammer", "Rock", "Ore"],
		["Hammer", "Stone", "Ore"],
		["Hammer", "Hill", "Ore"],
		["Hammer", "Mountain", "Ore"],
		["Human", "Dinosaur", "Paleontologist"],
		["Human", "Fossil", "Paleontologist"],
		["Science", "Dinosaur", "Paleontologist"],
		["Science", "Fossil", "Paleontologist"],
		["Swamp", "Plant", "Peat"],
		["Swamp", "Time", "Peat"],
		["Swamp", "Pressure", "Peat"],
		["Time", "Grass", "Peat"],
		["Animal", "Ice", "Polar bear"],
		["Animal", "Arctic", "Polar bear"],
		["Earth", "Vegetable", "Potato"],
		["Metal", "Liquid", "Quicksilver"],
		["Stream", "Small", "Rivulet"],
		["Puddle", "Motion", "Rivulet"],
		["Tree", "Blade", "Sap"],
		["Pollen", "Plant", "Seed"],
		["Pollen", "Bee", "Seed"],
		["Time", "Flower", "Seed"],
		["Philosophy", "Bacteria", "Small"],
		["Philosophy", "Oxygen", "Small"],
		["Philosophy", "Carbon dioxide", "Small"],
		["Philosophy", "Ozone", "Small"],
		["Philosophy", "Pebble", "Small"],
		["Philosophy", "Rivulet", "Small"],
		["Philosophy", "Ant", "Small"],
		["Philosophy", "Spider", "Small"],
		["Philosophy", "Bee", "Small"],
		["Philosophy", "Scorpion", "Small"],
		["Philosophy", "Confetti", "Small"],
		["Philosophy", "Seahorse", "Small"],
		["Human", "Snowboard", "Snowboarder"],
		["Pond", "Motion", "Stream"],
		["Rivulet", "Big", "Stream"],
		["River", "Small", "Stream"],
		["Animal", "Container", "Zoo"],
		["Animal", "Cage", "Zoo"],
		["Farm", "Ant", "Ant farm"],
		["Ant", "Jar", "Ant farm"],
		["Ant", "Glass", "Ant farm"],
		["Anthill", "Farm", "Ant farm"],
		["Anthill", "Jar", "Ant farm"],
		["Ant", "House", "Anthill"],
		["Ant", "Container", "Anthill"],
		["Ant", "Hill", "Anthill"],
		["Ant", "Earth", "Anthill"],
		["Ant", "Land", "Anthill"],
		["Ant", "Soil", "Anthill"],
		["Wood", "Bullet", "Arrow"],
		["Wood", "Bow", "Arrow"],
		["Big", "Birdcage", "Aviary"],
		["Human", "Beehive", "Beekeeper"],
		["Human", "Bee", "Beekeeper"],
		["Farmer", "Beehive", "Beekeeper"],
		["Farmer", "Bee", "Beekeeper"],
		["Blood", "Container", "Blood bag"],
		["Blood", "Sack", "Blood bag"],
		["Blood", "Bottle", "Blood bag"],
		["Container", "Milk", "Bottle"],
		["Container", "Water", "Bottle"],
		["Container", "Coconut milk", "Bottle"],
		["Container", "Juice", "Bottle"],
		["Container", "Oil", "Bottle"],
		["Container", "Alcohol", "Bottle"],
		["Container", "Wine", "Bottle"],
		["Container", "Beer", "Bottle"],
		["Container", "Chocolate milk", "Bottle"],
		["Container", "Soda", "Bottle"],
		["Container", "Perfume", "Bottle"],
		["Container", "Liquid", "Bottle"],
		["Big", "Rock", "Boulder"],
		["Big", "Stone", "Boulder"],
		["Small", "Hill", "Boulder"],
		["Rock", "Stone", "Boulder"],
		["Rock", "Rock", "Boulder"],
		["Rock", "Earth", "Boulder"],
		["Wood", "Rope", "Bow"],
		["Wood", "Wire", "Bow"],
		["Tool", "Elf", "Bow"],
		["Tool", "Cupid", "Bow"],
		["Container", "Wood", "Bucket"],
		["Container", "Yogurt", "Bucket"],
		["Container", "Paint", "Bucket"],
		["Bottle", "River", "Bucket"],
		["Bottle", "Paint", "Bucket"],
		["Chicken wing", "Container", "Bucket"],
		["Chicken wing", "Box", "Bucket"],
		["Butterfly", "Net", "Butterfly net"],
		["Bee", "Net", "Butterfly net"],
		["Container", "Broom", "Closet"],
		["Container", "Toolbox", "Closet"],
		["Container", "Umbrella", "Closet"],
		["Container", "Robot vacuum", "Closet"],
		["Container", "Vacuum cleaner", "Closet"],
		["Wood", "Cook", "Cutting board"],
		["Car", "House", "Garage"],
		["Car", "Container", "Garage"],
		["Car", "Wall", "Garage"],
		["Car", "Barn", "Garage"],
		["Ambulance", "House", "Garage"],
		["Ambulance", "Container", "Garage"],
		["Ambulance", "Wall", "Garage"],
		["Ambulance", "Barn", "Garage"],
		["Motorcycle", "House", "Garage"],
		["Motorcycle", "Container", "Garage"],
		["Motorcycle", "Wall", "Garage"],
		["Motorcycle", "Barn", "Garage"],
		["Bus", "House", "Garage"],
		["Bus", "Container", "Garage"],
		["Bus", "Wall", "Garage"],
		["Bus", "Barn", "Garage"],
		["Sleigh", "House", "Garage"],
		["Sleigh", "Container", "Garage"],
		["Sleigh", "Wall", "Garage"],
		["Sleigh", "Barn", "Garage"],
		["Electric car", "House", "Garage"],
		["Electric car", "Container", "Garage"],
		["Electric car", "Wall", "Garage"],
		["Electric car", "Barn", "Garage"],
		["Snowmobile", "House", "Garage"],
		["Snowmobile", "Container", "Garage"],
		["Snowmobile", "Wall", "Garage"],
		["Snowmobile", "Barn", "Garage"],
		["Tractor", "House", "Garage"],
		["Tractor", "Container", "Garage"],
		["Tractor", "Wall", "Garage"],
		["Tractor", "Barn", "Garage"],
		["Rv", "House", "Garage"],
		["Rv", "Container", "Garage"],
		["Rv", "Wall", "Garage"],
		["Rv", "Barn", "Garage"],
		["Ice cream truck", "House", "Garage"],
		["Ice cream truck", "Container", "Garage"],
		["Ice cream truck", "Wall", "Garage"],
		["Ice cream truck", "Barn", "Garage"],
		["Wind", "Small", "Gust"],
		["Air", "Small", "Gust"],
		["Big", "Boulder", "Hill"],
		["Earth", "Boulder", "Hill"],
		["Stone", "Boulder", "Hill"],
		["Boulder", "Boulder", "Hill"],
		["Mountain", "Small", "Hill"],
		["Ice", "Statue", "Ice sculpture"],
		["Blade", "Cook", "Knife"],
		["Sword", "Cook", "Knife"],
		["Computer", "Small", "Laptop"],
		["Small", "Alchemist", "Little alchemy (element)"],
		["Sap", "Heat", "Maple syrup"],
		["Sap", "Sugar", "Maple syrup"],
		["Moon", "Car", "Moon rover"],
		["Moon", "Electric car", "Moon rover"],
		["Nuts", "Butter", "Peanut butter"],
		["Nuts", "Pressure", "Peanut butter"],
		["Small", "Earth", "Pebble"],
		["Small", "Stone", "Pebble"],
		["Small", "Rock", "Pebble"],
		["Rain", "Forest", "Rainforest"],
		["House", "Cook", "Restaurant"],
		["Container", "Flour", "Sack"],
		["Container", "Salt", "Sack"],
		["Container", "Letter", "Sack"],
		["Container", "Air", "Scuba tank"],
		["Container", "Atmosphere", "Scuba tank"],
		["Container", "Oxygen", "Scuba tank"],
		["Tool", "Gardener", "Shovel"],
		["Wheat", "Container", "Silo"],
		["Wheat", "House", "Silo"],
		["Wheat", "Barn", "Silo"],
		["Wheat", "Wall", "Silo"],
		["Wheat", "Farm", "Silo"],
		["Wheat", "Safe", "Silo"],
		["Wheat", "Bank", "Silo"],
		["Human", "Sewing machine", "Tailor"],
		["Human", "Needle", "Tailor"],
		["Human", "Thread", "Tailor"],
		["Quicksilver", "Glass", "Thermometer"],
		["Quicksilver", "Tool", "Thermometer"],
		["Quicksilver", "Engineer", "Thermometer"],
		["Safe", "Big", "Vault"],
		["Fabric", "Cook", "Apron"],
		["Fabric", "Baker", "Apron"],
		["Container", "Pizza", "Box"],
		["Container", "Pencil", "Box"],
		["Container", "Cereal", "Box"],
		["Container", "Cookie", "Box"],
		["Container", "Donut", "Box"],
		["Container", "Cake", "Box"],
		["Container", "Crayon", "Box"],
		["Fabric", "Paint", "Canvas"],
		["Container", "Smoothie", "Cup"],
		["Container", "Tea", "Cup"],
		["Container", "Milk shake", "Cup"],
		["Bottle", "Smoothie", "Cup"],
		["Bottle", "Tea", "Cup"],
		["Bottle", "Milk shake", "Cup"],
		["Scuba tank", "Human", "Diver"],
		["Scuba tank", "Swimmer", "Diver"],
		["Scuba tank", "Sea", "Diver"],
		["Scuba tank", "Ocean", "Diver"],
		["Scuba tank", "Lake", "Diver"],
		["Shovel", "Big", "Excavator"],
		["Shovel", "Car", "Excavator"],
		["Pitchfork", "Small", "Fork"],
		["Animal", "Needle", "Hedgehog"],
		["Mouse", "Needle", "Hedgehog"],
		["Rat", "Needle", "Hedgehog"],
		["Jam", "Container", "Jar"],
		["Jam", "Bottle", "Jar"],
		["Jam", "Glass", "Jar"],
		["Jam", "Bucket", "Jar"],
		["Human", "Flute", "Musician"],
		["Human", "Music", "Musician"],
		["Human", "Sheet music", "Musician"],
		["Human", "Drum", "Musician"],
		["Human", "Pan flute", "Musician"],
		["Flute", "Flute", "Pan flute"],
		["Robot", "Vacuum cleaner", "Robot vacuum"],
		["Robot", "Broom", "Robot vacuum"],
		["Computer", "Vacuum cleaner", "Robot vacuum"],
		["Computer", "Broom", "Robot vacuum"],
		["Pebble", "Pebble", "Rock"],
		["Pebble", "Big", "Rock"],
		["Boulder", "Small", "Rock"],
		["Cart", "Snow", "Sleigh"],
		["Cart", "Ice", "Sleigh"],
		["Cart", "Arctic", "Sleigh"],
		["Cart", "Antarctica", "Sleigh"],
		["Wagon", "Snow", "Sleigh"],
		["Wagon", "Ice", "Sleigh"],
		["Wagon", "Arctic", "Sleigh"],
		["Wagon", "Antarctica", "Sleigh"],
		["Shovel", "Small", "Spoon"],
		["Doctor", "Needle", "Syringe"],
		["Tool", "Needle", "Syringe"],
		["Laptop", "Small", "Tablet"],
		["Train", "Container", "Trainyard"],
		["Train", "House", "Trainyard"],
		["Train", "Wall", "Trainyard"],
		["Train", "Garage", "Trainyard"],
		["Rainforest", "Rope", "Vine"],
		["Rainforest", "Thread", "Vine"],
		["Rainforest", "Wire", "Vine"],
		["Human", "Book", "Writer"],
		["Human", "Pencil", "Writer"],
		["Wine", "Container", "Barrel"],
		["Wine", "Wood", "Barrel"],
		["Tent", "Big", "Circus"],
		["Tent", "Animal", "Circus"],
		["Blade", "Dough", "Cookie cutter"],
		["Blade", "Cookie dough", "Cookie cutter"],
		["Chocolate milk", "Heat", "Hot chocolate"],
		["Chocolate", "Heat", "Hot chocolate"],
		["Human", "Library", "Librarian"],
		["Car", "Letter", "Mail truck"],
		["Car", "Mailman", "Mail truck"],
		["Car", "Post office", "Mail truck"],
		["Letter", "Box", "Mailbox"],
		["Letter", "Metal", "Mailbox"],
		["Letter", "Steel", "Mailbox"],
		["Letter", "Wood", "Mailbox"],
		["Mailman", "Box", "Mailbox"],
		["Mailman", "Metal", "Mailbox"],
		["Mailman", "Steel", "Mailbox"],
		["Mailman", "Wood", "Mailbox"],
		["Canvas", "Paint", "Painting"],
		["Canvas", "Painter", "Painting"],
		["Cup", "Paper", "Paper cup"],
		["Kite", "Big", "Paraglider"],
		["Mailman", "House", "Post office"],
		["Mailman", "Wall", "Post office"],
		["Mailman", "Container", "Post office"],
		["Mailman", "Letter", "Post office"],
		["Letter", "Letter", "Post office"],
		["Letter", "House", "Post office"],
		["Letter", "Wall", "Post office"],
		["Small", "Tablet", "Smartphone"],
		["Paper cup", "Wire", "String phone"],
		["Paper cup", "Thread", "String phone"],
		["Cup", "Wire", "String phone"],
		["Cup", "Thread", "String phone"]
	]
};
const form = document.getElementById("combine-form");
const firstSelect = document.getElementById("first-element");
const secondSelect = document.getElementById("second-element");
const resultText = document.getElementById("result-text");
const totalCount = document.getElementById("total-count");
const copySaveButton = document.getElementById("copy-save-button");
const importSaveButton = document.getElementById("import-save-button");
const clearSaveButton = document.getElementById("clear-save-button");
const saveDataInput = document.getElementById("save-data-input");

const SAVE_KEY = "alchemist-save-v1";
const SAVE_INTERVAL_MS = 2000;

const elementNameByLower = new Map();
for (const element of STAGE_ONE.elements) {
	elementNameByLower.set(element.toLowerCase(), element);
}
for (const element of STAGE_TWO.elements) {
	const key = element.toLowerCase();
	if (!elementNameByLower.has(key)) {
		elementNameByLower.set(key, element);
	}
}

const stageOneElementSet = new Set(STAGE_ONE.elements.map((name) => toCanonicalName(name)));
let stageTwoUnlocked = false;
let activeElementSet = new Set(stageOneElementSet);
let recipeIndex = new Map();
const unlocked = new Set(STAGE_ONE.baseElements.map((name) => toCanonicalName(name)));

function toCanonicalName(name) {
	const normalized = String(name).toLowerCase();
	return elementNameByLower.get(normalized) || String(name);
}

function toRecipeKey(first, second) {
	return [first.toLowerCase(), second.toLowerCase()].sort().join("|");
}

function addRecipesToIndex(recipes, index) {
	for (const recipe of recipes) {
		const first = toCanonicalName(recipe[0]);
		const second = toCanonicalName(recipe[1]);
		const result = toCanonicalName(recipe[2]);
		const key = toRecipeKey(first, second);
		const results = index.get(key) || [];
		if (!results.includes(result)) {
			results.push(result);
		}
		index.set(key, results);
	}
}

function rebuildActiveData() {
	activeElementSet = new Set(stageOneElementSet);
	if (stageTwoUnlocked) {
		for (const name of STAGE_TWO.elements) {
			activeElementSet.add(toCanonicalName(name));
		}
	}
	recipeIndex = new Map();
	addRecipesToIndex(STAGE_ONE.recipes, recipeIndex);
	if (stageTwoUnlocked) {
		addRecipesToIndex(STAGE_TWO.recipes, recipeIndex);
	}
}

function isStageOneComplete() {
	for (const element of stageOneElementSet) {
		if (!unlocked.has(element)) {
			return false;
		}
	}
	return true;
}

function maybeUnlockStageTwo() {
	if (stageTwoUnlocked || !isStageOneComplete()) {
		return;
	}
	stageTwoUnlocked = true;
	for (const base of STAGE_TWO.baseElements) {
		unlocked.add(toCanonicalName(base));
	}
	rebuildActiveData();
	resultText.textContent = "Stage 2 unlocked! Little Alchemy 2 combinations are now available.";
}

function populateElementOptions() {
	const sorted = Array.from(unlocked).sort((a, b) => a.localeCompare(b));
	const firstValue = firstSelect.value;
	const secondValue = secondSelect.value;
	const html = sorted.map((element) => `<option value=\"${element}\">${element}</option>`).join("");
	firstSelect.innerHTML = html;
	secondSelect.innerHTML = html;
	if (firstValue && unlocked.has(firstValue)) {
		firstSelect.value = firstValue;
	}
	if (secondValue && unlocked.has(secondValue)) {
		secondSelect.value = secondValue;
	}
}

function combineSelectedElements() {
	const first = firstSelect.value;
	const second = secondSelect.value;
	const key = toRecipeKey(first, second);
	const results = recipeIndex.get(key);
	if (!results || results.length === 0) {
		resultText.textContent = `No recipe for ${first} + ${second}.`;
		return;
	}
	const newlyUnlocked = [];
	for (const result of results) {
		if (!activeElementSet.has(result)) {
			continue;
		}
		if (unlocked.has(result)) {
			continue;
		}
		unlocked.add(result);
		newlyUnlocked.push(result);
	}
	if (newlyUnlocked.length === 0) {
		resultText.textContent = `already unlocked ${results.join(", ")}.`;
		return;
	}
	resultText.textContent = `Unlocked ${newlyUnlocked.join(", ")}!`;
	maybeUnlockStageTwo();
	populateElementOptions();
	renderInventory();
	saveDataInput.value = getEncodedSavePayload();
	saveGame();
}

function renderInventory() {
	const total = activeElementSet.size;
	const count = Array.from(unlocked).filter((name) => activeElementSet.has(name)).length;
	const percent = total === 0 ? 0 : (count / total) * 100;
	totalCount.textContent = `${count}/${total} elements unlocked (${percent.toFixed(1)}%)`; 
}

function getSavePayload() {
	return {
		version: 2,
		stageTwoUnlocked,
		unlocked: Array.from(unlocked).sort((a, b) => a.localeCompare(b))
	};
}

function encodeBase64(text) {
	const bytes = new TextEncoder().encode(text);
	let binary = "";
	for (const byte of bytes) {
		binary += String.fromCharCode(byte);
	}
	return btoa(binary);
}

function decodeBase64(encoded) {
	const binary = atob(encoded);
	const bytes = new Uint8Array(binary.length);
	for (let i = 0; i < binary.length; i += 1) {
		bytes[i] = binary.charCodeAt(i);
	}
	return new TextDecoder().decode(bytes);
}

function getEncodedSavePayload() {
	return encodeBase64(JSON.stringify(getSavePayload()));
}

function applySavePayload(payload) {
	if (!payload || !Array.isArray(payload.unlocked)) {
		return false;
	}
	stageTwoUnlocked = Boolean(payload.stageTwoUnlocked);
	rebuildActiveData();
	unlocked.clear();
	for (const item of payload.unlocked) {
		const canonical = toCanonicalName(item);
		if (activeElementSet.has(canonical)) {
			unlocked.add(canonical);
		}
	}
	if (unlocked.size === 0) {
		for (const base of STAGE_ONE.baseElements) {
			unlocked.add(toCanonicalName(base));
		}
	}
	maybeUnlockStageTwo();
	return true;
}

function saveGame() {
	try {
		localStorage.setItem(SAVE_KEY, getEncodedSavePayload());
	} catch (error) {
	}
}

function loadGame() {
	try {
		const encoded = localStorage.getItem(SAVE_KEY);
		if (!encoded) {
			return;
		}
		const raw = decodeBase64(encoded);
		const parsed = JSON.parse(raw);
		applySavePayload(parsed);
	} catch (error) {
	}
}

async function copySaveDataToClipboard() {
	const encodedSave = getEncodedSavePayload();
	saveDataInput.value = encodedSave;
	try {
		await navigator.clipboard.writeText(encodedSave);
		resultText.textContent = "save data copied to clipboard.";
	} catch (error) {
		resultText.textContent = "could not copy save data.";
	}
}

function importSaveData() {
	const encoded = saveDataInput.value.trim();
	if (!encoded) {
		resultText.textContent = "could not import save data.";
		return;
	}
	try {
		const raw = decodeBase64(encoded);
		const parsed = JSON.parse(raw);
		if (!applySavePayload(parsed)) {
			resultText.textContent = "could not import save data.";
			return;
		}
		populateElementOptions();
		renderInventory();
		saveGame();
		resultText.textContent = "save data imported.";
	} catch (error) {
		resultText.textContent = "could not import save data.";
	}
}

function clearSaveData() {
	stageTwoUnlocked = false;
	rebuildActiveData();
	unlocked.clear();
	for (const base of STAGE_ONE.baseElements) {
		unlocked.add(toCanonicalName(base));
	}
	saveDataInput.value = "";
	localStorage.removeItem(SAVE_KEY);
	populateElementOptions();
	renderInventory();
	resultText.textContent = "save data cleared.";
}

rebuildActiveData();
loadGame();
maybeUnlockStageTwo();
populateElementOptions();
renderInventory();
saveDataInput.value = getEncodedSavePayload();
saveGame();
setInterval(saveGame, SAVE_INTERVAL_MS);

form.addEventListener("submit", (event) => {
	event.preventDefault();
	combineSelectedElements();
});

function handleSelectEnterKey(event) {
	if (event.key !== "Enter") {
		return;
	}
	event.preventDefault();
	combineSelectedElements();
}

firstSelect.addEventListener("keydown", handleSelectEnterKey);
secondSelect.addEventListener("keydown", handleSelectEnterKey);

copySaveButton.addEventListener("click", () => {
	copySaveDataToClipboard();
});

importSaveButton.addEventListener("click", () => {
	importSaveData();
});

clearSaveButton.addEventListener("click", () => {
	clearSaveData();
});
